version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: meteor-node-stubs
    versions:
    - 1.0.1
    - 1.0.2
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: elliptic
    versions:
    - 6.5.3
