locations_en = [
{name:'birthday',roles:['event']},
{name:'election',roles:['event']},
{name:'festivus',roles:['festivity']},
{name:'hanukkah',roles:['festivity']},
{name:'yardsale',roles:['event']},
{name:'funeral',roles:['event']},
{name:'grandma',roles:['family']},
{name:'grandpa',roles:['family']},
{name:'husband',roles:['family']},
{name:'kwanzaa',roles:['festivity']},
{name:'parents',roles:['family']},
{name:'wedding',roles:['festivity']},
{name:'bracelet',roles:['valuables']},
{name:'crystal',roles:['valuables']},
{name:'diamond',roles:['valuables']},
{name:'emerald',roles:['valuables']},
{name:'jewelry',roles:['valuables']},
{name:'bromance',roles:['social']},
{name:'checkers',roles:['games']},
{name:'follower',roles:['social']},
{name:'highfive',roles:['social']},
{name:'hulahoop',roles:['toy']},
{name:'joystick',roles:['games']},
{name:'lemonade',roles:['beverage']},
{name:'marriage',roles:['social']},
{name:'monopoly',roles:['games']},
{name:'pinwheel',roles:['toy']},
{name:'scrabble',roles:['games']},
{name:'smoothie',roles:['beverage']},
{name:'swingset',roles:['toy']},
{name:'balloon',roles:['toy']},
{name:'divorce',roles:['social']},
{name:'dreidel',roles:['toy']},
{name:'frenemy',roles:['social']},
{name:'gameboy',roles:['toy']},
{name:'martini',roles:['beverage']},
{name:'pinball',roles:['games']},
{name:'sixpack',roles:['beverage']},
{name:'tequila',roles:['beverage']},
{name:'whiskey',roles:['beverage']},
{name:'yahtzee',roles:['games']},
{name:'barstool',roles:['furniture']},
{name:'bookcase',roles:['furniture']},
{name:'chainsaw',roles:['tool']},
{name:'scissors',roles:['tool']},
{name:'tweezers',roles:['tool']},
{name:'waterbed',roles:['furniture']},
{name:'bathtub',roles:['furniture']},
{name:'bunkbed',roles:['furniture']},
{name:'cabinet',roles:['furniture']},
{name:'compass',roles:['tool']},
{name:'crowbar',roles:['tool']},
{name:'dresser',roles:['furniture']},
{name:'dustpan',roles:['tool']},
{name:'stapler',roles:['tool']},
{name:'lipstick',roles:['toiletries']},
{name:'perfume',roles:['toiletries']},
{name:'shampoo',roles:['toiletries']},
{name:'nailfile',roles:['toiletries']},
{name:'sunblock',roles:['toiletries']},
{name:'hairdye',roles:['toiletries']},
{name:'hairgel',roles:['toiletries']},
{name:'mascara',roles:['toiletries']},
{name:'computer',roles:['computing']},
{name:'facebook',roles:['computing']},
{name:'firewall',roles:['computing']},
{name:'keyboard',roles:['computing']},
{name:'password',roles:['computing']},
{name:'hashtag',roles:['computing']},
{name:'macbook',roles:['computing']},
{name:'twitter',roles:['computing']},
{name:'catapult',roles:['weapon']},
{name:'crossbow',roles:['weapon']},
{name:'dynamite',roles:['weapon']},
{name:'fireball',roles:['weapon']},
{name:'bayonet',roles:['weapon']},
{name:'bazooka',roles:['weapon']},
{name:'handgun',roles:['weapon']},
{name:'missile',roles:['weapon']},
{name:'shotgun',roles:['weapon']},
{name:'torpedo',roles:['weapon']},
{name:'cannon',roles:['weapon']},
{name:'earmuffs',roles:['clothing']},
{name:'eyepatch',roles:['accessory']},
{name:'headband',roles:['accessory']},
{name:'kneepads',roles:['accessory']},
{name:'necklace',roles:['accessory']},
{name:'nosering',roles:['accessory']},
{name:'overalls',roles:['clothing']},
{name:'pantsuit',roles:['clothing']},
{name:'partyhat',roles:['accessory']},
{name:'raincoat',roles:['clothing']},
{name:'shoelace',roles:['accessory']},
{name:'slippers',roles:['clothing']},
{name:'sneakers',roles:['clothing']},
{name:'swimsuit',roles:['clothing']},
{name:'umbrella',roles:['accessory']},
{name:'bandana',roles:['accessory']},
{name:'earring',roles:['accessory']},
{name:'hairtie',roles:['accessory']},
{name:'handbag',roles:['accessory']},
{name:'mittens',roles:['clothing']},
{name:'pajamas',roles:['clothing']},
{name:'sandals',roles:['clothing']},
{name:'sweater',roles:['clothing']},
{name:'bikini',roles:['clothing']},
{name:'crutches',roles:['medical']},
{name:'dandruff',roles:['medical']},
{name:'dentures',roles:['medical']},
{name:'firstaid',roles:['medical']},
{name:'headache',roles:['medical']},
{name:'hospital',roles:['medical']},
{name:'insomnia',roles:['medical']},
{name:'medicine',roles:['medical']},
{name:'papercut',roles:['medical']},
{name:'seasick',roles:['medical']},
{name:'sunburn',roles:['medical']},
{name:'vaccine',roles:['medical']},
{name:'vitamin',roles:['medical']},
{name:'branches',roles:['plant']},
{name:'eggplant',roles:['plant']},
{name:'hongkong',roles:['geography']},
{name:'palmtree',roles:['plant']},
{name:'pinecone',roles:['plant']},
{name:'pinetree',roles:['plant']},
{name:'primrose',roles:['plant']},
{name:'scotland',roles:['geography']},
{name:'america',roles:['geography']},
{name:'atlanta',roles:['geography']},
{name:'bahamas',roles:['geography']},
{name:'england',roles:['geography']},
{name:'finland',roles:['geography']},
{name:'florida',roles:['geography']},
{name:'germany',roles:['geography']},
{name:'holland',roles:['geography']},
{name:'ireland',roles:['geography']},
{name:'jamaica',roles:['geography']},
{name:'newyork',roles:['geography']},
{name:'oaktree',roles:['plant']},
{name:'orlando',roles:['geography']},
{name:'seaweed',roles:['plant']},
{name:'bamboo',roles:['plant']},
{name:'carrot',roles:['plant']},
{name:'celery',roles:['plant']},
{name:'cherry',roles:['plant']},
{name:'garlic',roles:['plant']},
{name:'grapes',roles:['plant']},
{name:'backbone',roles:['anatomy']},
{name:'cemetery',roles:['location location location']},
{name:'forehead',roles:['anatomy']},
{name:'mustache',roles:['anatomy']},
{name:'nosehair',roles:['anatomy']},
{name:'shoulder',roles:['anatomy']},
{name:'skeleton',roles:['anatomy']},
{name:'tentacle',roles:['anatomy']},
{name:'whiskers',roles:['anatomy']},
{name:'eyeball',roles:['anatomy']},
{name:'eyebrow',roles:['anatomy']},
{name:'eyelash',roles:['anatomy']},
{name:'kneecap',roles:['anatomy']},
{name:'knuckle',roles:['anatomy']},
{name:'library',roles:['location location location']},
{name:'mansion',roles:['location location location']},
{name:'petshop',roles:['location location location']},
{name:'stomach',roles:['anatomy']},
{name:'theater',roles:['location location location']},
{name:'unibrow',roles:['anatomy']},
{name:'africa',roles:['location location location']},
{name:'brazil',roles:['location location location']},
{name:'canada',roles:['location location location']},
{name:'casino',roles:['location location location']},
{name:'castle',roles:['location location location']},
{name:'church',roles:['location location location']},
{name:'circus',roles:['location location location']},
{name:'dallas',roles:['location location location']},
{name:'france',roles:['location location location']},
{name:'hawaii',roles:['location location location']},
{name:'rowboat',roles:['transportation']},
{name:'shuttle',roles:['transportation']},
{name:'airplane',roles:['transportation']},
{name:'forklift',roles:['transportation']},
{name:'golfcart',roles:['transportation']},
{name:'sailboat',roles:['transportation']},
{name:'towtruck',roles:['transportation']},
{name:'tricycle',roles:['transportation']},
{name:'zeppelin',roles:['transportation']},
{name:'bicycle',roles:['transportation']},
{name:'dogsled',roles:['transportation']},
{name:'minivan',roles:['transportation']},
{name:'porsche',roles:['transportation']},
{name:'scooter',roles:['transportation']},
{name:'tractor',roles:['transportation']},
{name:'tugboat',roles:['transportation']},
{name:'bagpipes',roles:['music']},
{name:'guitar',roles:['music']},
{name:'daftpunk',roles:['music']},
{name:'macarena',roles:['music']},
{name:'musicbox',roles:['music']},
{name:'skrillex',roles:['music']},
{name:'trombone',roles:['music']},
{name:'beatles',roles:['music']},
{name:'beyonce',roles:['music']},
{name:'blondie',roles:['music']},
{name:'bonjovi',roles:['music']},
{name:'drumset',roles:['music']},
{name:'dubstep',roles:['music']},
{name:'nirvana',roles:['music']},
{name:'outkast',roles:['music']},
{name:'shakira',roles:['music']},
{name:'ukulele',roles:['music']},
{name:'griffin',roles:['mythology']},
{name:'atlantis',roles:['mythology']},
{name:'hercules',roles:['mythology']},
{name:'minotaur',roles:['mythology']},
{name:'poseidon',roles:['mythology']},
{name:'bigfoot',roles:['mythology']},
{name:'centaur',roles:['mythology']},
{name:'cyclops',roles:['mythology']},
{name:'goddess',roles:['mythology']},
{name:'jupiter',roles:['mythology']},
{name:'mermaid',roles:['mythology']},
{name:'monster',roles:['mythology']},
{name:'neptune',roles:['mythology']},
{name:'pegasus',roles:['mythology']},
{name:'phoenix',roles:['mythology']},
{name:'unicorn',roles:['mythology']},
{name:'vampire',roles:['mythology']},
{name:'dragon',roles:['mythology']},
{name:'angelina',roles:['famous person']},
{name:'bob dylan',roles:['famous person']},
{name:'brad pitt',roles:['famous person']},
{name:'bruce lee',roles:['famous person']},
{name:'geronimo',roles:['famous person']},
{name:'greenday',roles:['famous person']},
{name:'katemoss',roles:['famous person']},
{name:'ladygaga',roles:['famous person']},
{name:'lilwayne',roles:['famous person']},
{name:'ludacris',roles:['famous person']},
{name:'mchammer',roles:['famous person']},
{name:'tomhanks',roles:['famous person']},
{name:'beckham',roles:['famous person']},
{name:'colbert',roles:['famous person']},
{name:'jayleno',roles:['famous person']},
{name:'lincoln',roles:['famous person']},
{name:'picasso',roles:['famous person']},
{name:'rihanna',roles:['famous person']},
{name:'vangogh',roles:['famous person']},
{name:'justin bieber',roles:['famous person']},
{name:'eminem',roles:['famous person']},
{name:'gandhi',roles:['famous person']},
{name:'baseball',roles:['sports']},
{name:'dumbbell',roles:['sports']},
{name:'football',roles:['sports']},
{name:'goalpost',roles:['sports']},
{name:'golfclub',roles:['sports']},
{name:'halfpipe',roles:['sports']},
{name:'handball',roles:['sports']},
{name:'iceskate',roles:['sports']},
{name:'jumprope',roles:['sports']},
{name:'longjump',roles:['sports']},
{name:'minigolf',roles:['sports']},
{name:'olympics',roles:['sports']},
{name:'pingpong',roles:['sports']},
{name:'slamdunk',roles:['sports']},
{name:'sledding',roles:['sports']},
{name:'swimming',roles:['sports']},
{name:'archery',roles:['sports']},
{name:'bowling',roles:['sports']},
{name:'fencing',roles:['sports']},
{name:'fishing',roles:['sports']},
{name:'frisbee',roles:['sports']},
{name:'homerun',roles:['sports']},
{name:'javelin',roles:['sports']},
{name:'rebound',roles:['sports']},
{name:'referee',roles:['sports']},
{name:'boxing',roles:['sports']},
{name:'haymitch',roles:['pop culture']},
{name:'autobots',roles:['pop culture']},
{name:'avengers',roles:['pop culture']},
{name:'catwoman',roles:['pop culture']},
{name:'garfield',roles:['pop culture']},
{name:'ironchef',roles:['pop culture']},
{name:'lionking',roles:['pop culture']},
{name:'splinter',roles:['pop culture']},
{name:'startrek',roles:['pop culture']},
{name:'starwars',roles:['pop culture']},
{name:'superman',roles:['pop culture']},
{name:'aladdin',roles:['pop culture']},
{name:'aquaman',roles:['pop culture']},
{name:'asterix',roles:['pop culture']},
{name:'hawkeye',roles:['pop culture']},
{name:'katniss',roles:['pop culture']},
{name:'madonna',roles:['pop culture']},
{name:'metroid',roles:['pop culture']},
{name:'pikachu',roles:['pop culture']},
{name:'riddler',roles:['pop culture']},
{name:'rugrats',roles:['pop culture']},
{name:'twoface',roles:['pop culture']},
{name:'avatar',roles:['pop culture']},
{name:'barbie',roles:['pop culture']},
{name:'batman',roles:['pop culture']},
{name:'beavis',roles:['pop culture']},
{name:'bowser',roles:['pop culture']},
{name:'assassin',roles:['profession']},
{name:'director',roles:['profession']},
{name:'gangster',roles:['profession']},
{name:'gardener',roles:['profession']},
{name:'magician',roles:['profession']},
{name:'princess',roles:['profession']},
{name:'waitress',roles:['profession']},
{name:'wrestler',roles:['profession']},
{name:'butcher',roles:['profession']},
{name:'captain',roles:['profession']},
{name:'cashier',roles:['profession']},
{name:'cowgirl',roles:['profession']},
{name:'dentist',roles:['profession']},
{name:'drummer',roles:['profession']},
{name:'gymnast',roles:['profession']},
{name:'mailman',roles:['profession']},
{name:'milkman',roles:['profession']},
{name:'painter',roles:['profession']},
{name:'plumber',roles:['profession']},
{name:'poolboy',roles:['profession']},
{name:'sheriff',roles:['profession']},
{name:'soldier',roles:['profession']},
{name:'surgeon',roles:['profession']},
{name:'teacher',roles:['profession']},
{name:'warrior',roles:['profession']},
{name:'artist',roles:['profession']},
{name:'barber',roles:['profession']},
{name:'cowboy',roles:['profession']},
{name:'doctor',roles:['profession']},
{name:'farmer',roles:['profession']},
{name:'dinosaur',roles:['animal']},
{name:'elephant',roles:['animal']},
{name:'flamingo',roles:['animal']},
{name:'goldfish',roles:['animal']},
{name:'kangaroo',roles:['animal']},
{name:'mosquito',roles:['animal']},
{name:'penguins',roles:['animal']},
{name:'reindeer',roles:['animal']},
{name:'scorpion',roles:['animal']},
{name:'seahorse',roles:['animal']},
{name:'squirrel',roles:['animal']},
{name:'starfish',roles:['animal']},
{name:'tortoise',roles:['animal']},
{name:'beehive',roles:['animal']},
{name:'buffalo',roles:['animal']},
{name:'catfish',roles:['animal']},
{name:'chicken',roles:['animal']},
{name:'dolphin',roles:['animal']},
{name:'feather',roles:['animal']},
{name:'firefly',roles:['animal']},
{name:'firefox',roles:['animal']},
{name:'giraffe',roles:['animal']},
{name:'gorilla',roles:['animal']},
{name:'hamster',roles:['animal']},
{name:'ladybug',roles:['animal']},
{name:'lamprey',roles:['animal']},
{name:'leopard',roles:['animal']},
{name:'lobster',roles:['animal']},
{name:'mammoth',roles:['animal']},
{name:'narwhal',roles:['animal']},
{name:'octopus',roles:['animal']},
{name:'ostrich',roles:['animal']},
{name:'peacock',roles:['animal']},
{name:'penguin',roles:['animal']},
{name:'pitbull',roles:['animal']},
{name:'raccoon',roles:['animal']},
{name:'reptile',roles:['animal']},
{name:'rooster',roles:['animal']},
{name:'seagull',roles:['animal']},
{name:'tadpole',roles:['animal']},
{name:'banana',roles:['animal']},
{name:'donkey',roles:['animal']},
{name:'baguette',roles:['food']},
{name:'barbeque',roles:['food']},
{name:'broccoli',roles:['food']},
{name:'espresso',roles:['food']},
{name:'fastfood',roles:['food']},
{name:'frosting',roles:['food']},
{name:'hotsauce',roles:['food']},
{name:'junkfood',roles:['food']},
{name:'lollipop',roles:['food']},
{name:'macaroni',roles:['food']},
{name:'meatball',roles:['food']},
{name:'mushroom',roles:['food']},
{name:'pancakes',roles:['food']},
{name:'popsicle',roles:['food']},
{name:'sandwich',roles:['food']},
{name:'skittles',roles:['food']},
{name:'snowcone',roles:['food']},
{name:'soysauce',roles:['food']},
{name:'avocado',roles:['food']},
{name:'brownie',roles:['food']},
{name:'burrito',roles:['food']},
{name:'coconut',roles:['food']},
{name:'cookies',roles:['food']},
{name:'corndog',roles:['food']},
{name:'cupcake',roles:['food']},
{name:'doritos',roles:['food']},
{name:'eggroll',roles:['food']},
{name:'hambone',roles:['food']},
{name:'hamwich',roles:['food']},
{name:'ketchup',roles:['food']},
{name:'mustard',roles:['food']},
{name:'noodles',roles:['food']},
{name:'oatmeal',roles:['food']},
{name:'pancake',roles:['food']},
{name:'peaches',roles:['food']},
{name:'popcorn',roles:['food']},
{name:'pretzel',roles:['food']},
{name:'pumpkin',roles:['food']},
{name:'sausage',roles:['food']},
{name:'seafood',roles:['food']},
{name:'spinach',roles:['food']},
{name:'twinkie',roles:['food']},
{name:'cereal',roles:['food']},
{name:'cheese',roles:['food']},
{name:'coffee',roles:['food']},
{name:'cookie',roles:['food']},
]