words_en = [
{text:'birthday',category:'event'},
{text:'election',category:'event'},
{text:'festivus',category:'festivity'},
{text:'hanukkah',category:'festivity'},
{text:'yardsale',category:'event'},
{text:'funeral',category:'event'},
{text:'grandma',category:'family'},
{text:'grandpa',category:'family'},
{text:'husband',category:'family'},
{text:'kwanzaa',category:'festivity'},
{text:'parents',category:'family'},
{text:'wedding',category:'festivity'},
{text:'bracelet',category:'valuables'},
{text:'crystal',category:'valuables'},
{text:'diamond',category:'valuables'},
{text:'emerald',category:'valuables'},
{text:'jewelry',category:'valuables'},
{text:'bromance',category:'social'},
{text:'checkers',category:'games'},
{text:'follower',category:'social'},
{text:'highfive',category:'social'},
{text:'hulahoop',category:'toy'},
{text:'joystick',category:'games'},
{text:'lemonade',category:'beverage'},
{text:'marriage',category:'social'},
{text:'monopoly',category:'games'},
{text:'pinwheel',category:'toy'},
{text:'scrabble',category:'games'},
{text:'smoothie',category:'beverage'},
{text:'swingset',category:'toy'},
{text:'balloon',category:'toy'},
{text:'divorce',category:'social'},
{text:'dreidel',category:'toy'},
{text:'frenemy',category:'social'},
{text:'gameboy',category:'toy'},
{text:'martini',category:'beverage'},
{text:'pinball',category:'games'},
{text:'sixpack',category:'beverage'},
{text:'tequila',category:'beverage'},
{text:'whiskey',category:'beverage'},
{text:'yahtzee',category:'games'},
{text:'barstool',category:'furniture'},
{text:'bookcase',category:'furniture'},
{text:'chainsaw',category:'tool'},
{text:'scissors',category:'tool'},
{text:'tweezers',category:'tool'},
{text:'waterbed',category:'furniture'},
{text:'bathtub',category:'furniture'},
{text:'bunkbed',category:'furniture'},
{text:'cabinet',category:'furniture'},
{text:'compass',category:'tool'},
{text:'crowbar',category:'tool'},
{text:'dresser',category:'furniture'},
{text:'dustpan',category:'tool'},
{text:'stapler',category:'tool'},
{text:'lipstick',category:'toiletries'},
{text:'perfume',category:'toiletries'},
{text:'shampoo',category:'toiletries'},
{text:'nailfile',category:'toiletries'},
{text:'sunblock',category:'toiletries'},
{text:'hairdye',category:'toiletries'},
{text:'hairgel',category:'toiletries'},
{text:'mascara',category:'toiletries'},
{text:'computer',category:'computing'},
{text:'facebook',category:'computing'},
{text:'firewall',category:'computing'},
{text:'keyboard',category:'computing'},
{text:'password',category:'computing'},
{text:'hashtag',category:'computing'},
{text:'macbook',category:'computing'},
{text:'twitter',category:'computing'},
{text:'catapult',category:'weapon'},
{text:'crossbow',category:'weapon'},
{text:'dynamite',category:'weapon'},
{text:'fireball',category:'weapon'},
{text:'bayonet',category:'weapon'},
{text:'bazooka',category:'weapon'},
{text:'handgun',category:'weapon'},
{text:'missile',category:'weapon'},
{text:'shotgun',category:'weapon'},
{text:'torpedo',category:'weapon'},
{text:'cannon',category:'weapon'},
{text:'earmuffs',category:'clothing'},
{text:'eyepatch',category:'accessory'},
{text:'headband',category:'accessory'},
{text:'kneepads',category:'accessory'},
{text:'necklace',category:'accessory'},
{text:'nosering',category:'accessory'},
{text:'overalls',category:'clothing'},
{text:'pantsuit',category:'clothing'},
{text:'partyhat',category:'accessory'},
{text:'raincoat',category:'clothing'},
{text:'shoelace',category:'accessory'},
{text:'slippers',category:'clothing'},
{text:'sneakers',category:'clothing'},
{text:'swimsuit',category:'clothing'},
{text:'umbrella',category:'accessory'},
{text:'bandana',category:'accessory'},
{text:'earring',category:'accessory'},
{text:'hairtie',category:'accessory'},
{text:'handbag',category:'accessory'},
{text:'mittens',category:'clothing'},
{text:'pajamas',category:'clothing'},
{text:'sandals',category:'clothing'},
{text:'sweater',category:'clothing'},
{text:'bikini',category:'clothing'},
{text:'crutches',category:'medical'},
{text:'dandruff',category:'medical'},
{text:'dentures',category:'medical'},
{text:'firstaid',category:'medical'},
{text:'headache',category:'medical'},
{text:'hospital',category:'medical'},
{text:'insomnia',category:'medical'},
{text:'medicine',category:'medical'},
{text:'papercut',category:'medical'},
{text:'seasick',category:'medical'},
{text:'sunburn',category:'medical'},
{text:'vaccine',category:'medical'},
{text:'vitamin',category:'medical'},
{text:'branches',category:'plant'},
{text:'eggplant',category:'plant'},
{text:'hongkong',category:'geography'},
{text:'palmtree',category:'plant'},
{text:'pinecone',category:'plant'},
{text:'pinetree',category:'plant'},
{text:'primrose',category:'plant'},
{text:'scotland',category:'geography'},
{text:'america',category:'geography'},
{text:'atlanta',category:'geography'},
{text:'bahamas',category:'geography'},
{text:'england',category:'geography'},
{text:'finland',category:'geography'},
{text:'florida',category:'geography'},
{text:'germany',category:'geography'},
{text:'holland',category:'geography'},
{text:'ireland',category:'geography'},
{text:'jamaica',category:'geography'},
{text:'newyork',category:'geography'},
{text:'oaktree',category:'plant'},
{text:'orlando',category:'geography'},
{text:'seaweed',category:'plant'},
{text:'bamboo',category:'plant'},
{text:'carrot',category:'plant'},
{text:'celery',category:'plant'},
{text:'cherry',category:'plant'},
{text:'garlic',category:'plant'},
{text:'grapes',category:'plant'},
{text:'backbone',category:'anatomy'},
{text:'cemetery',category:'location location location'},
{text:'forehead',category:'anatomy'},
{text:'mustache',category:'anatomy'},
{text:'nosehair',category:'anatomy'},
{text:'shoulder',category:'anatomy'},
{text:'skeleton',category:'anatomy'},
{text:'tentacle',category:'anatomy'},
{text:'whiskers',category:'anatomy'},
{text:'eyeball',category:'anatomy'},
{text:'eyebrow',category:'anatomy'},
{text:'eyelash',category:'anatomy'},
{text:'kneecap',category:'anatomy'},
{text:'knuckle',category:'anatomy'},
{text:'library',category:'location location location'},
{text:'mansion',category:'location location location'},
{text:'petshop',category:'location location location'},
{text:'stomach',category:'anatomy'},
{text:'theater',category:'location location location'},
{text:'unibrow',category:'anatomy'},
{text:'africa',category:'location location location'},
{text:'brazil',category:'location location location'},
{text:'canada',category:'location location location'},
{text:'casino',category:'location location location'},
{text:'castle',category:'location location location'},
{text:'church',category:'location location location'},
{text:'circus',category:'location location location'},
{text:'dallas',category:'location location location'},
{text:'france',category:'location location location'},
{text:'hawaii',category:'location location location'},
{text:'rowboat',category:'transportation'},
{text:'shuttle',category:'transportation'},
{text:'airplane',category:'transportation'},
{text:'forklift',category:'transportation'},
{text:'golfcart',category:'transportation'},
{text:'sailboat',category:'transportation'},
{text:'towtruck',category:'transportation'},
{text:'tricycle',category:'transportation'},
{text:'zeppelin',category:'transportation'},
{text:'bicycle',category:'transportation'},
{text:'dogsled',category:'transportation'},
{text:'minivan',category:'transportation'},
{text:'porsche',category:'transportation'},
{text:'scooter',category:'transportation'},
{text:'tractor',category:'transportation'},
{text:'tugboat',category:'transportation'},
{text:'bagpipes',category:'music'},
{text:'guitar',category:'music'},
{text:'daftpunk',category:'music'},
{text:'macarena',category:'music'},
{text:'musicbox',category:'music'},
{text:'skrillex',category:'music'},
{text:'trombone',category:'music'},
{text:'beatles',category:'music'},
{text:'beyonce',category:'music'},
{text:'blondie',category:'music'},
{text:'bonjovi',category:'music'},
{text:'drumset',category:'music'},
{text:'dubstep',category:'music'},
{text:'nirvana',category:'music'},
{text:'outkast',category:'music'},
{text:'shakira',category:'music'},
{text:'ukulele',category:'music'},
{text:'griffin',category:'mythology'},
{text:'atlantis',category:'mythology'},
{text:'hercules',category:'mythology'},
{text:'minotaur',category:'mythology'},
{text:'poseidon',category:'mythology'},
{text:'bigfoot',category:'mythology'},
{text:'centaur',category:'mythology'},
{text:'cyclops',category:'mythology'},
{text:'goddess',category:'mythology'},
{text:'jupiter',category:'mythology'},
{text:'mermaid',category:'mythology'},
{text:'monster',category:'mythology'},
{text:'neptune',category:'mythology'},
{text:'pegasus',category:'mythology'},
{text:'phoenix',category:'mythology'},
{text:'unicorn',category:'mythology'},
{text:'vampire',category:'mythology'},
{text:'dragon',category:'mythology'},
{text:'angelina',category:'famous person'},
{text:'bob dylan',category:'famous person'},
{text:'brad pitt',category:'famous person'},
{text:'bruce lee',category:'famous person'},
{text:'geronimo',category:'famous person'},
{text:'greenday',category:'famous person'},
{text:'katemoss',category:'famous person'},
{text:'ladygaga',category:'famous person'},
{text:'lilwayne',category:'famous person'},
{text:'ludacris',category:'famous person'},
{text:'mchammer',category:'famous person'},
{text:'tomhanks',category:'famous person'},
{text:'beckham',category:'famous person'},
{text:'colbert',category:'famous person'},
{text:'jayleno',category:'famous person'},
{text:'lincoln',category:'famous person'},
{text:'picasso',category:'famous person'},
{text:'rihanna',category:'famous person'},
{text:'vangogh',category:'famous person'},
{text:'justin bieber',category:'famous person'},
{text:'eminem',category:'famous person'},
{text:'gandhi',category:'famous person'},
{text:'baseball',category:'sports'},
{text:'dumbbell',category:'sports'},
{text:'football',category:'sports'},
{text:'goalpost',category:'sports'},
{text:'golfclub',category:'sports'},
{text:'halfpipe',category:'sports'},
{text:'handball',category:'sports'},
{text:'iceskate',category:'sports'},
{text:'jumprope',category:'sports'},
{text:'longjump',category:'sports'},
{text:'minigolf',category:'sports'},
{text:'olympics',category:'sports'},
{text:'pingpong',category:'sports'},
{text:'slamdunk',category:'sports'},
{text:'sledding',category:'sports'},
{text:'swimming',category:'sports'},
{text:'archery',category:'sports'},
{text:'bowling',category:'sports'},
{text:'fencing',category:'sports'},
{text:'fishing',category:'sports'},
{text:'frisbee',category:'sports'},
{text:'homerun',category:'sports'},
{text:'javelin',category:'sports'},
{text:'rebound',category:'sports'},
{text:'referee',category:'sports'},
{text:'boxing',category:'sports'},
{text:'haymitch',category:'pop culture'},
{text:'autobots',category:'pop culture'},
{text:'avengers',category:'pop culture'},
{text:'catwoman',category:'pop culture'},
{text:'garfield',category:'pop culture'},
{text:'ironchef',category:'pop culture'},
{text:'lionking',category:'pop culture'},
{text:'splinter',category:'pop culture'},
{text:'startrek',category:'pop culture'},
{text:'starwars',category:'pop culture'},
{text:'superman',category:'pop culture'},
{text:'aladdin',category:'pop culture'},
{text:'aquaman',category:'pop culture'},
{text:'asterix',category:'pop culture'},
{text:'hawkeye',category:'pop culture'},
{text:'katniss',category:'pop culture'},
{text:'madonna',category:'pop culture'},
{text:'metroid',category:'pop culture'},
{text:'pikachu',category:'pop culture'},
{text:'riddler',category:'pop culture'},
{text:'rugrats',category:'pop culture'},
{text:'twoface',category:'pop culture'},
{text:'avatar',category:'pop culture'},
{text:'barbie',category:'pop culture'},
{text:'batman',category:'pop culture'},
{text:'beavis',category:'pop culture'},
{text:'bowser',category:'pop culture'},
{text:'assassin',category:'profession'},
{text:'director',category:'profession'},
{text:'gangster',category:'profession'},
{text:'gardener',category:'profession'},
{text:'magician',category:'profession'},
{text:'princess',category:'profession'},
{text:'waitress',category:'profession'},
{text:'wrestler',category:'profession'},
{text:'butcher',category:'profession'},
{text:'captain',category:'profession'},
{text:'cashier',category:'profession'},
{text:'cowgirl',category:'profession'},
{text:'dentist',category:'profession'},
{text:'drummer',category:'profession'},
{text:'gymnast',category:'profession'},
{text:'mailman',category:'profession'},
{text:'milkman',category:'profession'},
{text:'painter',category:'profession'},
{text:'plumber',category:'profession'},
{text:'poolboy',category:'profession'},
{text:'sheriff',category:'profession'},
{text:'soldier',category:'profession'},
{text:'surgeon',category:'profession'},
{text:'teacher',category:'profession'},
{text:'warrior',category:'profession'},
{text:'artist',category:'profession'},
{text:'barber',category:'profession'},
{text:'cowboy',category:'profession'},
{text:'doctor',category:'profession'},
{text:'farmer',category:'profession'},
{text:'dinosaur',category:'animal'},
{text:'elephant',category:'animal'},
{text:'flamingo',category:'animal'},
{text:'goldfish',category:'animal'},
{text:'kangaroo',category:'animal'},
{text:'mosquito',category:'animal'},
{text:'penguins',category:'animal'},
{text:'reindeer',category:'animal'},
{text:'scorpion',category:'animal'},
{text:'seahorse',category:'animal'},
{text:'squirrel',category:'animal'},
{text:'starfish',category:'animal'},
{text:'tortoise',category:'animal'},
{text:'beehive',category:'animal'},
{text:'buffalo',category:'animal'},
{text:'catfish',category:'animal'},
{text:'chicken',category:'animal'},
{text:'dolphin',category:'animal'},
{text:'feather',category:'animal'},
{text:'firefly',category:'animal'},
{text:'firefox',category:'animal'},
{text:'giraffe',category:'animal'},
{text:'gorilla',category:'animal'},
{text:'hamster',category:'animal'},
{text:'ladybug',category:'animal'},
{text:'lamprey',category:'animal'},
{text:'leopard',category:'animal'},
{text:'lobster',category:'animal'},
{text:'mammoth',category:'animal'},
{text:'narwhal',category:'animal'},
{text:'octopus',category:'animal'},
{text:'ostrich',category:'animal'},
{text:'peacock',category:'animal'},
{text:'penguin',category:'animal'},
{text:'pitbull',category:'animal'},
{text:'raccoon',category:'animal'},
{text:'reptile',category:'animal'},
{text:'rooster',category:'animal'},
{text:'seagull',category:'animal'},
{text:'tadpole',category:'animal'},
{text:'banana',category:'animal'},
{text:'donkey',category:'animal'},
{text:'baguette',category:'food'},
{text:'barbeque',category:'food'},
{text:'broccoli',category:'food'},
{text:'espresso',category:'food'},
{text:'fastfood',category:'food'},
{text:'frosting',category:'food'},
{text:'hotsauce',category:'food'},
{text:'junkfood',category:'food'},
{text:'lollipop',category:'food'},
{text:'macaroni',category:'food'},
{text:'meatball',category:'food'},
{text:'mushroom',category:'food'},
{text:'pancakes',category:'food'},
{text:'popsicle',category:'food'},
{text:'sandwich',category:'food'},
{text:'skittles',category:'food'},
{text:'snowcone',category:'food'},
{text:'soysauce',category:'food'},
{text:'avocado',category:'food'},
{text:'brownie',category:'food'},
{text:'burrito',category:'food'},
{text:'coconut',category:'food'},
{text:'cookies',category:'food'},
{text:'corndog',category:'food'},
{text:'cupcake',category:'food'},
{text:'doritos',category:'food'},
{text:'eggroll',category:'food'},
{text:'hambone',category:'food'},
{text:'hamwich',category:'food'},
{text:'ketchup',category:'food'},
{text:'mustard',category:'food'},
{text:'noodles',category:'food'},
{text:'oatmeal',category:'food'},
{text:'pancake',category:'food'},
{text:'peaches',category:'food'},
{text:'popcorn',category:'food'},
{text:'pretzel',category:'food'},
{text:'pumpkin',category:'food'},
{text:'sausage',category:'food'},
{text:'seafood',category:'food'},
{text:'spinach',category:'food'},
{text:'twinkie',category:'food'},
{text:'cereal',category:'food'},
{text:'cheese',category:'food'},
{text:'coffee',category:'food'},
{text:'cookie',category:'food'},
]