words_fr = [
    { text: "grand-mère", category: "famille" },
    { text: "grand-père", category: "famille" },
    { text: "mari", category: "famille" },
    { text: "parents", category: "famille" },
    { text: "épouse", category: "famille" },
    { text: "oncle", category: "famille" },
    { text: "tante", category: "famille" },
    { text: "père", category: "famille" },
    { text: "mère", category: "famille" },
    { text: "demi-sœur", category: "famille" },
    { text: "demi-frère", category: "famille" },
    { text: "beau-père", category: "famille" },
    { text: "belle-mère", category: "famille" },
    { text: "parrain", category: "famille" },
    { text: "marraine", category: "famille" },
    { text: "belle-mère", category: "famille" },
    { text: "beau-père", category: "famille" },
    { text: "enfants", category: "famille" },
    { text: "frère", category: "famille" },
    { text: "sœur", category: "famille" },
    { text: "cousin", category: "famille" },
    { text: "petite-fille", category: "famille" },
    { text: "petit-fils", category: "famille" },
    { text: "nièce", category: "famille" },
    { text: "neveu", category: "famille" },

    { text: "Festivus", category: "festivité" },
    { text: "Hanoukka", category: "festivité" },
    { text: "Kwanzaa", category: "festivité" },
    { text: "mariage", category: "festivité" },
    { text: "anniversaire", category: "festivité" },
    { text: "Bar Mitzvah", category: "festivité" },
    { text: "Halloween", category: "festivité" },
    { text: "Oktoberfest", category: "festivité" },
    { text: "Noël", category: "festivité" },
    { text: "Jour des Morts", category: "festivité" },
    { text: "réveillon du Nouvel An", category: "festivité" },
    { text: "Jour de la Marmotte", category: "festivité" },
    { text: "Saint-Valentin", category: "festivité" },
    { text: "Saint-Patrick", category: "festivité" },
    { text: "Pâque", category: "festivité" },
    { text: "Pâques", category: "festivité" },
    { text: "Ramadan", category: "festivité" },
    { text: "Fête des Mères", category: "festivité" },
    { text: "Jour de l'Indépendance", category: "festivité" },
    { text: "Columbus Day", category: "festivité" },
    { text: "Diwali", category: "festivité" },
    { text: "Black Friday", category: "festivité" },
    { text: "Thanksgiving", category: "festivité" },
    { text: "élection", category: "festivité" },
    { text: "remise de diplôme", category: "festivité" },

    { text: "bracelet", category: "Objets de valeur" },
    { text: "cristal", category: "Objets de valeur" },
    { text: "diamant", category: "Objets de valeur" },
    { text: "émeraude", category: "Objets de valeur" },
    { text: "bijoux", category: "Objets de valeur" },
    { text: "lingot d'or", category: "Objets de valeur" },
    { text: "perles", category: "Objets de valeur" },

    { text: "bromance", category: "Interactions sociales" },
    { text: "follower", category: "Interactions sociales" },
    { text: "highfive", category: "Interactions sociales" },
    { text: "mariage", category: "Interactions sociales" },
    { text: "divorce", category: "Interactions sociales" },
    { text: "frenemy", category: "Interactions sociales" },

    { text: "hula hoop", category: "Jeux" },
    { text: "moulin à vent", category: "Jeux" },
    { text: "balançoire", category: "Jeux" },
    { text: "ballon", category: "Jeux" },
    { text: "toupie", category: "Jeux" },
    { text: "Game Boy", category: "Jeux" },
    { text: "flipper", category: "Jeux" },
    { text: "joystick", category: "Jeux" },
    { text: "Monopoly", category: "Jeux" },
    { text: "Scrabble", category: "Jeux" },
    { text: "jeu de dés", category: "Jeux" },

    { text: "chaise", category: "Mobilier" },
    { text: "tabouret de bar", category: "Mobilier" },
    { text: "bibliothèque", category: "Mobilier" },
    { text: "lit à eau", category: "Mobilier" },
    { text: "baignoire", category: "Mobilier" },
    { text: "lit superposé", category: "Mobilier" },
    { text: "armoire", category: "Mobilier" },
    { text: "commode", category: "Mobilier" },

    { text: "tronçonneuse", category: "Outils" },
    { text: "ciseaux", category: "Outils" },
    { text: "pince à épiler", category: "Outils" },
    { text: "compas", category: "Outils" },
    { text: "pied-de-biche", category: "Outils" },
    { text: "balayette", category: "Outils" },
    { text: "agrafeuse", category: "Outils" },

    { text: "rouge à lèvres", category: "Articles de toilette" },
    { text: "parfum", category: "Articles de toilette" },
    { text: "shampoing", category: "Articles de toilette" },
    { text: "lime à ongles", category: "Articles de toilette" },
    { text: "écran solaire", category: "Articles de toilette" },
    { text: "teinture pour cheveux", category: "Articles de toilette" },
    { text: "gel pour cheveux", category: "Articles de toilette" },
    { text: "mascara", category: "Articles de toilette" },

    { text: "ordinateur", category: "Informatique" },
    { text: "Facebook", category: "Informatique" },
    { text: "pare-feu", category: "Informatique" },
    { text: "clavier", category: "Informatique" },
    { text: "mot de passe", category: "Informatique" },
    { text: "hashtag", category: "Informatique" },
    { text: "MacBook", category: "Informatique" },
    { text: "Twitter", category: "Informatique" },

    { text: "hache de bataille", category: "Arme" },
    { text: "baïonnette", category: "Arme" },
    { text: "bazooka", category: "Arme" },
    { text: "canon", category: "Arme" },
    { text: "catapulte", category: "Arme" },
    { text: "arbalète", category: "Arme" },
    { text: "dynamite", category: "Arme" },
    { text: "pistolet", category: "Arme" },
    { text: "missile", category: "Arme" },
    { text: "fusil de chasse", category: "Arme" },
    { text: "épée", category: "Arme" },
    { text: "torpille", category: "Arme" },
    { text: "marteau de guerre", category: "Arme" },

    { text: "cache-œil", category: "Accessoire" },
    { text: "bandeau", category: "Accessoire" },
    { text: "genouillères", category: "Accessoire" },
    { text: "collier", category: "Accessoire" },
    { text: "anneau nasal", category: "Accessoire" },
    { text: "chapeau de fête", category: "Accessoire" },
    { text: "lacet de chaussure", category: "Accessoire" },
    { text: "parapluie", category: "Accessoire" },
    { text: "bandana", category: "Accessoire" },
    { text: "boucle d'oreille", category: "Accessoire" },
    { text: "élastique à cheveux", category: "Accessoire" },
    { text: "sac à main", category: "Accessoire" },
    { text: "mouchoir", category: "Accessoire" },

    { text: "ceinture de chasteté", category: "Vêtement" },
    { text: "haut-de-forme", category: "Vêtement" },
    { text: "tailleur-pantalon", category: "Vêtement" },
    { text: "bandeau", category: "Vêtement" },
    { text: "ceinture", category: "Vêtement" },
    { text: "bikini", category: "Vêtement" },
    { text: "bottes", category: "Vêtement" },
    { text: "nœud papillon", category: "Vêtement" },
    { text: "chapeau de cow-boy", category: "Vêtement" },
    { text: "casquette", category: "Vêtement" },
    { text: "manteau", category: "Vêtement" },
    { text: "robe", category: "Vêtement" },
    { text: "cache-oreilles", category: "Vêtement" },
    { text: "lunettes", category: "Vêtement" },
    { text: "gants", category: "Vêtement" },
    { text: "élastique à cheveux", category: "Vêtement" },
    { text: "sweat à capuche", category: "Vêtement" },
    { text: "chapeau", category: "Vêtement" },
    { text: "bandeau", category: "Vêtement" },
    { text: "veste", category: "Vêtement" },
    { text: "jean", category: "Vêtement" },
    { text: "genouillères", category: "Vêtement" },
    { text: "mitaines", category: "Vêtement" },
    { text: "collier", category: "Vêtement" },
    { text: "salopette", category: "Vêtement" },
    { text: "pyjama", category: "Vêtement" },
    { text: "chapeau de fête", category: "Vêtement" },
    { text: "imperméable", category: "Vêtement" },
    { text: "sandales", category: "Vêtement" },
    { text: "écharpe", category: "Vêtement" },
    { text: "chemise", category: "Vêtement" },
    { text: "chaussures", category: "Vêtement" },
    { text: "jupe", category: "Vêtement" },
    { text: "pantoufles", category: "Vêtement" },
    { text: "baskets", category: "Vêtement" },
    { text: "chaussettes", category: "Vêtement" },
    { text: "sombrero", category: "Vêtement" },
    { text: "bas", category: "Vêtement" },
    { text: "costume", category: "Vêtement" },
    { text: "pull", category: "Vêtement" },
    { text: "sweat-shirt", category: "Vêtement" },
    { text: "maillot de bain", category: "Vêtement" },
    { text: "t-shirt", category: "Vêtement" },
    { text: "cravate", category: "Vêtement" },
    { text: "pantalon", category: "Vêtement" },
    { text: "caleçon", category: "Vêtement" },

    { text: "béquilles", category: "Medical" },
    { text: "pellicules", category: "Medical" },
    { text: "dentiers", category: "Medical" },
    { text: "premiers soins", category: "Medical" },
    { text: "mal de tête", category: "Medical" },
    { text: "hôpital", category: "Medical" },
    { text: "insomnie", category: "Medical" },
    { text: "médicament", category: "Medical" },
    { text: "coupure de papier", category: "Medical" },
    { text: "mal de mer", category: "Medical" },
    { text: "coup de soleil", category: "Medical" },
    { text: "vaccin", category: "Medical" },
    { text: "vitamine", category: "Medical" },

    { text: "Hong Kong", category: "Geographie" },
    { text: "Écosse", category: "Geographie" },
    { text: "Amérique", category: "Geographie" },
    { text: "Atlanta", category: "Geographie" },
    { text: "Bahamas", category: "Geographie" },
    { text: "Angleterre", category: "Geographie" },
    { text: "Finlande", category: "Geographie" },
    { text: "Floride", category: "Geographie" },
    { text: "Allemagne", category: "Geographie" },
    { text: "Hollande", category: "Geographie" },
    { text: "Irlande", category: "Geographie" },
    { text: "Jamaïque", category: "Geographie" },
    { text: "New York", category: "Geographie" },
    { text: "Orlando", category: "Geographie" },

    { text: "chou", category: "Plante" },
    { text: "plaquemine", category: "Plante" },
    { text: "concombre", category: "Plante" },
    { text: "courgette", category: "Plante" },
    { text: "pastèque", category: "Plante" },
    { text: "mangue", category: "Plante" },
    { text: "citron", category: "Plante" },
    { text: "citron vert", category: "Plante" },
    { text: "pomme de terre", category: "Plante" },
    { text: "cactus", category: "Plante" },
    { text: "tomate", category: "Plante" },
    { text: "aubergine", category: "Plante" },
    { text: "palmier", category: "Plante" },
    { text: "cône de pin", category: "Plante" },
    { text: "pin", category: "Plante" },
    { text: "primevère", category: "Plante" },
    { text: "chêne", category: "Plante" },
    { text: "algues", category: "Plante" },
    { text: "bambou", category: "Plante" },
    { text: "carotte", category: "Plante" },
    { text: "céleri", category: "Plante" },
    { text: "cerise", category: "Plante" },
    { text: "ail", category: "Plante" },
    { text: "raisins", category: "Plante" },
    { text: "coriandre", category: "Plante" },
    { text: "banane", category: "Plante" },
    { text: "brocoli", category: "Plante" },
    { text: "avocat", category: "Plante" },
    { text: "noix de coco", category: "Plante" },
    { text: "pêches", category: "Plante" },
    { text: "épinards", category: "Plante" },
    { text: "ananas", category: "Plante" },
    { text: "blé", category: "Plante" },
    { text: "orange", category: "Plante" },

    { text: "colonne vertébrale", category: "Anatomie" },
    { text: "front", category: "Anatomie" },
    { text: "moustache", category: "Anatomie" },
    { text: "poil de nez", category: "Anatomie" },
    { text: "épaule", category: "Anatomie" },
    { text: "squelette", category: "Anatomie" },
    { text: "tentacule", category: "Anatomie" },
    { text: "moustaches (whiskers)", category: "Anatomie" },
    { text: "globe oculaire", category: "Anatomie" },
    { text: "sourcil", category: "Anatomie" },
    { text: "cil", category: "Anatomie" },
    { text: "rotule", category: "Anatomie" },
    { text: "articulation", category: "Anatomie" },
    { text: "estomac", category: "Anatomie" },
    { text: "unibrow", category: "Anatomie" },

    { text: "aéroport", category: "Endroit" },
    { text: "immeuble d'appartements", category: "Endroit" },
    { text: "banque", category: "Endroit" },
    { text: "salon de coiffure", category: "Endroit" },
    { text: "bar", category: "Endroit" },
    { text: "grange", category: "Endroit" },
    { text: "plage", category: "Endroit" },
    { text: "librairie", category: "Endroit" },
    { text: "bowling", category: "Endroit" },
    { text: "arrêt de bus", category: "Endroit" },
    { text: "casino", category: "Endroit" },
    { text: "cathédrale", category: "Endroit" },
    { text: "château", category: "Endroit" },
    { text: "cimetière", category: "Endroit" },
    { text: "église", category: "Endroit" },
    { text: "cirque", category: "Endroit" },
    { text: "dépanneur", category: "Endroit" },
    { text: "palais de justice", category: "Endroit" },
    { text: "désert", category: "Endroit" },
    { text: "grand magasin", category: "Endroit" },
    { text: "discothèque", category: "Endroit" },
    { text: "donjon", category: "Endroit" },
    { text: "caserne de pompiers", category: "Endroit" },
    { text: "jardin", category: "Endroit" },
    { text: "station-service", category: "Endroit" },
    { text: "parcours de golf", category: "Endroit" },
    { text: "hôpital", category: "Endroit" },
    { text: "maison", category: "Endroit" },
    { text: "bibliothèque", category: "Endroit" },
    { text: "phare", category: "Endroit" },
    { text: "manoir", category: "Endroit" },
    { text: "centre commercial", category: "Endroit" },
    { text: "cinéma", category: "Endroit" },
    { text: "musée", category: "Endroit" },
    { text: "immeuble de bureaux", category: "Endroit" },
    { text: "opéra", category: "Endroit" },
    { text: "verger", category: "Endroit" },
    { text: "palais", category: "Endroit" },
    { text: "animalerie", category: "Endroit" },
    { text: "commissariat de police", category: "Endroit" },
    { text: "bureau de poste", category: "Endroit" },
    { text: "prison", category: "Endroit" },
    { text: "pub", category: "Endroit" },
    { text: "restaurant", category: "Endroit" },
    { text: "safari", category: "Endroit" },
    { text: "scierie", category: "Endroit" },
    { text: "école", category: "Endroit" },
    { text: "gratte-ciel", category: "Endroit" },
    { text: "supermarché", category: "Endroit" },
    { text: "piscine", category: "Endroit" },
    { text: "temple", category: "Endroit" },
    { text: "gare", category: "Endroit" },
    { text: "théâtre", category: "Endroit" },
    { text: "parc d'attractions", category: "Endroit" },
    { text: "clinique vétérinaire", category: "Endroit" },
    { text: "zoo", category: "Endroit" },

    { text: "avion", category: "Transport" },
    { text: "vélo", category: "Transport" },
    { text: "autobus", category: "Transport" },
    { text: "bateau", category: "Transport" },
    { text: "traîneau à chiens", category: "Transport" },
    { text: "bus à impériale", category: "Transport" },
    { text: "F-16", category: "Transport" },
    { text: "chariot élévateur", category: "Transport" },
    { text: "Formule 1", category: "Transport" },
    { text: "voiturette de golf", category: "Transport" },
    { text: "hélicoptère", category: "Transport" },
    { text: "hoverboard", category: "Transport" },
    { text: "camion de crème glacée", category: "Transport" },
    { text: "jeep", category: "Transport" },
    { text: "monospace", category: "Transport" },
    { text: "paquebot", category: "Transport" },
    { text: "pousse-pousse", category: "Transport" },
    { text: "fusée", category: "Transport" },
    { text: "canot", category: "Transport" },
    { text: "voilier", category: "Transport" },
    { text: "scooter", category: "Transport" },
    { text: "navette", category: "Transport" },
    { text: "vaisseau spatial", category: "Transport" },
    { text: "voiture de sport", category: "Transport" },
    { text: "diligence", category: "Transport" },
    { text: "bateau à vapeur", category: "Transport" },
    { text: "sous-marin", category: "Transport" },
    { text: "tracteur", category: "Transport" },
    { text: "train", category: "Transport" },
    { text: "tramway", category: "Transport" },
    { text: "dépanneuse", category: "Transport" },
    { text: "tricycle", category: "Transport" },
    { text: "remorqueur", category: "Transport" },
    { text: "monocycle", category: "Transport" },
    { text: "yacht", category: "Transport" },
    { text: "zeppelin", category: "Transport" }, { text: "AC/DC", category: "Artistes de musique" },
    { text: "Adele", category: "Artistes de musique" },
    { text: "Beatles", category: "Artistes de musique" },
    { text: "Beyoncé", category: "Artistes de musique" },
    { text: "Billie Eilish", category: "Artistes de musique" },
    { text: "Bon Jovi", category: "Artistes de musique" },
    { text: "Bruno Mars", category: "Artistes de musique" },
    { text: "Childish Gambino", category: "Artistes de musique" },
    { text: "Coldplay", category: "Artistes de musique" },
    { text: "David Bowie", category: "Artistes de musique" },
    { text: "Daft Punk", category: "Artistes de musique" },
    { text: "Dr. Dre", category: "Artistes de musique" },
    { text: "Drake", category: "Artistes de musique" },
    { text: "Ed Sheeran", category: "Artistes de musique" },
    { text: "Elton John", category: "Artistes de musique" },
    { text: "Eminem", category: "Artistes de musique" },
    { text: "Guns N' Roses", category: "Artistes de musique" },
    { text: "Jay-Z", category: "Artistes de musique" },
    { text: "Justin Bieber", category: "Artistes de musique" },
    { text: "Justin Timberlake", category: "Artistes de musique" },
    { text: "Kanye West", category: "Artistes de musique" },
    { text: "Katy Perry", category: "Artistes de musique" },
    { text: "Lady Gaga", category: "Artistes de musique" },
    { text: "Led Zeppelin", category: "Artistes de musique" },
    { text: "Mariah Carey", category: "Artistes de musique" },
    { text: "Michael Jackson", category: "Artistes de musique" },
    { text: "Muse", category: "Artistes de musique" },
    { text: "Nicki Minaj", category: "Artistes de musique" },
    { text: "Nirvana", category: "Artistes de musique" },
    { text: "Pink Floyd", category: "Artistes de musique" },
    { text: "Pitbull", category: "Artistes de musique" },
    { text: "Prince", category: "Artistes de musique" },
    { text: "Queen", category: "Artistes de musique" },
    { text: "Rihanna", category: "Artistes de musique" },
    { text: "Skrillex", category: "Artistes de musique" },
    { text: "Snoop Dogg", category: "Artistes de musique" },
    { text: "Taylor Swift", category: "Artistes de musique" },
    { text: "The Black Eyed Peas", category: "Artistes de musique" },
    { text: "Tupac Shakur", category: "Artistes de musique" },
    { text: "U2", category: "Artistes de musique" },

    { text: "Dubstep", category: "Genre de Musique" },
    { text: "House", category: "Genre de Musique" },
    { text: "Rock", category: "Genre de Musique" },
    { text: "Hip Hop", category: "Genre de Musique" },
    { text: "Blues", category: "Genre de Musique" },
    { text: "Pop", category: "Genre de Musique" },
    { text: "Jazz", category: "Genre de Musique" },
    { text: "Classique", category: "Genre de Musique" },
    { text: "R&B", category: "Genre de Musique" },
    { text: "Heavy Metal", category: "Genre de Musique" },
    { text: "Punk", category: "Genre de Musique" },
    { text: "Country", category: "Genre de Musique" },
    { text: "Reggae", category: "Genre de Musique" },
    { text: "Musique d'ascenseur", category: "Genre de Musique" },
    { text: "Disco", category: "Genre de Musique" },
    { text: "Techno", category: "Genre de Musique" },
    { text: "J-Pop", category: "Genre de Musique" },
    { text: "Grunge", category: "Genre de Musique" },
    { text: "Rap", category: "Genre de Musique" },
    { text: "Swing", category: "Genre de Musique" },

    { text: "cornemuse", category: "instrument de musique" },
    { text: "basse", category: "instrument de musique" },
    { text: "juke-box", category: "instrument de musique" },
    { text: "trombone", category: "instrument de musique" },
    { text: "batterie", category: "instrument de musique" },
    { text: "ukulélé", category: "instrument de musique" },
    { text: "guitare électrique", category: "instrument de musique" },
    { text: "piano", category: "instrument de musique" },
    { text: "violon", category: "instrument de musique" },
    { text: "saxophone", category: "instrument de musique" },
    { text: "violoncelle", category: "instrument de musique" },
    { text: "flûte", category: "instrument de musique" },
    { text: "clarinette", category: "instrument de musique" },
    { text: "trompette", category: "instrument de musique" },
    { text: "harmonica", category: "instrument de musique" },
    { text: "harpe", category: "instrument de musique" },
    { text: "banjo", category: "instrument de musique" },
    { text: "castagnettes", category: "instrument de musique" },
    { text: "kazoo", category: "instrument de musique" },
    { text: "cloche de vache", category: "instrument de musique" },
    { text: "cymbale", category: "instrument de musique" },
    { text: "gong", category: "instrument de musique" },
    { text: "maracas", category: "instrument de musique" },
    { text: "marimba", category: "instrument de musique" },
    { text: "tambourin", category: "instrument de musique" },
    { text: "triangle", category: "instrument de musique" },
    { text: "planche à laver", category: "instrument de musique" },
    { text: "xylophone", category: "instrument de musique" },
    { text: "accordéon", category: "instrument de musique" },
    { text: "cor", category: "instrument de musique" },
    { text: "clairon", category: "instrument de musique" },
    { text: "didgeridoo", category: "instrument de musique" },
    { text: "hautbois", category: "instrument de musique" },
    { text: "ocarina", category: "instrument de musique" },
    { text: "piccolo", category: "instrument de musique" },
    { text: "sifflet", category: "instrument de musique" },
    { text: "tuba", category: "instrument de musique" },
    { text: "sitar", category: "instrument de musique" },
    { text: "luth", category: "instrument de musique" },

    { text: "génie", category: "Mythologie" },
    { text: "minotaure", category: "Mythologie" },
    { text: "tapis volant", category: "Mythologie" },
    { text: "griffon", category: "Mythologie" },
    { text: "Bigfoot", category: "Mythologie" },
    { text: "chimère", category: "Mythologie" },
    { text: "cyclope", category: "Mythologie" },
    { text: "centaure", category: "Mythologie" },
    { text: "sirène", category: "Mythologie" },
    { text: "Pégase", category: "Mythologie" },
    { text: "phénix", category: "Mythologie" },
    { text: "licorne", category: "Mythologie" },
    { text: "vampire", category: "Mythologie" },
    { text: "dragon", category: "Mythologie" },
    { text: "dryade", category: "Mythologie" },
    { text: "fantôme", category: "Mythologie" },
    { text: "Méduse", category: "Mythologie" },
    { text: "manticore", category: "Mythologie" },
    { text: "satyre", category: "Mythologie" },
    { text: "sphinx", category: "Mythologie" },
    { text: "loup-garou", category: "Mythologie" },
    { text: "zombie", category: "Mythologie" },
    { text: "momie", category: "Mythologie" },
    { text: "golem", category: "Mythologie" },
    { text: "guerrière amazone", category: "Mythologie" },
    { text: "peuple lézard", category: "Mythologie" },
    { text: "basilic", category: "Mythologie" },
    { text: "gobelin", category: "Mythologie" },
    { text: "fée", category: "Mythologie" },
    { text: "goule", category: "Mythologie" },
    { text: "lutin", category: "Mythologie" },
    { text: "troll", category: "Mythologie" },
    { text: "ogre", category: "Mythologie" },
    { text: "nymphe", category: "Mythologie" },
    { text: "géant", category: "Mythologie" },
    { text: "elfe", category: "Mythologie" },

    { text: "Angelina Jolie", category: "Célébrité" },
    { text: "Bob Dylan", category: "Célébrité" },
    { text: "Brad Pitt", category: "Célébrité" },
    { text: "Bruce Lee", category: "Célébrité" },
    { text: "Geronimo", category: "Célébrité" },
    { text: "Green Day", category: "Célébrité" },
    { text: "Kate Moss", category: "Célébrité" },
    { text: "Lady Gaga", category: "Célébrité" },
    { text: "Lil Wayne", category: "Célébrité" },
    { text: "Ludacris", category: "Célébrité" },
    { text: "MC Hammer", category: "Célébrité" },
    { text: "Tom Hanks", category: "Célébrité" },
    { text: "Beckham", category: "Célébrité" },
    { text: "Colbert", category: "Célébrité" },
    { text: "Jay Leno", category: "Célébrité" },
    { text: "Lincoln", category: "Célébrité" },
    { text: "Picasso", category: "Célébrité" },
    { text: "Rihanna", category: "Célébrité" },
    { text: "Vincent van Gogh", category: "Célébrité" },
    { text: "Donald Trump", category: "Célébrité" },

    { text: "artiste", category: "Profession" },
    { text: "assassin", category: "Profession" },
    { text: "coiffeur", category: "Profession" },
    { text: "boucher", category: "Profession" },
    { text: "capitaine", category: "Profession" },
    { text: "caissier", category: "Profession" },
    { text: "chef", category: "Profession" },
    { text: "clown", category: "Profession" },
    { text: "cuisinier", category: "Profession" },
    { text: "cow-boy", category: "Profession" },
    { text: "cow-girl", category: "Profession" },
    { text: "dentiste", category: "Profession" },
    { text: "DJ", category: "Profession" },
    { text: "docteur", category: "Profession" },
    { text: "batteur", category: "Profession" },
    { text: "fermier", category: "Profession" },
    { text: "pompier", category: "Profession" },
    { text: "pirate informatique", category: "Profession" },
    { text: "gangster", category: "Profession" },
    { text: "jardinier", category: "Profession" },
    { text: "gymnaste", category: "Profession" },
    { text: "concierge", category: "Profession" },
    { text: "avocat", category: "Profession" },
    { text: "magicien", category: "Profession" },
    { text: "facteur", category: "Profession" },
    { text: "laitier", category: "Profession" },
    { text: "réalisateur de films", category: "Profession" },
    { text: "chanteur d'opéra", category: "Profession" },
    { text: "peintre", category: "Profession" },
    { text: "pilote", category: "Profession" },
    { text: "plombier", category: "Profession" },
    { text: "policier", category: "Profession" },
    { text: "homme de piscine", category: "Profession" },
    { text: "prêtre", category: "Profession" },
    { text: "princesse", category: "Profession" },
    { text: "shérif", category: "Profession" },
    { text: "soldat", category: "Profession" },
    { text: "chirurgien", category: "Profession" },
    { text: "enseignant", category: "Profession" },
    { text: "serveur", category: "Profession" },
    { text: "guerrier", category: "Profession" },
    { text: "laveur de vitres", category: "Profession" },
    { text: "lutteur", category: "Profession" },

    { text: "tamanoir", category: "Animal" },
    { text: "alpaga", category: "Animal" },
    { text: "fourmi", category: "Animal" },
    { text: "tatou", category: "Animal" },
    { text: "babouin", category: "Animal" },
    { text: "blaireau", category: "Animal" },
    { text: "chauve-souris", category: "Animal" },
    { text: "ours", category: "Animal" },
    { text: "castor", category: "Animal" },
    { text: "abeille", category: "Animal" },
    { text: "oiseau", category: "Animal" },
    { text: "buffle", category: "Animal" },
    { text: "taureau", category: "Animal" },
    { text: "veau", category: "Animal" },
    { text: "chameau", category: "Animal" },
    { text: "chat", category: "Animal" },
    { text: "chenille", category: "Animal" },
    { text: "poisson-chat", category: "Animal" },
    { text: "caméléon", category: "Animal" },
    { text: "guépard", category: "Animal" },
    { text: "poulet", category: "Animal" },
    { text: "chimpanzé", category: "Animal" },
    { text: "chihuahua", category: "Animal" },
    { text: "cigale", category: "Animal" },
    { text: "cafard", category: "Animal" },
    { text: "vache", category: "Animal" },
    { text: "grue", category: "Animal" },
    { text: "crabe", category: "Animal" },
    { text: "grillon", category: "Animal" },
    { text: "crocodile", category: "Animal" },
    { text: "cerf", category: "Animal" },
    { text: "dinosaure", category: "Animal" },
    { text: "chien", category: "Animal" },
    { text: "dauphin", category: "Animal" },
    { text: "âne", category: "Animal" },
    { text: "canard", category: "Animal" },
    { text: "libellule", category: "Animale", category: "Animal" },
    { text: "moustique", category: "Animal" },
    { text: "élan", category: "Animal" },
    { text: "souris", category: "Animal" },
    { text: "narval", category: "Animal" },
    { text: "poulpe", category: "Animal" },
    { text: "autruche", category: "Animal" },
    { text: "loutre", category: "Animal" },
    { text: "hibou", category: "Animal" },
    { text: "huître", category: "Animal" },
    { text: "panda", category: "Animal" },
    { text: "pangolin", category: "Animal" },
    { text: "perroquet", category: "Animal" },
    { text: "panthère", category: "Animal" },
    { text: "paon", category: "Animal" },
    { text: "pélican", category: "Animal" },
    { text: "pingouin", category: "Animal" },
    { text: "cochon", category: "Animal" },
    { text: "pigeon", category: "Animal" },
    { text: "pitbull", category: "Animal" },
    { text: "ornithorynque", category: "Animal" },
    { text: "porc-épic", category: "Animal" },
    { text: "caniche", category: "Animal" },
    { text: "chiot", category: "Animal" },
    { text: "lapin", category: "Animal" },
    { text: "raton laveur", category: "Animal" },
    { text: "rat", category: "Animal" },
    { text: "renne", category: "Animal" },
    { text: "reptile", category: "Animal" },
    { text: "rhinocéros", category: "Animal" },
    { text: "coq", category: "Animal" },
    { text: "scorpion", category: "Animal" },
    { text: "mouette", category: "Animal" },
    { text: "hippocampe", category: "Animal" },
    { text: "phoque", category: "Animal" },
    { text: "requin", category: "Animal" },
    { text: "mouton", category: "Animal" },
    { text: "crevette", category: "Animal" },
    { text: "moufette", category: "Animal" },
    { text: "escargot", category: "Animal" },
    { text: "serpent", category: "Animal" },
    { text: "araignée", category: "Animal" },
    { text: "calmar", category: "Animal" },
    { text: "écureuil", category: "Animal" },
    { text: "étoile de mer", category: "Animal" },
    { text: "cigogne", category: "Animal" },
    { text: "cygne", category: "Animal" },
    { text: "têtard", category: "Animal" },
    { text: "tigre", category: "Animal" },
    { text: "crapaud", category: "Animal" },
    { text: "poisson tropical", category: "Animal" },
    { text: "thon", category: "Animal" },
    { text: "dindon", category: "Animal" },
    { text: "tortue", category: "Animal" },
    { text: "varan", category: "Animal" },
    { text: "vautour", category: "Animal" },
    { text: "morse", category: "Animal" },
    { text: "baleine", category: "Animal" },
    { text: "loup", category: "Animal" },
    { text: "wombat", category: "Animal" },
    { text: "ver de terre", category: "Animal" },
    { text: "zèbre", category: "Animal" },
    { text: "Bacon", category: "Nourriture" },
    { text: "Baguette", category: "Nourriture" },
    { text: "Barbecue", category: "Nourriture" },
    { text: "Haricots", category: "Nourriture" },
    { text: "Bière", category: "Nourriture" },
    { text: "Burrito", category: "Nourriture" },
    { text: "Gâteau", category: "Nourriture" },
    { text: "Céréales", category: "Nourriture" },
    { text: "Champagne", category: "Nourriture" },
    { text: "Fromage", category: "Nourriture" },
    { text: "Ailes de poulet", category: "Nourriture" },
    { text: "Café", category: "Nourriture" },
    { text: "Corn Dog", category: "Nourriture" },
    { text: "Croissant", category: "Nourriture" },
    { text: "Petit gâteau", category: "Nourriture" },
    { text: "Rouleau de printemps", category: "Nourriture" },
    { text: "Espresso", category: "Nourriture" },
    { text: "Fast Food", category: "Nourriture" },
    { text: "Fish and Chips", category: "Nourriture" },
    { text: "Glaçage", category: "Nourriture" },
    { text: "Hamburger", category: "Nourriture" },
    { text: "Os à jambon", category: "Nourriture" },
    { text: "Sandwich au jambon", category: "Nourriture" },
    { text: "Sauce piquante", category: "Nourriture" },
    { text: "Nourriture malsaine", category: "Nourriture" },
    { text: "Kebab", category: "Nourriture" },
    { text: "Ketchup", category: "Nourriture" },
    { text: "Lasagne", category: "Nourriture" },
    { text: "Limonade", category: "Nourriture" },
    { text: "Macaroni", category: "Nourriture" },
    { text: "Martini", category: "Nourriture" },
    { text: "Purée de pommes de terre", category: "Nourriture" },
    { text: "Boulettes de viande", category: "Nourriture" },
    { text: "Lait", category: "Nourriture" },
    { text: "Champignon", category: "Nourriture" },
    { text: "Moutarde", category: "Nourriture" },
    { text: "Nouilles", category: "Nourriture" },
    { text: "Porridge", category: "Nourriture" },
    { text: "Crêpe", category: "Nourriture" },
    { text: "Pâtes", category: "Nourriture" },
    { text: "Tarte", category: "Nourriture" },
    { text: "Pizza", category: "Nourriture" },
    { text: "Popcorn", category: "Nourriture" },
    { text: "Bretzel", category: "Nourriture" },
    { text: "Citrouille", category: "Nourriture" },
    { text: "Salade", category: "Nourriture" },
    { text: "Sandwich", category: "Nourriture" },
    { text: "Saucisse", category: "Nourriture" },
    { text: "Fruits de mer", category: "Nourriture" },
    { text: "Smoothie", category: "Nourriture" },
    { text: "Barbe à papa", category: "Nourriture" },
    { text: "Sauce soja", category: "Nourriture" },
    { text: "Sushi", category: "Nourriture" },
    { text: "Thé", category: "Nourriture" },
    { text: "Tequila", category: "Nourriture" },
    { text: "Gaufres", category: "Nourriture" },
    { text: "Whisky", category: "Nourriture" },
    { text: "Horreur", category: "Genres de films" },
    { text: "Action", category: "Genres de films" },
    { text: "Thriller", category: "Genres de films" },
    { text: "Science-Fiction", category: "Genres de films" },
    { text: "Comédie romantique", category: "Genres de films" },
    { text: "Western", category: "Genres de films" },
    { text: "Comédie", category: "Genres de films" },
    { text: "Gangster", category: "Genres de films" },
    { text: "Slapstick", category: "Genres de films" },
    { text: "Guerre", category: "Genres de films" },
    { text: "Documentaire", category: "Genres de films" },
    { text: "Mockumentaire", category: "Genres de films" },
    { text: "Musical", category: "Genres de films" },
    { text: "Animation", category: "Genres de films" },
    { text: "Catastrophes", category: "Genres de films" },
    { text: "Zombies", category: "Genres de films" },
    { text: "Sport", category: "Genres de films" },
    { text: "Orange mécanique", category: "Film" },
    { text: "Armageddon", category: "Film" },
    { text: "Alien", category: "Film" },
    { text: "Austin Powers", category: "Film" },
    { text: "Avengers", category: "Film" },
    { text: "Retour vers le futur", category: "Film" },
    { text: "Braveheart", category: "Film" },
    { text: "Beetlejuice", category: "Film" },
    { text: "Piège de cristal", category: "Film" },
    { text: "E.T.", category: "Film" },
    { text: "Fargo", category: "Film" },
    { text: "Le Monde de Nemo", category: "Film" },
    { text: "Forrest Gump", category: "Film" },
    { text: "La Reine des neiges", category: "Film" },
    { text: "Gladiator", category: "Film" },
    { text: "GoldenEye", category: "Film" },
    { text: "Autant en emporte le vent", category: "Film" },
    { text: "Un jour sans fin", category: "Film" },
    { text: "Maman, j'ai raté l'avion", category: "Film" },
    { text: "Inception", category: "Film" },
    { text: "Indiana Jones", category: "Film" },
    { text: "Inglourious Basterds", category: "Film" },
    { text: "Les Dents de la mer", category: "Film" },
    { text: "Jurassic Park", category: "Film" },
    { text: "King Kong", category: "Film" },
    { text: "Le Roi Lion", category: "Film" },
    { text: "Mary Poppins", category: "Film" },
    { text: "Minority Report", category: "Film" },
    { text: "Mission: Impossible", category: "Film" },
    { text: "Monty Python : Sacré Graal !", category: "Film" },
    { text: "La Princesse promise", category: "Film" },
    { text: "Pulp Fiction", category: "Film" },
    { text: "Rocky Horror Picture Show", category: "Film" },
    { text: "Rocky", category: "Film" },
    { text: "Il faut sauver le soldat Ryan", category: "Film" },
    { text: "Scarface", category: "Film" },
    { text: "Shrek", category: "Film" },
    { text: "Star Wars", category: "Film" },
    { text: "Terminator", category: "Film" },
    { text: "Le Bon, la Brute et le Truand", category: "Film" },
    { text: "La Ligne verte", category: "Film" },
    { text: "Le Seigneur des anneaux", category: "Film" },
    { text: "Matrix", category: "Film" },
    { text: "The Social Network", category: "Film" },
    { text: "Le Magicien d'Oz", category: "Film" },
    { text: "Titanic", category: "Film" },
    { text: "Toy Story", category: "Film" },
    { text: "West Side Story", category: "Film" },
    { text: "Wonder Woman", category: "Film" },
    { text: "X-Men", category: "Film" },
    { text: "RoboCop", category: "Film" },
    { text: "Bonbon aigre", category: "Snack" },
    { text: "Twinkie", category: "Snack" },
    { text: "Sucette", category: "Snack" },
    { text: "Esquimau", category: "Snack" },
    { text: "Skittles", category: "Snack" },
    { text: "Brownie", category: "Snack" },
    { text: "Cookie", category: "Snack" },
    { text: "Doritos", category: "Snack" },
    { text: "Glace", category: "Snack" },
    { text: "Les Pyramides", category: "Sites célèbres" },
    { text: "Statue du Christ Rédempteur", category: "Sites célèbres" },
    { text: "La Grande Muraille de Chine", category: "Sites célèbres" },
    { text: "Tour de Pise", category: "Sites célèbres" },
    { text: "Empire State Building", category: "Sites célèbres" },
    { text: "Colisée", category: "Sites célèbres" },
    { text: "La Tour Eiffel", category: "Sites célèbres" },
    { text: "Statue de la Liberté", category: "Sites célèbres" },
    { text: "Le Sphinx", category: "Sites célèbres" },
    { text: "La Petite Sirène", category: "Sites célèbres" },
    { text: "Le Taj Mahal", category: "Sites célèbres" },
    { text: "Big Ben", category: "Sites célèbres" },
    { text: "Loch Ness", category: "Sites célèbres" },
    { text: "Porte de Brandebourg", category: "Sites célèbres" },
    { text: "Acropole", category: "Sites célèbres" },
    { text: "Stonehenge", category: "Sites célèbres" },
    { text: "Île de Pâques", category: "Sites célèbres" },
    { text: "Capitole", category: "Sites célèbres" },
    { text: "Chutes du Niagara", category: "Sites célèbres" },
    { text: "Mont Rush more", category: "Sites célèbres" },
    { text: "Grand Canyon", category: "Sites célèbres" },
    { text: "Fontaine de Trevi", category: "Sites célèbres" },
    { text: "Opéra de Sydney", category: "Sites célèbres" },
    { text: "Pont du Golden Gate", category: "Sites célèbres" },
    { text: "Cité interdite", category: "Sites célèbres" },
    { text: "Le Kremlin", category: "Sites célèbres" },
    { text: "Le Louvre", category: "Sites célèbres" },
    { text: "L'enseigne Hollywood", category: "Sites célèbres" },
    { text: "Cendrillon", category: "Conte de fées" },
    { text: "Les Trois Petits Cochons", category: "Conte de fées" },
    { text: "Le Vilain Petit Canard", category: "Conte de fées" },
    { text: "Le Soldat de Plomb", category: "Conte de fées" },
    { text: "La Lampe merveilleuse", category: "Conte de fées" },
    { text: "La Princesse au petit pois", category: "Conte de fées" },
    { text: "Poucette", category: "Conte de fées" },
    { text: "La Petite Sirène", category: "Conte de fées" },
    { text: "Boucles d'Or et les Trois Ours", category: "Conte de fées" },
    { text: "La Belle au bois dormant", category: "Conte de fées" },
    { text: "Blanche-Neige", category: "Conte de fées" },
    { text: "Raiponce", category: "Conte de fées" },
    { text: "Le Prince Grenouille", category: "Conte de fées" },
    { text: "Hansel et Gretel", category: "Conte de fées" },
    { text: "Le Poisson d'or", category: "Conte de fées" },
    { text: "Rumpelstilzchen", category: "Conte de fées" },
    { text: "L'Oie d'or", category: "Conte de fées" },
    { text: "Le Chat Botté", category: "Conte de fées" },
    { text: "Aladdin", category: "Conte de fées" },
    { text: "La Belle et la Bête", category: "Conte de fées" },
    { text: "Ali Baba et les Quarante Voleurs", category: "Conte de fées" },
    { text: "Sinbad le marin", category: "Conte de fées" },
    { text: "Le Pêcheur et le Démon", category: "Conte de fées" }
];