words_de = [
    { text: 'Oma', category: 'Familie' },
    { text: 'opa', category: 'Familie' },
    { text: 'Ehemann', category: 'Familie' },
    { text: 'Eltern', category: 'Familie' },
    { text: 'Ehefrau', category: 'Familie' },
    { text: 'Onkel', category: 'Familie' },
    { text: 'Tante', category: 'Familie' },
    { text: 'Vater', category: 'Familie' },
    { text: 'Mutter', category: 'Familie' },
    { text: 'Stiefschwester', category: 'Familie' },
    { text: 'Stiefbruder', category: 'Familie' },
    { text: 'Stiefvater', category: 'Familie' },
    { text: 'Stiefmutter', category: 'Familie' },
    { text: 'Patenonkel', category: 'Familie' },
    { text: 'Patentante', category: 'Familie' },
    { text: 'Schwiegermutter', category: 'Familie' },
    { text: 'Schwiegervater', category: 'Familie' },
    { text: 'Kinder', category: 'Familie' },
    { text: 'Bruder', category: 'Familie' },
    { text: 'Schwester', category: 'Familie' },
    { text: 'Cousin', category: 'Familie' },
    { text: 'Großmutter', category: 'Familie' },
    { text: 'Enkel', category: 'Familie' },
    { text: 'Nichte', category: 'Familie' },
    { text: 'Neffe', category: 'Familie' },

	{ text: 'Neujahr', category: 'Festlichkeit' },
    { text: 'Hochzeit', category: 'Festlichkeit' },
    { text: 'Geburtstag', category: 'Festlichkeit' },
    { text: 'Halloween', category: 'Festlichkeit' },
    { text: 'oktoberfest', category: 'Festlichkeit' },
    { text: 'weihnachten', category: 'Festlichkeit' },
    { text: 'Silvester', category: 'Festlichkeit' },
    { text: 'Murmeltiertag', category: 'Festlichkeit' },
    { text: 'Valentine`s Day', category: 'Festlichkeit' },
    { text: 'St. Patrick`s Day', category: 'Festlichkeit' },
    { text: 'Pfingsten', category: 'Festlichkeit' },
    { text: 'Ostern', category: 'Festlichkeit' },
    { text: 'Ramadan', category: 'Festlichkeit' },
    { text: 'Muttertag', category: 'Festlichkeit' },
    { text: 'Independence Day', category: 'Festlichkeit' },
    { text: 'Black Friday', category: 'Festlichkeit' },
    { text: 'Thanksgiving', category: 'Festlichkeit' },
    { text: 'Bundestagswahl', category: 'Festlichkeit' },
    { text: 'Abschlussfeier', category: 'Festlichkeit' },


    { text: 'Stuhl', category: 'Möbel' },
    { text: 'Barhocker', category: 'Möbel' },
    { text: 'Bücherregal', category: 'Möbel' },
    { text: 'Wasserbett', category: 'Möbel' },
    { text: 'badewanne', category: 'Möbel' },
    { text: 'Etagenbett', category: 'Möbel' },
    { text: 'Schrank', category: 'Möbel' },
    { text: 'Kommode', category: 'Möbel' },
    { text: 'Bett', category: 'Möbel' },

    { text: 'Kettensäge', category: 'Werkzeug' },
    { text: 'Schere', category: 'Werkzeug' },
    { text: 'Pinzette', category: 'Werkzeug' },
    { text: 'Zirkel', category: 'Werkzeug' },
    { text: 'Brechstange', category: 'Werkzeug' },
    { text: 'Kehrschaufel', category: 'Werkzeug' },
    { text: 'Hefter', category: 'Werkzeug' },

    { text: 'Lippenstift', category: 'Toilettenartikel' },
    { text: 'Parfüm', category: 'Toilettenartikel' },
    { text: 'Shampoo', category: 'Toilettenartikel' },
    { text: 'Nagelfeile', category: 'Toilettenartikel' },
    { text: 'Sonnencreme', category: 'Toilettenartikel' },
    { text: 'Haarfärbemittel', category: 'Toilettenartikel' },
    { text: 'Haargel', category: 'Toilettenartikel' }, 
    { text: 'Wimperntusche', category: 'Toilettenartikel' },

    { text: 'Computer', category: 'computing' },
    { text: 'facebook', category: 'computing' },
    { text: 'firewall', category: 'computing' },
    { text: 'Tastatur', category: 'computing' },
    { text: 'Passwort', category: 'computing' },
    { text: 'hashtag', category: 'computing' },
    { text: 'macbook', category: 'computing' },
    { text: 'twitter', category: 'computing' },
	{ text: 'reddit', category: 'computing' },
	{ text: 'snapchat', category: 'computing' },
	{ text: 'instagram', category: 'computing' },


	{ category: 'Waffe', text: 'Kriegsaxt' },
	{ category: 'Waffe', text: 'Bayonett' },
	{ category: 'Waffe', text: 'Panzerfaust' },
	{ category: 'Waffe', text: 'Kanone' },
	{ category: 'Waffe', text: 'Katapult' },
	{ category: 'Waffe', text: 'Armbrust' },
	{ category: 'Waffe', text: 'Dynamit' },
	{ category: 'Waffe', text: 'Pistole' },
	{ category: 'Waffe', text: 'Rakete' },
	{ category: 'Waffe', text: 'Shotgun' },
	{ category: 'Waffe', text: 'Schwert' }, 
	{ category: 'Waffe', text: 'Kitana' },
	{ category: 'Waffe', text: 'Torpedo' }, 
	{ category: 'Waffe', text: 'Warhammer'},

    { text: 'Augenklappe', category: 'Accessoires' },
    { text: 'Stirnband', category: 'Accessoires' },
    { text: 'Knieschoner', category: 'Accessoires' },
    { text: 'Halskette', category: 'Accessoires' },
    { text: 'nosering', category: 'Accessoires' },
    { text: 'partyhat', category: 'Accessoires' },
    { text: 'Schnürsenkel', category: 'Accessoires' },
    { text: 'Regenschirm', category: 'Accessoires' },
    { text: 'Halstuch', category: 'Accessoires' },
    { text: 'ohrring', category: 'Accessoires' },
    { text: 'Haargummi', category: 'Accessoires' },
    { text: 'Handtasche', category: 'Accessoires' },
	{ category: 'Accessoires', text: 'Taschentuch' },

    { category: 'Kleidung', text: 'Keuschheitsgürtel' },
    { category: 'Kleidung', text: 'Tophat' },
    { category: 'Kleidung', text: 'Hosenanzug' },
    { category: 'Kleidung', text: 'Halstuch' },
    { category: 'Kleidung', text: 'Gürtel' },
    { category: 'Kleidung', text: 'Bikini' },
    { category: 'Kleidung', text: 'Stiefel' },
    { category: 'Kleidung', text: 'Fliege' },
	{ category: 'Kleidung', text: 'Tophat' },
	{ category: 'Kleidung', text: 'Cowboyhut' },
    { category: 'Kleidung', text: 'Mütze' }, 
    { category: 'Kleidung', text: 'Mantel' },
    { category: 'Kleidung', text: 'Kleid' },
    { category: 'Kleidung', text: 'Ohrenschützer' },
    { category: 'Kleidung', text: 'Augenklappe' },
    { category: 'Kleidung', text: 'Brille' },
    { category: 'Kleidung', text: 'Handschuhe' },
    { category: 'Kleidung', text: 'Haargummi' }, 
	{ category: 'Kleidung', text: 'Hoodie' },
    { category: 'Kleidung', text: 'Hut' },
    { category: 'Kleidung', text: 'Stirnband' },
    { category: 'Kleidung', text: 'Jacke' },
    { category: 'Kleidung', text: 'Jeans' },
    { category: 'Kleidung', text: 'Knieschoner' },
    { category: 'Kleidung', text: 'Fäustlinge' },
    { category: 'Kleidung', text: 'Halskette' },
    { category: 'Kleidung', text: 'Latzhose' }, 
    { category: 'Kleidung', text: 'Pyjama' },
    { category: 'Kleidung', text: 'Partyhut' },
    { category: 'Kleidung', text: 'Regenmantel' },
    { category: 'Kleidung', text: 'Sandalen' },
    { category: 'Kleidung', text: 'Schal' },
    { category: 'Kleidung', text: 'Hemd' }, 
    { category: 'Kleidung', text: 'Schuhe' },
    { category: 'Kleidung', text: 'Rock' },
    { category: 'Kleidung', text: 'Hausschuhe' },
    { category: 'Kleidung', text: 'Turnschuhe' },
    { category: 'Kleidung', text: 'Socken' },
    { category: 'Kleidung', text: 'Sombrero' },
    { category: 'Kleidung', text: 'Strümpfe' },
    { category: 'Kleidung', text: 'Anzug' },
    { category: 'Kleidung', text: 'Pullover' },
    { category: 'Kleidung', text: 'Sweatshirt' },
    { category: 'Kleidung', text: 'Schwimmanzug' },
    { category: 'Kleidung', text: 't-shirt' }, 
    { category: 'Kleidung', text: 'Krawatte' }, 
    { category: 'Kleidung', text: 'Hose' },
    { category: 'Kleidung', text: 'Unterhosen' },

    { text: 'Krücken', category: 'Medizin' },
    { text: 'Schuppen', category: 'Medizin' },
    { text: 'Zahnersatz', category: 'Medizin' },
    { text: 'Erste Hilfe', category: 'Medizin' },
    { text: 'Kopfschmerzen', category: 'Medizin' },
    { text: 'Krankenhaus', category: 'Medizin' },
    { text: 'Schlaflosigkeit', category: 'Medizin' },
    { text: 'Medizin', category: 'Medizin' },
    { text: 'Papierschnitt', category: 'Medizin' },
    { text: 'Seekrankheit', category: 'Medizin' },
    { text: 'Sonnenbrand', category: 'Medizin' },
    { text: 'Impfung', category: 'Medizin' },
    { text: 'Vitamin', category: 'Medizin' },

    { text: 'hongkong', category: 'Geografie' },
    { text: 'schottland', category: 'Geografie' },
    { text: 'amerika', category: 'Geografie' },
    { text: 'atlanta', category: 'Geografie' },
    { text: 'bahamas', category: 'Geografie' },
    { text: 'england', category: 'Geografie' },
    { text: 'finland', category: 'Geografie' },
    { text: 'florida', category: 'Geografie' },
    { text: 'deutschland', category: 'Geografie' },
    { text: 'holland', category: 'Geografie' },
    { text: 'ireland', category: 'Geografie' },
    { text: 'jamaika', category: 'Geografie' },
    { text: 'new-york', category: 'Geografie' },
    { text: 'orlando', category: 'Geografie' },
	{ text: 'Berlin', category: 'Geografie' },
	{ text: 'Stuttgart', category: 'Geografie' },
	{ text: 'Frankreich', category: 'Geografie' },
	{ text: 'Italien', category: 'Geografie' },



    { text: 'kohl', category: 'Pflanze' },
    { text: 'Dattelpflaume', category: 'Pflanze' },
    { text: 'Gurke', category: 'Pflanze' },
    { text: 'Zucchini', category: 'Pflanze' },
    { text: 'Wassermelone', category: 'Pflanze' },
    { text: 'Mango', category: 'Pflanze' },
    { text: 'Zitrone', category: 'Pflanze' },
    { text: 'Limette', category: 'Pflanze' },
    { text: 'Kartoffel', category: 'Pflanze' },
    { text: 'Kaktus', category: 'Pflanze' },
    { text: 'Tomate', category: 'Pflanze' },
    { text: 'Aubergine', category: 'Pflanze' },
    { text: 'Palme', category: 'Pflanze' },
    { text: 'Tannenzapfen', category: 'Pflanze' },
    { text: 'Kiefernbaum', category: 'Pflanze' },
    { text: 'Primrose', category: 'Pflanze' },
    { text: 'Eiche', category: 'Pflanze' },
    { text: 'Seegras', category: 'Pflanze' },
    { text: 'Bambus', category: 'Pflanze' },
    { text: 'Kraut', category: 'Pflanze' },
    { text: 'Persimmon', category: 'Pflanze' },
    { text: 'Gurke', category: 'Pflanze' },
    { text: 'Zucchini', category: 'Pflanze' },
    { text: 'Wassermelone', category: 'Pflanze' },
    { text: 'Mango', category: 'Pflanze' },
    { text: 'Zitrone', category: 'Pflanze' },
    { text: 'Limette', category: 'Pflanze' },
    { text: 'Kartoffel', category: 'Pflanze' },
    { text: 'Kaktus', category: 'Pflanze' },
    { text: 'Tomate', category: 'Pflanze' },
    { text: 'Aubergine', category: 'Pflanze' },
    { text: 'Palme', category: 'Pflanze' },
    { text: 'Tannenzapfen', category: 'Pflanze' },
    { text: 'Pinienbaum', category: 'Pflanze' },
    { text: 'Primrose', category: 'Pflanze' },
    { text: 'Eiche', category: 'Pflanze' },
    { text: 'Seegras', category: 'Pflanze' },
    { text: 'Bamboo', category: 'Pflanze' },
    { text: 'Karotte', category: 'Pflanze' },
    { text: 'Sellerie', category: 'Pflanze' },
    { text: 'Kirsche', category: 'Pflanze' },
    { text: 'Knoblauch', category: 'Pflanze' },
    { text: 'Trauben', category: 'Pflanze' },
    { text: 'Koriander', category: 'Pflanze' },
    { text: 'Banane', category: 'Pflanze' },
    { text: 'Brokkoli', category: 'Pflanze' },
    { text: 'Avocado', category: 'Pflanze' },
    { text: 'Kokosnuss', category: 'Pflanze' },
    { text: 'Pfirsiche', category: 'Pflanze' },
    { text: 'Spinat', category: 'Pflanze' },
    { text: 'Ananas', category: 'Pflanze' },
    { text: 'Weizen', category: 'Pflanze' },
    { text: 'Orange', category: 'Pflanze' },

    { text: 'Wirbelsäule', category: 'Anatomie' },
    { text: 'Stirn', category: 'Anatomie' },
    { text: 'Schnurrbart', category: 'Anatomie' },
    { text: 'Nasenhaar', category: 'Anatomie' },
    { text: 'Schulter', category: 'Anatomie' },
    { text: 'Skelett', category: 'Anatomie' },
    { text: 'Tentakel', category: 'Anatomie' },
    { text: 'Schnurrhaare', category: 'Anatomie' },
    { text: 'Augapfel', category: 'Anatomie' },
    { text: 'Augenbraue', category: 'Anatomie' },
    { text: 'Wimper', category: 'Anatomie' },
    { text: 'Kniescheibe', category: 'Anatomie' },
    { text: 'knuckle', category: 'Anatomie' },
    { text: 'Bauch', category: 'Anatomie' },
    { text: 'unibrow', category: 'Anatomie' },

    { category: 'Ort', text: 'Flughafen' },
    { category: 'Ort', text: 'Mehrfamilienhaus' },
    { category: 'Ort', text: 'Bank' },
    { category: 'Ort', text: 'Friseurladen' },
	{ category: 'Ort', text: 'Bar' },
    { category: 'Ort', text: 'Scheune' },
	{ category: 'Ort', text: 'Strand' },
    { category: 'Ort', text: 'Buchhandlung' },
    { category: 'Ort', text: 'Bowlingbahn' },
    { category: 'Ort', text: 'Bushaltestelle' },
	{ category: 'Ort', text: 'Casino' },
    { category: 'Ort', text: 'Kathedrale' },
	{ category: 'Ort', text: 'Schloss' },
	{ category: 'Ort', text: 'Friedhof' },
	{ category: 'Ort', text: 'Kirche' },
	{ category: 'Ort', text: 'Zirkus' },
    { category: 'Ort', text: 'Convenience Store' },
    { category: 'Ort', text: 'Gerichtsgebäude' }, 
	{ category: 'Ort', text: 'Wüste' },
    { category: 'Ort', text: 'Kaufhaus' },
    { category: 'Ort', text: 'Disco' },
	{ category: 'Ort', text: 'Dungeon' }, 
    { category: 'Ort', text: 'Feuerwache' },
	{ category: 'Ort', text: 'Garten' },
    { category: 'Ort', text: 'Tankstelle' },
	{ category: 'Ort', text: 'Golfplatz' },
    { category: 'Ort', text: 'Krankenhaus' },
    { category: 'Ort', text: 'Haus' },
	{ category: 'Ort', text: 'Bibliothek' },
    { category: 'Ort', text: 'Leuchtturm' },
	{ category: 'Ort', text: 'Herrenhaus' },
    { category: 'Ort', text: 'Einkaufszentrum' },
    { category: 'Ort', text: 'Kino' },
    { category: 'Ort', text: 'Museum' },
    { category: 'Ort', text: 'Bürogebäude' },
    { category: 'Ort', text: 'Opernhaus' },
	{ category: 'Ort', text: 'Obstgarten' },
    { category: 'Ort', text: 'Palast' },
	{ category: 'Ort', text: 'Tierhandlung' },
    { category: 'Ort', text: 'Polizeistation' },
    { category: 'Ort', text: 'Postamt' },
	{ category: 'Ort', text: 'Gefängnis' },
	{ category: 'Ort', text: 'Kneipe' },
    { category: 'Ort', text: 'Restaurant' },
	{ category: 'Ort', text: 'Safari' },
    { category: 'Ort', text: 'Sägewerk' },
	{ category: 'Ort', text: 'Schule' },
	{ category: 'Ort', text: 'Wolkenkratzer' }, 
    { category: 'Ort', text: 'Supermarkt' },
	{ category: 'Ort', text: 'Schwimmbad' },
    { category: 'Ort', text: 'Tempel' },
    { category: 'Ort', text: 'Bahnhof' },
	{ category: 'Ort', text: 'Theater' },
	{ category: 'Ort', text: 'Themenpark' },
	{ category: 'Ort', text: 'Tierklinik' },
	{ category: 'Ort', text: 'Zoo' },

    { text: 'Flugzeug', category: 'Transport' },
    { text: 'Fahrrad', category: 'Transport' },
	{ text: 'Bus', category: 'Transport' },
	{ text: 'Boot', category: 'Transport' },
    { text: 'Hundeschlitten', category: 'Transport' },
	{ text: 'Doppeldecker-Bus', category: 'Transport' },
    { text: 'F-16', category: 'Transport' },
    { text: 'Gabelstapler', category: 'Transport' },
    { text: 'Formel Eins', category: 'Transport' },
    { text: 'Golfwagen', category: 'Transport' },
    { text: 'Hubschrauber', category: 'Transport' },
    { text: 'Hoverboard', category: 'Transport' },
	{ text: 'Eiscreme-Truck', category: 'Transport' },
    { text: 'Jeep', category: 'Transport' },
    { text: 'Minivan', category: 'Transport' },
    { text: 'Ozeandampfer', category: 'Transport' },
    { text: 'Rikscha', category: 'Transport' },
    { text: 'Raketenschiff', category: 'Transport' },
	{ text: 'Ruderboot', category: 'Transport' },
    { text: 'Segelboot', category: 'Transport' },
    { text: 'Scooter', category: 'Transport' },
    { text: 'Shuttle', category: 'Transport' },
	{ text: 'Raumschiff', category: 'Transport' },
	{ text: 'Sportwagen', category: 'Transport' },
    { text: 'Postkutsche', category: 'Transport' },
    { text: 'Dampfschiff', category: 'Transport' },
    { text: 'U-Boot', category: 'Transport' },
    { text: 'Traktor', category: 'Transport' },
    { text: 'Zug', category: 'Transport' },
	{ text: 'Straßenbahn', category: 'Transport' },
    { text: 'Abschleppwagen', category: 'Transport' },
    { text: 'Dreirad', category: 'Transport' },
    { text: 'Schlepper', category: 'Transport' },
    { text: 'Einrad', category: 'Transport' },
    { text: 'Yacht', category: 'Transport' },
    { text: 'Zeppelin', category: 'Transport' },

	{ text: 'AC/DC', category: 'Musikgruppe' },
    { text: 'Adele', category: 'Musikgruppe' },
    { text: 'Beatles', category: 'Musikgruppe' },
    { text: 'Beyonce', category: 'Musikgruppe' },
    { text: 'Billie Eilish', category: 'Musikgruppe' },
    { text: 'Bon Jovi', category: 'Musikgruppe' },
    { text: 'Bruno Mars', category: 'Musikgruppe' },
    { text: 'Childish Gambino', category: 'Musikgruppe' },
    { text: 'Coldplay', category: 'Musikgruppe' },
	{ text: 'David Bowie', category: 'Musikgruppe' },
    { text: 'Daftpunk', category: 'Musikgruppe' },
    { text: 'Dr. Dre', category: 'Musikgruppe' },
    { text: 'Drake', category: 'Musikgruppe' },
    { text: 'Ed Shiran', category: 'Musikgruppe' },
	{ text: 'Elton John', category: 'Musikgruppe' },
    { text: 'Eminem', category: 'Musikgruppe' },
    { text: 'Guns And Roses', category: 'Musikgruppe' },
    { text: 'Jay Z', category: 'Musikgruppe' },
    { text: 'Justin Bieber', category: 'Musikgruppe' },
    { text: 'Justin Timberlake', category: 'Musikgruppe' },
    { text: 'Kanye West', category: 'Musikgruppe' },
    { text: 'Katy Perry', category: 'Musikgruppe' },
    { text: 'Lady Gaga', category: 'Musikgruppe' },
    { text: 'Led Zeppelin', category: 'Musikgruppe' },
    { text: 'Mariah Carey', category: 'Musikgruppe' },
    { text: 'Michael Jackson', category: 'Musikgruppe' },
    { text: 'Muse', category: 'Musikgruppe' },
    { text: 'Nicki Minaj', category: 'Musikgruppe' },
    { text: 'Nirvana', category: 'Musikgruppe' },
    { text: 'Pink Floyd', category: 'Musikgruppe' },
    { text: 'Pitbull', category: 'Musikgruppe' },
    { text: 'Prince', category: 'Musikgruppe' },
    { text: 'Queen', category: 'Musikgruppe' },
    { text: 'Rihana', category: 'Musikgruppe' },
    { text: 'Skrillex', category: 'Musikgruppe' },
    { text: 'Snoop dogg', category: 'Musikgruppe' },
    { text: 'Taylor Swift', category: 'Musikgruppe' },
    { text: 'The Black Eyed Peas', category: 'Musikgruppe' },
    { text: 'Tupac Shakur', category: 'Musikgruppe' },
    { text: 'U2', category: 'Musikgruppe' },
	{ text: 'Die Toten Hosen', category: 'Musikgruppe' },
    { text: 'Die Ärzte', category: 'Musikgruppe' },
    { text: 'Helene Fischer', category: 'Musikgruppe' },
    { text: 'Kettcar', category: 'Musikgruppe' },



    { text: 'Dubstep', category: 'Music Genre' },
    { text: 'House', category: 'Musikgenre' },
    { text: 'Rock', category: 'Musikgenre' },
    { text: 'Hip Hop', category: 'Musikgenre' },
    { text: 'Blues', category: 'Musikgenre' },
    { text: 'Pop', category: 'Musikgenre' },
    { text: 'Jazz', category: 'Musikrichtung' },
    { text: 'Klassisch', category: 'Musikgenre' },
    { text: 'R&B', category: 'Musikgenre' },
    { text: 'Heavy Metal', category: 'Musikgenre' },
    { text: 'Punk', category: 'Musikgenre' },
    { text: 'Country', category: 'Musikgenre' },
    { text: 'Reggae', category: 'Musikgenre' },
    { text: 'Fahrstuhlmusik', category: 'Musikgenre' },
    { text: 'Disco', category: 'Musikgenre' },
    { text: 'Techno', category: 'Musikgenre' },
    { text: 'K-Pop', category: 'Musikgenre' },
    { text: 'Grunge', category: 'Musikgenre' },
    { text: 'Rap', category: 'Musikgenre' },
    { text: 'Swing', category: 'Musikgenre' },

    { text: 'Dudelsack', category: 'Musikinstrument' },
    { text: 'Bassgitarre', category: 'Musikinstrument' },
    { text: 'Jukebox', category: 'Musikinstrument' },
    { text: 'Posaune', category: 'Musikinstrument' },
    { text: 'Schlagzeug', category: 'Musikinstrument' },
    { text: 'Ukulele', category: 'Musikinstrument' },
    { text: 'E-Gitarre', category: 'Musikinstrument' },
    { text: 'Klavier', category: 'Musikinstrument' },
    { text: 'Violine', category: 'Musikinstrument' },
    { text: 'Saxophon', category: 'Musikinstrument' },
    { text: 'Cello', category: 'Musikinstrument' },
    { text: 'Flöte', category: 'Musikinstrument' },
    { text: 'Klarinette', category: 'Musikinstrument' },
    { text: 'Trompete', category: 'Musikinstrument' },
    { text: 'Mundharmonika', category: 'Musikinstrument' },
    { text: 'Harfe', category: 'Musikinstrument' },
    { text: 'Banjo', category: 'Musikinstrument' },
    { text: 'Kastagnetten', category: 'Musikinstrument' },
    { text: 'Kazoo', category: 'Musikinstrument' },
    { text: 'Kuhglocke', category: 'Musikinstrument' },
    { text: 'Cymbal', category: 'Musikinstrument' },
    { text: 'Gong', category: 'Musikinstrument' },
    { text: 'Maraca', category: 'Musikinstrument' },
    { text: 'Marimba', category: 'Musikinstrument' },
    { text: 'Tamburin', category: 'Musikinstrument' },
    { text: 'Triangel', category: 'Musikinstrument' },
    { text: 'Waschbrett', category: 'Musikinstrument' },
    { text: 'Xylophon', category: 'Musikinstrument' },
    { text: 'Akkordeon', category: 'Musikinstrument' },
    { text: 'Horn', category: 'Musikinstrument' },
    { text: 'Signalhorn', category: 'Musikinstrument' },
    { text: 'Didgeridoo', category: 'Musikinstrument' },
    { text: 'Oboe', category: 'Musikinstrument' },
    { text: 'Ocarina', category: 'Musikinstrument' },
    { text: 'Piccolo', category: 'Musikinstrument' },
    { text: 'Pfeife', category: 'Musikinstrument' },
    { text: 'Tuba', category: 'Musikinstrument' },
    { text: 'Sitar', category: 'Musikinstrument' },
    { text: 'Fiddle', category: 'Musikinstrument' },
    { text: 'Laute', category: 'Musikinstrument' },
    
    { text: 'Genie', category: 'Mythologie' },
    { text: 'Minotaurus', category: 'Mythologie' },
    { text: 'Zauberteppich', category: 'Mythologie' },
    { text: 'Greifen', category: 'Mythologie' },
    { text: 'Minotaurus', category: 'Mythologie' },
    { text: 'Bigfoot', category: 'Mythologie' },
    { text: 'Chimäre', category: 'Mythologie' },
    { text: 'Zyklop', category: 'Mythologie' },
    { text: 'Zentaur', category: 'Mythologie' },
    { text: 'Meerjungfrau', category: 'Mythologie' },
    { text: 'Pegasus', category: 'Mythologie' },
    { text: 'Phönix', category: 'Mythologie' },
    { text: 'Einhorn', category: 'Mythologie' },
    { text: 'Vampir', category: 'Mythologie' },
    { text: 'Drache', category: 'Mythologie' },
    { text: 'Dryade', category: 'Mythologie' },
    { text: 'Geist', category: 'Mythologie' },
    { text: 'Medusa', category: 'Mythologie' },
    { text: 'Mantikor', category: 'Mythologie' },
    { text: 'Satyr', category: 'Mythologie' },
    { text: 'Sphinx', category: 'Mythologie' },
    { text: 'Werwolf', category: 'Mythologie' },
    { text: 'Zombie', category: 'Mythologie' },
    { text: 'Mumie', category: 'Mythologie' },
    { text: 'Golem', category: 'Mythologie' },
    { text: 'Amazonenkriegerin', category: 'Mythologie' },
    { text: 'Echsenmenschen', category: 'Mythologie' },
    { text: 'Basilisk', category: 'Mythologie' },
    { text: 'Goblin', category: 'Mythologie' },
    { text: 'Fee', category: 'Mythologie' },
    { text: 'Ghoul', category: 'Mythologie' },
    { text: 'Kobold', category: 'Mythologie' },
    { text: 'Troll', category: 'Mythologie' },
    { text: 'Oger', category: 'Mythologie' },
    { text: 'Nymphe', category: 'Mythologie' },
    { text: 'Riese', category: 'Mythology' },
    { text: 'Elf', category: 'Mythology' },


    { text: 'angelina jolie', category: 'Berühmte Personen' },
    { text: 'bob dylan', category: 'Berühmte Personen' },
    { text: 'brad pitt', category: 'Berühmte Personen' },
    { text: 'bruce lee', category: 'Berühmte Personen' },
    { text: 'geronimo', category: 'Berühmte Personen' },
    { text: 'greenday', category: 'Berühmte Personen' },
    { text: 'kate moss', category: 'Berühmte Personen' },
    { text: 'lady gaga', category: 'Berühmte Personen' },
    { text: 'lil wayne', category: 'Berühmte Personen' },
    { text: 'ludacris', category: 'Berühmte Personen' },
    { text: 'mc hammer', category: 'Berühmte Personen' },
    { text: 'tom hanks', category: 'Berühmte Personen' },
    { text: 'beckham', category: 'Berühmte Personen' },
    { text: 'colbert', category: 'Berühmte Personen' },
    { text: 'jay leno', category: 'Berühmte Personen' },
    { text: 'lincoln', category: 'Berühmte Personen' },
    { text: 'picasso', category: 'Berühmte Personen' },
    { text: 'rihanna', category: 'Berühmte Personen' },
    { text: 'van gogh', category: 'Berühmte Personen' },
    { text: 'justin bieber', category: 'Berühmte Personen' },
    { text: 'eminem', category: 'Berühmte Personen' },
    { text: 'gandhi', category: 'Berühmte Personen' },
    { text: 'madonna', category: 'Berühmte Personen' },
    { text: 'pitbull', category: 'Berühmte Personen' },
	{ text: 'vincent van gogh', category: 'Berühmte Personen' },
	{ text: 'Donald Trump', category: 'Berühmte Personen' },
	{ text: 'Angela Merkel', category: 'Berühmte Personen' },
	{ text: 'Mozart', category: 'Berühmte Personen' },
	{ text: 'Kai Pflaume', category: 'Berühmte Personen' },
	{ text: 'Stefan Raab', category: 'Berühmte Personen' },
	{ text: 'Thomas Gottschalk', category: 'Berühmte Personen' },
	{ text: 'Joko & Klaas', category: 'Berühmte Personen' },

    { text: 'Bogenschießen', category: 'Sport' },
    { text: 'baseball', category: 'Sport' },
    { text: 'Basketball', category: 'Sport' },
    { text: 'Bowling', category: 'Sport' },
    { text: 'Boxen', category: 'Sport' },
    { text: 'Curling', category: 'Sport' },
	{ text: 'Cricket', category: 'Sport' },
    { text: 'Kurzhantel', category: 'Sport' },
    { text: 'Fechten', category: 'Sport' },
    { text: 'Angeln', category: 'Sport' },
    { text: 'Fußball', category: 'Sport' },
    { text: 'frisbee', category: 'Sport' },
    { text: 'Torpfosten', category: 'Sport' },
    { text: 'Golf', category: 'Sport' },
    { text: 'Halfpipe', category: 'Sport' },
    { text: 'handball', category: 'Sport' },
    { text: 'homerun', category: 'Sport' },
    { text: 'Schlittschuhlaufen', category: 'Sports' },
    { text: 'Speerwurf', category: 'Sports' },
    { text: 'Seilspringen', category: 'Sports' },
    { text: 'Lacrosse', category: 'Sports' },
    { text: 'Weitsprung', category: 'Sport' },
    { text: 'Minigolf', category: 'Sport' },  
    { text: 'Olympiade', category: 'Sport' },
    { text: 'Tischtennis', category: 'Sport' },
    { text: 'rebound', category: 'Sport' },
    { text: 'schiedsrichter', category: 'Sport' },
	{ text: 'Klettern', category: 'Sport' },
    { text: 'Slamdunk', category: 'Sport' },
    { text: 'Schlittenfahren', category: 'Sport' },
	{ text: 'Fußball', category: 'Sport' },
    { text: 'Surfen', category: 'Sport' },
	{ text: 'Schwimmen', category: 'Sport' },
	{ text: 'Tennis', category: 'Sport' },
    { text: 'Volleyball', category: 'Sport' },


    { text: 'Sandmann', category: 'Popkultur' },
    { text: 'Catwoman', category: 'Popkultur' },
    { text: 'Garfield', category: 'Popkultur' },
    { text: 'superman', kategorie: 'Popkultur' },
    { text: 'aladdin', kategorie: 'Popkultur' },
    { text: 'Ironman', kategorie: 'Popkultur' },
    { text: 'asterix', category: 'Popkultur' },
    { text: 'hawkeye', kategorie: 'Popkultur' },
    { text: 'metroid', kategorie: 'Popkultur' },
    { text: 'Pikachu', category: 'Popkultur' },
    { text: 'riddler', kategorie: 'Popkultur' },
    { text: 'rugrats', category: 'Popkultur' },
    { text: 'Twoface', category: 'Popkultur' },
    { text: 'avatar', category: 'Popkultur' },
    { text: 'barbie', category: 'Popkultur' },
    { text: 'batman', category: 'Popkultur' },
    { text: 'Die Maus', category: 'Popkultur' },
    { text: 'bowser', category: 'Popkultur' },
    { text: 'Legend of Zelda', category: 'Popkultur' },
    { text: 'Mickey Mouse', category: 'Popkultur' },
    { text: 'Voldemort', category: 'Popkultur' },
    { text: 'Conan der Barbar', category: 'Popkultur' },
    { text: 'Die Simpsons', category: 'Popkultur' },
    { text: 'Rick & Morty', category: 'Popkultur' },
    { text: 'Kermit', category: 'Popkultur' },
    { text: 'Spongebob', category: 'Popkultur' },
    { text: 'Simba', category: 'Popkultur' },
	{ text: 'Scooby Doo', category: 'Popkultur' },
	
    { text: 'Künstler', category: 'Beruf' },
    { text: 'Meuchelmörder', category: 'Beruf' },
    { text: 'Barbier', category: 'Beruf' },
    { text: 'Metzger', category: 'Beruf' },
    { text: 'Kapitän', category: 'Beruf' },
    { text: 'Kassierer', category: 'Beruf' },
	{ text: 'Koch', category: 'Beruf' },
	{ text: 'Clown', category: 'Beruf' },
	{ text: 'Koch', category: 'Beruf' },
    { text: 'Zahnarzt', category: 'Beruf' },
    { text: 'DJ', category: 'Beruf' },
    { text: 'Arzt', category: 'Beruf' },
    { text: 'Schlagzeuger', category: 'Beruf' },
    { text: 'Landwirt', category: 'Beruf' },
    { text: 'Feuerwehrmann', category: 'Beruf' },
	{ text: 'Hacker', category: 'Beruf' },
    { text: 'Gangster', category: 'Beruf' },
    { text: 'Gärtner', category: 'Beruf' },
    { text: 'Turner', category: 'Beruf' },
    { text: 'Hausmeister', category: 'Beruf' },
	{ text: 'Rechtsanwalt', category: 'Beruf' },
    { text: 'Zauberer', category: 'Beruf' },
    { text: 'Postbote', category: 'Beruf' },
    { text: 'Milkman', category: 'Beruf' },
    { text: 'Filmregisseur', category: 'Beruf' },
    { text: 'Opernsänger', category: 'Beruf' },
    { text: 'Maler', category: 'Beruf' },
	{ text: 'Pilot', category: 'Beruf' },
    { text: 'Klempner', category: 'Beruf' },
    { text: 'Polizist', category: 'Beruf' },
    { text: 'Poolboy', category: 'Beruf' },
    { text: 'Priester', category: 'Beruf' },
    { text: 'Prinzessin', category: 'Beruf' },
    { text: 'Sheriff', category: 'Beruf' },
    { text: 'Soldat', category: 'Beruf' },
    { text: 'Chirurg', category: 'Beruf' },
    { text: 'Lehrer', category: 'Beruf' },
    { text: 'Lehrer', category: 'Beruf' },
    { text: 'Kellner', category: 'Beruf' },
    { text: 'Krieger', category: 'Beruf' },
    { text: 'Fensterputzer', category: 'Beruf' },
    { text: 'Wrestler', category: 'Beruf' },

    { category: 'Tier', text: 'Erdferkel' },
    { category: 'Tier', text: 'Alpaka' },
    { category: 'Tier', text: 'Ameise' }, 
    { category: 'Tier', text: 'Ameisenbär' },
    { category: 'Tier', text: 'Gürteltier' },
    { category: 'Tier', text: 'Pavian' },
    { category: 'Tier', text: 'Dachs' },
	{ category: 'Tier', text: 'Fledermaus' },
    { category: 'Tier', text: 'Bär' },
    { category: 'Tier', text: 'Biber' }, 
    { category: 'Tier', text: 'Biene' },
    { category: 'Tier', text: 'Vogel' },
    { category: 'Tier', text: 'Büffel' }, 
    { category: 'Tier', text: 'Stier' },
    { category: 'Tier', text: 'Kalb' },
    { category: 'Tier', text: 'Kamel' },
    { category: 'Tier', text: 'Katze' },
    { category: 'Tier', text: 'Raupe' }, 
	{ category: 'Tier', text: 'Wels' },
	{ category: 'Tier', text: 'Chamäleon' }, 
    { category: 'Tier', text: 'Gepard' }, 
    { category: 'Tier', text: 'Huhn' },
    { category: 'Tier', text: 'Schimpanse' },
    { category: 'Tier', text: 'Chihuahua' }, 
    { category: 'Tier', text: 'Zikade ' },
	{ category: 'Tier', text: 'Kakerlake' },
    { category: 'Tier', text: 'Kuh' },
    { category: 'Tier', text: 'Kranich' },
	{ category: 'Tier', text: 'Krabbe' },
    { category: 'Tier', text: 'Grille' },
    { category: 'Tier', text: 'Krokodil' }, 
    { category: 'Tier', text: 'Hirsch' },
    { category: 'Tier', text: 'Dinosaurier' },
    { category: 'Tier', text: 'Hund' },
    { category: 'Tier', text: 'Delphin' },
    { category: 'Tier', text: 'Esel' },
    { category: 'Tier', text: 'Ente' },
	{ category: 'Tier', text: 'Libelle' },
    { category: 'Tier', text: 'Adler' }, 
    { category: 'Tier', text: 'Elefant' }, 
	{ category: 'Tier', text: 'Glühwürmchen' },
    { category: 'Tier', text: 'Fisch' },
    { category: 'Tier', text: 'Flamingo' },
    { category: 'Tier', text: 'Fliege' },
    { category: 'Tier', text: 'Fuchs' },
    { category: 'Tier', text: 'Frosch' },
    { category: 'Tier', text: 'Giraffe' },
    { category: 'Tier', text: 'Ziege' }, 
    { category: 'Tier', text: 'Goldfisch' },
	{ category: 'Tier', text: 'Gans' }, 
    { category: 'Tier', text: 'Gorilla' }, 
    { category: 'Tier', text: 'Grashüpfer' },
    { category: 'Tier', text: 'Hamster' },
    { category: 'Tier', text: 'Nilpferd' }, 
    { category: 'Tier', text: 'Pferd' }, 
    { category: 'Tier', text: 'Hyäne' },
    { category: 'Tier', text: 'Jaguar' },
    { category: 'Tier', text: 'Känguru' },
    { category: 'Tier', text: 'Kätzchen' },
    { category: 'Tier', text: 'Marienkäfer' },
    { category: 'Tier', text: 'Leopard' },
    { category: 'Tier', text: 'Löwe' }, 
    { category: 'Tier', text: 'Eidechse' },
    { category: 'Tier', text: 'Lama' },
    { category: 'Tier', text: 'Hummer' }, 
    { category: 'Tier', text: 'Mammut' }, 
    { category: 'Tier', text: 'Affe' },
    { category: 'Tier', text: 'Moskito' },
	{ category: 'Tier', text: 'Elch' },
    { category: 'Tier', text: 'Maus' }, 
    { category: 'Tier', text: 'Einhornwal' }, 
    { category: 'Tier', text: 'Oktopus' }, 
    { category: 'Tier', text: 'Strauß' },
    { category: 'Tier', text: 'Otter' },
    { category: 'Tier', text: 'Eule' },
  { category: 'Tier', text: 'Otter' },
    { category: 'Tier', text: 'Eule' },
    { category: 'Tier', text: 'Auster' },
    { category: 'Tier', text: 'Panda' },
    { category: 'Tier', text: 'Schuppentier' }, 
	{ category: 'Tier', text: 'Papagei' },
    { category: 'Tier', text: 'Panther' },
    { category: 'Tier', text: 'Pfau' }, 
    { category: 'Tier', text: 'Pelikan' }, 
    { category: 'Tier', text: 'Pinguin' },
    { category: 'Tier', text: 'Schwein' },
    { category: 'Tier', text: 'Taube' }, 
	{ category: 'Tier', text: 'Pitbull' },
	{ category: 'Tier', text: 'Schnabeltier' }, 
    { category: 'Tier', text: 'Stachelschwein' },
	{ category: 'Tier', text: 'Pudel' },
    { category: 'Tier', text: 'Welpe' }, 
    { category: 'Tier', text: 'Kaninchen' }, 
    { category: 'Tier', text: 'Waschbär' }, 
    { category: 'Tier', text: 'Ratte' },
    { category: 'Tier', text: 'Rentier' }, 
	{ category: 'Tier', text: 'Reptil' },
    { category: 'Tier', text: 'Nashorn' },
    { category: 'Tier', text: 'Hahn' }, 
    { category: 'Tier', text: 'Skorpion' },
    { category: 'Tier', text: 'Möwe' }, 
    { category: 'Tier', text: 'Seepferdchen' }, 
    { category: 'Tier', text: 'Seehund' },
    { category: 'Tier', text: 'Hai' },
    { category: 'Tier', text: 'Schaf' },
    { category: 'Tier', text: 'Garnele' },
	{ category: 'Tier', text: 'Stinktier' },
    { category: 'Tier', text: 'Schnecke' },
    { category: 'Tier', text: 'Schlange' },
    { category: 'Tier', text: 'Spinne' },
    { category: 'Tier', text: 'Tintenfisch' },
    { category: 'Tier', text: 'Eichhörnchen' },
    { category: 'Tier', text: 'Seestern' }, 
    { category: 'Tier', text: 'Storch' }, 
    { category: 'Tier', text: 'Schwan' },
    { category: 'Tier', text: 'Kaulquappe' }, 
    { category: 'Tier', text: 'Tiger' }, 
    { category: 'Tier', text: 'Kröte' },
    { category: 'Tier', text: 'tropischer Fisch' },
    { category: 'Tier', text: 'Thunfisch' },
    { category: 'Tier', text: 'Truthahn' },
    { category: 'Tier', text: 'Schildkröte' },
    { category: 'Tier', text: 'Schildkröte' }, 
	{ category: 'Tier', text: 'Geier' },
	{ category: 'Tier', text: 'Walross' },
    { category: 'Tier', text: 'Wal' }, 
    { category: 'Tier', text: 'Wolf' },
    { category: 'Tier', text: 'Wombat' }, 
    { category: 'Tier', text: 'Wurm' },
	{ category: 'Tier', text: 'Zebra' },

   { text: 'Speck', category: 'Lebensmittel' },
    { text: 'Baguette', category: 'Lebensmittel' },
    { text: 'Barbeque', category: 'Lebensmittel' },
    { text: 'Bohnen', category: 'Lebensmittel' },
    { text: 'Bier', category: 'Lebensmittel' },
    { text: 'Burrito', category: 'Lebensmittel' },
	{ text: 'Torte', category: 'Lebensmittel' },
    { text: 'Müsli', category: 'Lebensmittel' },
    { text: 'Champagner', category: 'Lebensmittel' },
    { text: 'Käse', category: 'Lebensmittel' },
    { text: 'Chicken Wings', category: 'Lebensmittel' },
    { text: 'Kaffee', category: 'Lebensmittel' },
    { text: 'Corndog', category: 'Lebensmittel' },
	{ text: 'Croissant', category: 'Lebensmittel' },
    { text: 'Cupcake', category: 'Lebensmittel' },
    { text: 'Frühlingsrolle', category: 'Lebensmittel' },
    { text: 'Espresso', category: 'Lebensmittel' },
    { text: 'Fast Food', category: 'Lebensmittel' },
    { text: 'Fisch und Chips', category: 'Lebensmittel' },
    { text: 'Zuckerguss', category: 'Lebensmittel' },
	{ text: 'Hamburger', category: 'Lebensmittel' },
    { text: 'Schinkenknochen', category: 'Lebensmittel' },
    { text: 'Hamwich', category: 'Lebensmittel' },
    { text: 'Scharfe Soße', category: 'Lebensmittel' },
    { text: 'Junk Food', category: 'Lebensmittel' },
    { text: 'Kebab', category: 'Lebensmittel' },
	{ text: 'Ketchup', category: 'Lebensmittel' },
	{ text: 'Lasagna', category: 'Lebensmittel' },
    { text: 'Limonade', category: 'Lebensmittel' },
    { text: 'Makkaroni', category: 'Lebensmittel' },
    { text: 'Martini', category: 'Lebensmittel' },
    { text: 'Kartoffelpüree', category: 'Lebensmittel' },
    { text: 'Fleischbällchen', category: 'Lebensmittel' },
	{ text: 'Milch', category: 'Lebensmittel' },
    { text: 'Pilz', category: 'Lebensmittel' },
    { text: 'Senf', category: 'Lebensmittel' },
    { text: 'Nudeln', category: 'Lebensmittel' },
    { text: 'Haferflocken', category: 'Lebensmittel' },
    { text: 'Pfannkuchen', category: 'Lebensmittel' },
    { text: 'Nudeln', category: 'Lebensmittel' },
    { text: 'Kuchen', category: 'Lebensmittel' },
    { text: 'Pizza', category: 'Lebensmittel' },
    { text: 'Popcorn', category: 'Lebensmittel' },
    { text: 'Brezel', category: 'Lebensmittel' },
    { text: 'Kürbis', category: 'Lebensmittel' },
    { text: 'Salat', category: 'Lebensmittel' },
    { text: 'Sandwich', category: 'Lebensmittel' },
    { text: 'Würstchen', category: 'Lebensmittel' },
    { text: 'Meeresfrüchte', category: 'Lebensmittel' },
    { text: 'Smoothie', category: 'Lebensmittel' },
    { text: 'Snowcone', category: 'Lebensmittel' },
    { text: 'Sojasoße', category: 'Lebensmittel' },
    { text: 'Sushi', category: 'Lebensmittel' },
    { text: 'Tee', category: 'Lebensmittel' },
    { text: 'Tequila', category: 'Lebensmittel' },
	{ text: 'Waffeln', category: 'Lebensmittel' },
    { text: 'Whiskey', category: 'Lebensmittel' },



    { text: 'Horror', category: 'Film Genres' },
    { text: 'Action', category: 'Film Genres' },
    { text: 'Thriller', category: 'Film Genres' },
    { text: 'Sci-Fi', category: 'Film Genres' },
    { text: 'Rom-Com', category: 'Film Genres' },
    { text: 'Western', category: 'Film Genres' },
    { text: 'Komödie', category: 'Film Genres' },
    { text: 'Gangster', category: 'Film Genres' },
    { text: 'Slapstick', category: 'Film Genres' },
    { text: 'Krieg', category: 'Film Genres' },
    { text: 'Dokumentarfilm', category: 'Film Genres' },
    { text: 'Mockumentry', category: 'Film Genres' },
    { text: 'Musical', category: 'Film Genres' },
    { text: 'Animation', category: 'Film Genres' },
    { text: 'Katastrophenfilm', category: 'Film Genres' },
    { text: 'Zombies', category: 'Film Genres' },
    { text: 'Sport', category: 'Film Genres' },

    { text: 'A Clockwork Orange', category: 'Filme' },
	{ text: 'Armagedon', category: 'Filme' },
    { text: 'Alien', category: 'Filme' },
    { text: 'Austin Powers', category: 'Filme' },
    { text: 'Avengers', category: 'Filme' },
    { text: 'Zurück in die Zukunft', category: 'Filme' },
    { text: 'Braveheart', category: 'Filme' },
	{ text: 'Beetlejuice', category: 'Filme' },
    { text: 'Stirb langsam', category: 'Filme' },
    { text: 'E.T.', category: 'Filme' },
    { text: 'Fargo', category: 'Filme' },
    { text: 'Finding Nemo', category: 'Filme' },
    { text: 'Forrest Gump', category: 'Filme' },
	{ text: 'Frozen', category: 'Filme' },
    { text: 'Gladiator', category: 'Filme' },
    { text: 'Golden Eye', category: 'Filme' },
    { text: 'Vom Winde verweht', category: 'Filme' },
    { text: 'Murmeltiertag', category: 'Filme' },
    { text: 'Home Alone', category: 'Filme' },
    { text: 'Inception', category: 'Filme' },
    { text: 'Indiana Jones', category: 'Filme' },
    { text: 'Inglourious Basterds', category: 'Filme' },
    { text: 'Der weiße Hai', category: 'Filme' },
    { text: 'Jurassic Park', category: 'Filme' },
    { text: 'King Kong', category: 'Filme' },
    { text: 'König der Löwen', category: 'Filme' },
    { text: 'Mary Poppins', category: 'Filme' },
    { text: 'Minority Report', category: 'Filme' },
    { text: 'Mission Impossible', category: 'Filme' },
    { text: 'Monty Python und der Heilige Gral', category: 'Filme' },
    { text: 'Pulp Fiction', category: 'Filme' },
    { text: 'Rocky Horror Picture Show', category: 'Filme' },
    { text: 'Rocky', category: 'Filme' },
    { text: 'Saving Private Ryan', category: 'Filme' },
    { text: 'Scarface', category: 'Filme' },
    { text: 'Shrek', category: 'Filme' },
    { text: 'Star Wars', category: 'Filme' },
    { text: 'Terminator', category: 'Filme' },
    { text: 'The Good, the Bad and the Ugly', category: 'Filme' },
    { text: 'The Green Mile', category: 'Filme' },
    { text: 'Der Herr der Ringe', category: 'Filme' },
    { text: 'The Matrix', category: 'Filme' },
    { text: 'Die Verurteilten', category: 'Filme' },
    { text: 'The Social Network', category: 'Filme' },
    { text: 'Der Zauberer von Oz', category: 'Filme' },
    { text: 'Titanic', category: 'Filme' },
    { text: 'Toy Story', category: 'Filme' },
    { text: 'West Side Story', category: 'Filme' },
    { text: 'Wonder Woman', category: 'Filme' },
    { text: 'X-Men', category: 'Filme' },
	{ text: 'Robocop', category: 'Filme' },


    { text: 'Saures Bonbon', category: 'Snacks' },
    { text: 'Twinkie', category: 'Snacks' },
    { text: 'Lollipop', category: 'Snacks' },
    { text: 'Eis am Stiel', category: 'Snacks' },
    { text: 'Skittles', category: 'Snacks' },
    { text: 'Brownie', category: 'Snacks' },
    { text: 'Cookie', category: 'Snacks' },
    { text: 'Doritos', category: 'Snacks' },
    { text: 'Saures Bonbon', category: 'Snacks' },
    { text: 'Eiscreme', category: 'Snacks' },

    { text: 'Die Pyramiden', category: 'Berühmtes Wahrzeichen' },
    { text: 'Christus der Erlöser-Statue', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die Große Chinesische Mauer', category: 'Berühmtes Wahrzeichen' },
    { text: 'Schiefer Turm von Pisa', category: 'Berühmtes Wahrzeichen' },
    { text: 'Empire State Building', category: 'Berühmtes Wahrzeichen' },
    { text: 'Kolosseum', category: 'Berühmtes Wahrzeichen' },
    { text: 'Der Eiffelturm', category: 'Berühmtes Wahrzeichen' },
    { text: 'Freiheitsstatue', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die Sphinx', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die kleine Meerjungfrau', category: 'Berühmtes Wahrzeichen' },
    { text: 'Das Taj Mahal', category: 'Berühmtes Wahrzeichen' },
    { text: 'Big Ben', category: 'Berühmtes Wahrzeichen' },
    { text: 'Loch Ness', category: 'Berühmtes Wahrzeichen' },
    { text: 'Brandenburger Tor', category: 'Berühmtes Wahrzeichen' },
    { text: 'Akropolis', category: 'Berühmtes Wahrzeichen' },
    { text: 'Stonehenge', category: 'Berühmtes Wahrzeichen' },
    { text: 'Osterinsel', category: 'Berühmtes Wahrzeichen' },
    { text: 'Capitol Hill', category: 'Berühmtes Wahrzeichen' },
    { text: 'Niagra Falls', category: 'Berühmtes Wahrzeichen' },
    { text: 'Mount Rushmore', category: 'Berühmtes Wahrzeichen' },
    { text: 'Grand Canyon', category: 'Berühmtes Wahrzeichen' },
    { text: 'Fontana de Trevi', category: 'Berühmtes Wahrzeichen' },
    { text: 'Sydney Opera House', category: 'Berühmtes Wahrzeichen' },
    { text: 'Golden Gate Bridge', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die Verbotene Stadt', category: 'Berühmtes Wahrzeichen' },
    { text: 'Der Kreml', category: 'Berühmtes Wahrzeichen' },
    { text: 'Der Louvre', category: 'Berühmtes Wahrzeichen' },
    { text: 'Das Hollywood-Zeichen ', category: 'Berühmtes Wahrzeichen' },

    { text: 'Cinderella', category: 'Märchen' },
    { text: 'Die drei kleinen Schweinchen', category: 'Märchen' },
    { text: 'Das hässliche Entlein', category: 'Märchen' },
    { text: 'Die Prinzessin auf der Erbse', category: 'Märchen' },
    { text: 'Däumelinchen', category: 'Märchen' },
    { text: 'Die kleine Meerjungfrau', category: 'Märchen' },
    { text: 'Däumelinchen', category: 'Märchen' },
    { text: "Des Kaisers neue Kleider", category: 'Märchen' },
    { text: 'Dornröschen', category: 'Märchen' },
    { text: 'Schneewittchen', category: 'Märchen' },
    { text: 'Rapunzel', category: 'Märchen' },
    { text: 'Der Froschkönig', category: 'Märchen' },
    { text: 'Hänsel und Gretel', category: 'Märchen' },
    { text: 'Rumpelstilzchen', category: 'Märchen' },
    { text: 'Die goldene Gans', category: 'Märchen' },
    { text: 'Der gestiefelte Kater', category: 'Märchen' },
    { text: 'Aladdin', category: 'Märchen' },
    { text: 'Die Schöne und das Biest', category: 'Märchen' },
    { text: 'Ali Baba und die vierzig Räuber', category: 'Märchen' },
    { text: 'Sindbad', category: 'Märchen' },
    
]
