words_en = [
{text:'grandma',category:'family'},
{text:'grandpa',category:'family'},
{text:'husband',category:'family'},
{text:'parents',category:'family'},
{text:'wife',category:'family'},
{text:'uncle',category:'family'},
{text:'aunt',category:'family'},
{text:'father',category:'family'},
{text:'mother',category:'family'},
{text:'step sister',category:'family'},
{text:'step brother',category:'family'},
{text:'step father',category:'family'},
{text:'step mother',category:'family'},
{text:'god father',category:'family'},
{text:'god mother',category:'family'},
{text:'mother in law',category:'family'},
{text:'father in law',category:'family'},
{text:'children',category:'family'},
{text:'brother',category:'family'},
{text:'sister',category:'family'},
{text:'cousin',category:'family'},
{text:'granddaugther',category:'family'},
{text:'grandson',category:'family'},
{text:'niece',category:'family'},
{text:'nephew',category:'family'},

{text:'festivus',category:'festivity'},
{text:'hanukkah',category:'festivity'},
{text:'kwanzaa',category:'festivity'},
{text:'wedding',category:'festivity'},
{text:'birthday',category:'festivity'},
{text:'bar mitzvah',category:'festivity'},
{text:'halloween',category:'festivity'},
{text:'octoberfest',category:'festivity'},
{text:'christmas',category:'festivity'},
{text:'Día de Muertos',category:'festivity'},
{text:'new year`s eve',category:'festivity'},
{text:'groundhog day',category:'festivity'},
{text:'Valentine`s Day',category:'festivity'},
{text:'St. Patrick`s Day',category:'festivity'},
{text:'passover',category:'festivity'},
{text:'easter',category:'festivity'},
{text:'Ramadan',category:'festivity'},
{text:'Mother`s Day',category:'festivity'},
{text:'Independence Day',category:'festivity'},
{text:'Columbus Day',category:'festivity'},
{text:'Divali',category:'festivity'},
{text:'Black Friday',category:'festivity'},
{text:'thanksgiving',category:'festivity'},
{text:'election',category:'festivity'},

{text:'bracelet',category:'valuables'},
{text:'crystal',category:'valuables'},
{text:'diamond',category:'valuables'},
{text:'emerald',category:'valuables'},
{text:'jewelry',category:'valuables'},
{text:'gold bar',category:'valuables'},
{text:'pearls',category:'valuables'},

{text:'bromance',category:'social'},
{text:'follower',category:'social'},
{text:'highfive',category:'social'},
{text:'marriage',category:'social'},
{text:'divorce',category:'social'},
{text:'frenemy',category:'social'},

{text:'hulahoop',category:'games'},
{text:'pinwheel',category:'games'},
{text:'swingset',category:'games'},
{text:'balloon',category:'games'},
{text:'dreidel',category:'games'},
{text:'gameboy',category:'games'},

{text:'pinball',category:'games'},
{text:'checkers',category:'games'},
{text:'joystick',category:'games'},
{text:'monopoly',category:'games'},
{text:'scrabble',category:'games'},
{text:'yahtzee',category:'games'},

{text:'barstool',category:'furniture'},
{text:'bookcase',category:'furniture'},
{text:'waterbed',category:'furniture'},
{text:'bathtub',category:'furniture'},
{text:'bunkbed',category:'furniture'},
{text:'cabinet',category:'furniture'},
{text:'dresser',category:'furniture'},

{text:'chainsaw',category:'tool'},
{text:'scissors',category:'tool'},
{text:'tweezers',category:'tool'},
{text:'compass',category:'tool'},
{text:'crowbar',category:'tool'},
{text:'dustpan',category:'tool'},
{text:'stapler',category:'tool'},

{text:'lipstick',category:'toiletries'},
{text:'perfume',category:'toiletries'},
{text:'shampoo',category:'toiletries'},
{text:'nailfile',category:'toiletries'},
{text:'sunblock',category:'toiletries'},
{text:'hairdye',category:'toiletries'},
{text:'hairgel',category:'toiletries'},
{text:'mascara',category:'toiletries'},

{text:'computer',category:'computing'},
{text:'facebook',category:'computing'},
{text:'firewall',category:'computing'},
{text:'keyboard',category:'computing'},
{text:'password',category:'computing'},
{text:'hashtag',category:'computing'},
{text:'macbook',category:'computing'},
{text:'twitter',category:'computing'},

{text:'catapult',category:'weapon'},
{text:'crossbow',category:'weapon'},
{text:'dynamite',category:'weapon'},
{text:'fireball',category:'weapon'},
{text:'bayonet',category:'weapon'},
{text:'bazooka',category:'weapon'},
{text:'handgun',category:'weapon'},
{text:'missile',category:'weapon'},
{text:'shotgun',category:'weapon'},
{text:'torpedo',category:'weapon'},
{text:'cannon',category:'weapon'},

{text:'eyepatch',category:'accessory'},
{text:'headband',category:'accessory'},
{text:'kneepads',category:'accessory'},
{text:'necklace',category:'accessory'},
{text:'nosering',category:'accessory'},
{text:'partyhat',category:'accessory'},
{text:'shoelace',category:'accessory'},
{text:'umbrella',category:'accessory'},
{text:'bandana',category:'accessory'},
{text:'earring',category:'accessory'},
{text:'hairtie',category:'accessory'},
{text:'handbag',category:'accessory'},

{category:'clothing',text:'pantsuit'},
{category:'clothing', text:'bandana'},
{category:'clothing', text:'belt'},
{category:'clothing', text:'bikini'},
{category:'clothing', text:'boots'},
{category:'clothing', text:'bowtie'},
{category:'clothing', text:'cap'},
{category:'clothing', text:'coat'},
{category:'clothing', text:'dress'},
{category:'clothing', text:'earmuffs'},
{category:'clothing', text:'eyepatch'},
{category:'clothing', text:'glasses'},
{category:'clothing', text:'gloves'},
{category:'clothing', text:'hairtie'},
{category:'clothing', text:'hat'},
{category:'clothing', text:'headband'},
{category:'clothing', text:'jacket'},
{category:'clothing', text:'jeans'},
{category:'clothing', text:'kneepads'},
{category:'clothing', text:'mittens'},
{category:'clothing', text:'necklace'},
{category:'clothing', text:'overalls'},
{category:'clothing', text:'pajamas'},
{category:'clothing', text:'partyhat'},
{category:'clothing', text:'raincoat'},
{category:'clothing', text:'sandals'},
{category:'clothing', text:'scarf'},
{category:'clothing', text:'shirt'},
{category:'clothing', text:'shoes'},
{category:'clothing', text:'skirt'},
{category:'clothing', text:'slippers'},
{category:'clothing', text:'sneakers'},
{category:'clothing', text:'socks'},
{category:'clothing', text:'sombrero'},
{category:'clothing', text:'stockings'},
{category:'clothing', text:'suit'},
{category:'clothing', text:'sweater'},
{category:'clothing', text:'sweatshirt'},
{category:'clothing', text:'swimsuit'},
{category:'clothing', text:'t-shirt'},
{category:'clothing', text:'tie'},
{category:'clothing', text:'trousers'},
{category:'clothing', text:'underpants'},

{text:'crutches',category:'medical'},
{text:'dandruff',category:'medical'},
{text:'dentures',category:'medical'},
{text:'firstaid',category:'medical'},
{text:'headache',category:'medical'},
{text:'hospital',category:'medical'},
{text:'insomnia',category:'medical'},
{text:'medicine',category:'medical'},
{text:'papercut',category:'medical'},
{text:'seasick',category:'medical'},
{text:'sunburn',category:'medical'},
{text:'vaccine',category:'medical'},
{text:'vitamin',category:'medical'},

{text:'hongkong',category:'geography'},
{text:'scotland',category:'geography'},
{text:'america',category:'geography'},
{text:'atlanta',category:'geography'},
{text:'bahamas',category:'geography'},
{text:'england',category:'geography'},
{text:'finland',category:'geography'},
{text:'florida',category:'geography'},
{text:'germany',category:'geography'},
{text:'holland',category:'geography'},
{text:'ireland',category:'geography'},
{text:'jamaica',category:'geography'},
{text:'new-york',category:'geography'},
{text:'orlando',category:'geography'},

{text:'branches',category:'plant'},
{text:'eggplant',category:'plant'},
{text:'palmtree',category:'plant'},
{text:'pinecone',category:'plant'},
{text:'pinetree',category:'plant'},
{text:'primrose',category:'plant'},
{text:'oaktree',category:'plant'},
{text:'seaweed',category:'plant'},
{text:'bamboo',category:'plant'},
{text:'carrot',category:'plant'},
{text:'celery',category:'plant'},
{text:'cherry',category:'plant'},
{text:'garlic',category:'plant'},
{text:'grapes',category:'plant'},
{text:'cilantro',category:'plant'},

{text:'backbone',category:'anatomy'},
{text:'forehead',category:'anatomy'},
{text:'mustache',category:'anatomy'},
{text:'nosehair',category:'anatomy'},
{text:'shoulder',category:'anatomy'},
{text:'skeleton',category:'anatomy'},
{text:'tentacle',category:'anatomy'},
{text:'whiskers',category:'anatomy'},
{text:'eyeball',category:'anatomy'},
{text:'eyebrow',category:'anatomy'},
{text:'eyelash',category:'anatomy'},
{text:'kneecap',category:'anatomy'},
{text:'knuckle',category:'anatomy'},
{text:'stomach',category:'anatomy'},
{text:'unibrow',category:'anatomy'},

{text:'cemetery',category:'location location location'},
{text:'library',category:'location location location'},
{text:'mansion',category:'location location location'},
{text:'petshop',category:'location location location'},
{text:'theater',category:'location location location'},
{text:'casino',category:'location location location'},
{text:'castle',category:'location location location'},
{text:'church',category:'location location location'},
{text:'circus',category:'location location location'},
{category:'location location location', text:'airport'},
{category:'location location location', text:'apartment building'},
{category:'location location location', text:'bank'},
{category:'location location location', text:'barber shop'},
{category:'location location location', text:'barn'},
{category:'location location location', text:'book store'},
{category:'location location location', text:'bowling alley'},
{category:'location location location', text:'bus stop'},
{category:'location location location', text:'cathedral'},
{category:'location location location', text:'convenience store'},
{category:'location location location', text:'courthouse'},
{category:'location location location', text:'department store'},
{category:'location location location', text:'disco'},
{category:'location location location', text:'fire department'},
{category:'location location location', text:'fire station'},
{category:'location location location', text:'gas station'},
{category:'location location location', text:'hospital'},
{category:'location location location', text:'house'},
{category:'location location location', text:'lighthouse'},
{category:'location location location', text:'mall'},
{category:'location location location', text:'movie theater'},
{category:'location location location', text:'museum'},
{category:'location location location', text:'office building'},
{category:'location location location', text:'opera house'},
{category:'location location location', text:'palace'},
{category:'location location location', text:'police station'},
{category:'location location location', text:'post office'},
{category:'location location location', text:'prison'},
{category:'location location location', text:'restaurant'},
{category:'location location location', text:'saw mill'},
{category:'location location location', text:'school'},
{category:'location location location', text:'supermarket'},
{category:'location location location', text:'temple'},
{category:'location location location', text:'train station'},

{text:'Rowboat',category:'Transportation'},
{text:'Shuttle',category:'Transportation'},
{text:'Airplane',category:'Transportation'},
{text:'Forklift',category:'Transportation'},
{text:'Golf Cart',category:'Transportation'},
{text:'Sail Soat',category:'Transportation'},
{text:'Tow Truck',category:'Transportation'},
{text:'Tricycle',category:'Transportation'},
{text:'Zeppelin',category:'Transportation'},
{text:'Bicycle',category:'Transportation'},
{text:'Dog Sled',category:'Transportation'},
{text:'Minivan',category:'Transportation'},
{text:'Porsche',category:'Transportation'},
{text:'Scooter',category:'Transportation'},
{text:'Tractor',category:'Transportation'},
{text:'Tugboat',category:'Transportation'},
{text:'Rickshaw',category:'Transportation'},
{text:'Formula One',category:'Transportation'},
{text:'Train',category:'Transportation'},
{text:'Steam Boat',category:'Transportation'},
{text:'Bicycle',category:'Transportation'},
{text:'Unicycle',category:'Transportation'},
{text:'Ocean Liner',category:'Transportation'},
{text:'Submarine',category:'Transportation'},
{text:'Yacht',category:'Transportation'},
{text:'Helicopter',category:'Transportation'},
{text:'Hoverboard',category:'Transportation'},
{text:'Stagecoach',category:'Transportation'},
{text:'Daftpunk',category:'Music Band'},
{text:'Skrillex',category:'Music Band'},
{text:'Beatles',category:'Music Band'},
{text:'Beyonce',category:'Music Band'},
{text:'Bon Jovi',category:'Music Band'},
{text:'Nirvana',category:'Music Band'},
{text:'Guns And Roses',category:'Music Band'},
{text:'Justin Bieber',category:'Music Band'},
{text:'Billie Eilish',category:'Music Band'},
{text:'Pink Floyd',category:'Music Band'},
{text:'Lady Gaga',category:'Music Band'},
{text:'Muse',category:'Music Band'},
{text:'AC/DC',category:'Music Band'},
{text:'The Black Eyed Peas',category:'Music Band'},
{text:'U2',category:'Music Band'},
{text:'Drake',category:'Music Band'},
{text:'Ed Shiran',category:'Music Band'},
{text:'Nicki Minaj',category:'Music Band'},
{text:'Eminem',category:'Music Band'},
{text:'Taylor Swift',category:'Music Band'},
{text:'Queen',category:'Music Band'},
{text:'Adele',category:'Music Band'},
{text:'Rihana',category:'Music Band'},
{text:'Coldplay',category:'Music Band'},
{text:'Katy Perry',category:'Music Band'},
{text:'Kanye West',category:'Music Band'},
{text:'Childish Gambino',category:'Music Band'},
{text:'Mariah Carey',category:'Music Band'},
{text:'Justin Timberlake',category:'Music Band'},
{text:'Bruno Mars',category:'Music Band'},
{text:'Led Zeppelin',category:'Music Band'},
{text:'Michael Jackson',category:'Music Band'},
{text:'Tupac Shakur',category:'Music Band'},
{text:'Pitbull',category:'Music Band'},
{text:'Snoop dogg',category:'Music Band'},
{text:'Dr. Dre',category:'Music Band'},
{text:'Jay Z',category:'Music Band'},

{text:'Dubstep',category:'Music Genre'},
{text:'House',category:'Music Genre'},
{text:'Rock',category:'Music Genre'},
{text:'Hip Hop',category:'Music Genre'},
{text:'Blues',category:'Music Genre'},
{text:'Pop',category:'Music Genre'},
{text:'Jazz',category:'Music Genre'},
{text:'Classical',category:'Music Genre'},
{text:'R&B',category:'Music Genre'},
{text:'Heavy Metal',category:'Music Genre'},
{text:'Punk',category:'Music Genre'},
{text:'Country',category:'Music Genre'},
{text:'Reggae',category:'Music Genre'},
{text:'Elevator Music',category:'Music Genre'},
{text:'Disco',category:'Music Genre'},
{text:'Techno',category:'Music Genre'},
{text:'J-Pop',category:'Music Genre'},
{text:'Grunge',category:'Music Genre'},
{text:'Rap',category:'Music Genre'},
{text:'Swing',category:'Music Genre'},

{text:'Bagpipes',category:'Musical Instrument'},
{text:'Bass Guitar',category:'Musical Instrument'},
{text:'Jukebox',category:'Musical Instrument'},
{text:'Trombone',category:'Musical Instrument'},
{text:'Drums',category:'Musical Instrument'},
{text:'Ukulele',category:'Musical Instrument'},
{text:'Electric Guitar',category:'Musical Instrument'},
{text:'Piano',category:'Musical Instrument'},
{text:'Violin',category:'Musical Instrument'},
{text:'Saxophone',category:'Musical Instrument'},
{text:'Cello',category:'Musical Instrument'},
{text:'Flute',category:'Musical Instrument'},
{text:'Clarinet',category:'Musical Instrument'},
{text:'Trumpet',category:'Musical Instrument'},
{text:'Harmonica',category:'Musical Instrument'},
{text:'Harp',category:'Musical Instrument'},
{text:'Banjo',category:'Musical Instrument'},
{text:'Castanets',category:'Musical Instrument'},
{text:'Kazoo',category:'Musical Instrument'},
{text:'Cowbell',category:'Musical Instrument'},
{text:'Cymbal',category:'Musical Instrument'},
{text:'Gong',category:'Musical Instrument'},
{text:'Maraca',category:'Musical Instrument'},
{text:'Marimba',category:'Musical Instrument'},
{text:'Tambourine',category:'Musical Instrument'},
{text:'Triangle',category:'Musical Instrument'},
{text:'Washboard',category:'Musical Instrument'},
{text:'Xylophone',category:'Musical Instrument'},
{text:'Accordion',category:'Musical Instrument'},
{text:'Horn',category:'Musical Instrument'},
{text:'Bugle',category:'Musical Instrument'},
{text:'Didgeridoo',category:'Musical Instrument'},
{text:'Oboe',category:'Musical Instrument'},
{text:'Ocarina',category:'Musical Instrument'},
{text:'Piccolo',category:'Musical Instrument'},
{text:'Whistle',category:'Musical Instrument'},
{text:'Tuba',category:'Musical Instrument'},
{text:'Sitar',category:'Musical Instrument'},
{text:'Fiddle',category:'Musical Instrument'},
{text:'Lute',category:'Musical Instrument'},

{text:'Griffin',category:'mythology'},
{text:'Minotaur',category:'mythology'},
{text:'Bigfoot',category:'mythology'},
{text:'Chimera',category:'mythology'},
{text:'Cyclop',category:'mythology'},
{text:'Centaur',category:'mythology'},
{text:'Mermaid',category:'mythology'},
{text:'Pegasus',category:'mythology'},
{text:'Phoenix',category:'mythology'},
{text:'Unicorn',category:'mythology'},
{text:'Vampire',category:'mythology'},
{text:'Dragon',category:'mythology'},
{text:'Dryad',category:'mythology'},
{text:'Ghost',category:'mythology'},
{text:'Medusa',category:'mythology'},
{text:'Manticore',category:'mythology'},
{text:'Satyr',category:'mythology'},
{text:'Sphinx',category:'mythology'},
{text:'Werewolf',category:'mythology'},
{text:'Zombie',category:'mythology'},
{text:'Mummy',category:'mythology'},
{text:'Golem',category:'mythology'},
{text:'Amazon Warrior',category:'mythology'},
{text:'Lizard People',category:'mythology'},
{text:'Basilisk',category:'mythology'},
{text:'Goblin',category:'mythology'},
{text:'Fairy',category:'mythology'},
{text:'Ghoul',category:'mythology'},
{text:'Imp',category:'mythology'},
{text:'Troll',category:'mythology'},
{text:'Ogre',category:'mythology'},
{text:'Nymph',category:'mythology'},
{text:'Giant',category:'mythology'},
{text:'Elf',category:'mythology'},

{text:'angelina jolie',category:'famous person'},
{text:'bob dylan',category:'famous person'},
{text:'brad pitt',category:'famous person'},
{text:'bruce lee',category:'famous person'},
{text:'geronimo',category:'famous person'},
{text:'greenday',category:'famous person'},
{text:'kate moss',category:'famous person'},
{text:'lady gaga',category:'famous person'},
{text:'lil wayne',category:'famous person'},
{text:'ludacris',category:'famous person'},
{text:'mc hammer',category:'famous person'},
{text:'tom hanks',category:'famous person'},
{text:'beckham',category:'famous person'},
{text:'colbert',category:'famous person'},
{text:'jay leno',category:'famous person'},
{text:'lincoln',category:'famous person'},
{text:'picasso',category:'famous person'},
{text:'rihanna',category:'famous person'},
{text:'van gogh',category:'famous person'},
{text:'justin bieber',category:'famous person'},
{text:'eminem',category:'famous person'},
{text:'gandhi',category:'famous person'},
{text:'madonna',category:'famous person'},
{text:'pitbull',category:'famous person'},

{text:'baseball',category:'sports'},
{text:'dumbbell',category:'sports'},
{text:'football',category:'sports'},
{text:'goal post',category:'sports'},
{text:'golf club',category:'sports'},
{text:'half pipe',category:'sports'},
{text:'handball',category:'sports'},
{text:'iceskate',category:'sports'},
{text:'jumprope',category:'sports'},
{text:'longjump',category:'sports'},
{text:'minigolf',category:'sports'},
{text:'olympics',category:'sports'},
{text:'pingpong',category:'sports'},
{text:'slamdunk',category:'sports'},
{text:'sledding',category:'sports'},
{text:'swimming',category:'sports'},
{text:'archery',category:'sports'},
{text:'bowling',category:'sports'},
{text:'fencing',category:'sports'},
{text:'fishing',category:'sports'},
{text:'frisbee',category:'sports'},
{text:'homerun',category:'sports'},
{text:'javelin',category:'sports'},
{text:'rebound',category:'sports'},
{text:'referee',category:'sports'},
{text:'boxing',category:'sports'},

{text:'haymitch',category:'pop culture'},
{text:'autobots',category:'pop culture'},
{text:'avengers',category:'pop culture'},
{text:'catwoman',category:'pop culture'},
{text:'garfield',category:'pop culture'},
{text:'iron chef',category:'pop culture'},
{text:'lion king',category:'pop culture'},
{text:'splinter',category:'pop culture'},
{text:'startrek',category:'pop culture'},
{text:'starwars',category:'pop culture'},
{text:'superman',category:'pop culture'},
{text:'aladdin',category:'pop culture'},
{text:'aquaman',category:'pop culture'},
{text:'asterix',category:'pop culture'},
{text:'hawkeye',category:'pop culture'},
{text:'katniss',category:'pop culture'},
{text:'metroid',category:'pop culture'},
{text:'pikachu',category:'pop culture'},
{text:'riddler',category:'pop culture'},
{text:'rugrats',category:'pop culture'},
{text:'twoface',category:'pop culture'},
{text:'avatar',category:'pop culture'},
{text:'barbie',category:'pop culture'},
{text:'batman',category:'pop culture'},
{text:'beavis',category:'pop culture'},
{text:'bowser',category:'pop culture'},

{text:'assassin',category:'profession'},
{text:'director',category:'profession'},
{text:'gangster',category:'profession'},
{text:'gardener',category:'profession'},
{text:'magician',category:'profession'},
{text:'princess',category:'profession'},
{text:'waitress',category:'profession'},
{text:'wrestler',category:'profession'},
{text:'butcher',category:'profession'},
{text:'captain',category:'profession'},
{text:'cashier',category:'profession'},
{text:'cowgirl',category:'profession'},
{text:'dentist',category:'profession'},
{text:'drummer',category:'profession'},
{text:'gymnast',category:'profession'},
{text:'mailman',category:'profession'},
{text:'milkman',category:'profession'},
{text:'painter',category:'profession'},
{text:'plumber',category:'profession'},
{text:'poolboy',category:'profession'},
{text:'sheriff',category:'profession'},
{text:'soldier',category:'profession'},
{text:'surgeon',category:'profession'},
{text:'teacher',category:'profession'},
{text:'warrior',category:'profession'},
{text:'artist',category:'profession'},
{text:'barber',category:'profession'},
{text:'cowboy',category:'profession'},
{text:'doctor',category:'profession'},
{text:'farmer',category:'profession'},

{category:'animal', text:'aardvark'},
{category:'animal', text:'ant'},
{category:'animal', text:'anteater'},
{category:'animal', text:'armadillo'},
{category:'animal', text:'baboon'},
{category:'animal', text:'badger'},
{category:'animal', text:'bear'},
{category:'animal', text:'beaver'},
{category:'animal', text:'bee'},
{category:'animal', text:'bird'},
{category:'animal', text:'bull'},
{category:'animal', text:'calf'},
{category:'animal', text:'camel'},
{category:'animal', text:'cat'},
{category:'animal', text:'cheetah'},
{category:'animal', text:'chicken'},
{category:'animal', text:'chimpanzee'},
{category:'animal', text:'cow'},
{category:'animal', text:'crane'},
{category:'animal', text:'crocodile'},
{category:'animal', text:'deer'},
{category:'animal', text:'dinosaur'},
{category:'animal', text:'dog'},
{category:'animal', text:'dolphin'},
{category:'animal', text:'donkey'},
{category:'animal', text:'duck'},
{category:'animal', text:'eagle'},
{category:'animal', text:'elephant'},
{category:'animal', text:'fish'},
{category:'animal', text:'flamingo'},
{category:'animal', text:'fly'},
{category:'animal', text:'fox'},
{category:'animal', text:'frog'},
{category:'animal', text:'giraffe'},
{category:'animal', text:'goat'},
{category:'animal', text:'goldfish'},
{category:'animal', text:'gorilla'},
{category:'animal', text:'hamster'},
{category:'animal', text:'hippopotamus'},
{category:'animal', text:'horse'},
{category:'animal', text:'hyena'},
{category:'animal', text:'jaguar'},
{category:'animal', text:'kangaroo'},
{category:'animal', text:'kitten'},
{category:'animal', text:'ladybug'},
{category:'animal', text:'leopard'},
{category:'animal', text:'lion'},
{category:'animal', text:'lizard'},
{category:'animal', text:'llama'},
{category:'animal', text:'lobster'},
{category:'animal', text:'mammoth'},
{category:'animal', text:'monkey'},
{category:'animal', text:'mosquito'},
{category:'animal', text:'narwhal'},
{category:'animal', text:'octopus'},
{category:'animal', text:'ostrich'},
{category:'animal', text:'otter'},
{category:'animal', text:'owl'},
{category:'animal', text:'oyster'},
{category:'animal', text:'panda'},
{category:'animal', text:'panther'},
{category:'animal', text:'parrot'},
{category:'animal', text:'peacock'},
{category:'animal', text:'pelican'},
{category:'animal', text:'penguin'},
{category:'animal', text:'pig'},
{category:'animal', text:'pigeon'},
{category:'animal', text:'porcupine'},
{category:'animal', text:'puppy'},
{category:'animal', text:'rabbit'},
{category:'animal', text:'raccoon'},
{category:'animal', text:'rat'},
{category:'animal', text:'reindeer'},
{category:'animal', text:'rhinoceros'},
{category:'animal', text:'rooster'},
{category:'animal', text:'scorpion'},
{category:'animal', text:'seagull'},
{category:'animal', text:'seahorse'},
{category:'animal', text:'seal'},
{category:'animal', text:'shark'},
{category:'animal', text:'sheep'},
{category:'animal', text:'shrimp'},
{category:'animal', text:'snail'},
{category:'animal', text:'snake'},
{category:'animal', text:'spider'},
{category:'animal', text:'squid'},
{category:'animal', text:'squirrel'},
{category:'animal', text:'starfish'},
{category:'animal', text:'stork'},
{category:'animal', text:'swan'},
{category:'animal', text:'tadpole'},
{category:'animal', text:'tiger'},
{category:'animal', text:'toad'},
{category:'animal', text:'tropical fish'},
{category:'animal', text:'tuna'},
{category:'animal', text:'turkey'},
{category:'animal', text:'turtle'},
{category:'animal', text:'vulture'},
{category:'animal', text:'walrus'},
{category:'animal', text:'whale'},
{category:'animal', text:'wolf'},
{category:'animal', text:'zebra'},
{category:'animal', text:'reptile'},
{category:'animal', text:'buffalo'},
{category:'animal', text:'tortoise'},
{category:'animal', text:'catfish'},
{category:'animal', text:'firefly'},
{category:'animal', text:'dragonfly'},
{category:'animal', text:'pitbull'},

{text:'banana',category:'food'},
{text:'baguette',category:'food'},
{text:'barbeque',category:'food'},
{text:'broccoli',category:'food'},
{text:'espresso',category:'food'},
{text:'fast food',category:'food'},
{text:'frosting',category:'food'},
{text:'hot sauce',category:'food'},
{text:'junk food',category:'food'},
{text:'lollipop',category:'food'},
{text:'macaroni',category:'food'},
{text:'meatballs',category:'food'},
{text:'mushroom',category:'food'},
{text:'pancakes',category:'food'},
{text:'popsicle',category:'food'},
{text:'sandwich',category:'food'},
{text:'skittles',category:'food'},
{text:'snowcone',category:'food'},
{text:'soysauce',category:'food'},
{text:'avocado',category:'food'},
{text:'brownie',category:'food'},
{text:'burrito',category:'food'},
{text:'coconut',category:'food'},
{text:'cookies',category:'food'},
{text:'corndog',category:'food'},
{text:'cupcake',category:'food'},
{text:'doritos',category:'food'},
{text:'eggroll',category:'food'},
{text:'hambone',category:'food'},
{text:'hamwich',category:'food'},
{text:'ketchup',category:'food'},
{text:'mustard',category:'food'},
{text:'noodles',category:'food'},
{text:'oatmeal',category:'food'},
{text:'pancake',category:'food'},
{text:'peaches',category:'food'},
{text:'popcorn',category:'food'},
{text:'pretzel',category:'food'},
{text:'pumpkin',category:'food'},
{text:'sausage',category:'food'},
{text:'seafood',category:'food'},
{text:'spinach',category:'food'},
{text:'twinkie',category:'food'},
{text:'cereal',category:'food'},
{text:'cheese',category:'food'},
{text:'coffee',category:'food'},
{text:'cookie',category:'food'},
{text:'lemonade',category:'food'},
{text:'smoothie',category:'food'},
{text:'martini',category:'food'},
{text:'sixpack',category:'food'},
{text:'tequila',category:'food'},
{text:'whiskey',category:'food'},

{text:'Horror',category:'Film Genres'},
{text:'Action',category:'Film Genres'},
{text:'Thriller',category:'Film Genres'},
{text:'Sci-Fi',category:'Film Genres'},
{text:'Rom-Com',category:'Film Genres'},
{text:'Western',category:'Film Genres'},
{text:'Comedy',category:'Film Genres'},
{text:'Gangster',category:'Film Genres'},
{text:'Slapstick',category:'Film Genres'},
{text:'War',category:'Film Genres'},
{text:'Documentry',category:'Film Genres'},
{text:'Mockumentry',category:'Film Genres'},
{text:'Musical',category:'Film Genres'},
{text:'Animation',category:'Film Genres'},
{text:'Disasters',category:'Film Genres'},
{text:'Zombies',category:'Film Genres'},
{text:'Sport',category:'Film Genres'},

{text:'Toy Story',category:'Movies'},
{text:'Jaws',category:'Movies'},
{text:'Mission Impossible',category:'Movies'},
{text:'Wonder Woman',category:'Movies'},
{text:'Scarface',category:'Movies'},
{text:'Mary Poppins',category:'Movies'},
{text:'E.T.',category:'Movies'},
{text:'King Kong',category:'Movies'},
{text:'Star Wars',category:'Movies'},
{text:'Alien',category:'Movies'},
{text:'Pulp Fiction',category:'Movies'},
{text:'Lion King',category:'Movies'},
{text:'Die Hard',category:'Movies'},
{text:'The Shawshank Redemption',category:'Movies'},
{text:'Rocky Horror Picture Show',category:'Movies'},
{text:'Rocky',category:'Movies'},
{text:'The Wizard of Oz',category:'Movies'},
{text:'Gone with The Wind',category:'Movies'},
{text:'Forrest Gump',category:'Movies'},
{text:'West Side Story',category:'Movies'},
{text:'The Lord Of the Rings',category:'Movies'},
{text:'Gladiator',category:'Movies'},
{text:'Titanic',category:'Movies'},
{text:'Saving Private Ryan',category:'Movies'},
{text:'Indiana Jones',category:'Movies'},
{text:'A Clockwork Orange',category:'Movies'},
{text:'The Good, the Bad and the Ugly',category:'Movies'},
{text:'Braveheart',category:'Movies'},
{text:'Jurassic Park',category:'Movies'},
{text:'Home Alone',category:'Movies'},
{text:'Shrek',category:'Movies'},
{text:'The Matrix',category:'Movies'},
{text:'Finding Nemo',category:'Movies'},
{text:'Princess Bride',category:'Movies'},
{text:'Fargo',category:'Movies'},
{text:'The Green Mile',category:'Movies'},
{text:'Back to the Future',category:'Movies'},
{text:'The Social Network',category:'Movies'},
{text:'Golden Eye',category:'Movies'},
{text:'Minority Report',category:'Movies'},
{text:'Groundhog Day',category:'Movies'},
{text:'Inception',category:'Movies'},
{text:'Austin Powers',category:'Movies'},
{text:'Inglourious Basterds',category:'Movies'},
{text:'Monty Python and the Holy Grail',category:'Movies'},

]