words_en = [
    { text: 'grandma', category: 'Family' },
    { text: 'grandpa', category: 'Family' },
    { text: 'husband', category: 'Family' },
    { text: 'parents', category: 'Family' },
    { text: 'wife', category: 'Family' },
    { text: 'uncle', category: 'Family' },
    { text: 'aunt', category: 'Family' },
    { text: 'father', category: 'Family' },
    { text: 'mother', category: 'Family' },
    { text: 'step sister', category: 'Family' },
    { text: 'step brother', category: 'Family' },
    { text: 'step father', category: 'Family' },
    { text: 'step mother', category: 'Family' },
    { text: 'god father', category: 'Family' },
    { text: 'god mother', category: 'Family' },
    { text: 'mother in law', category: 'Family' },
    { text: 'father in law', category: 'Family' },
    { text: 'children', category: 'Family' },
    { text: 'brother', category: 'Family' },
    { text: 'sister', category: 'Family' },
    { text: 'cousin', category: 'Family' },
    { text: 'granddaugther', category: 'Family' },
    { text: 'grandson', category: 'Family' },
    { text: 'niece', category: 'Family' },
    { text: 'nephew', category: 'Family' },

    { text: 'festivus', category: 'Festivity' },
    { text: 'hanukkah', category: 'Festivity' },
    { text: 'kwanzaa', category: 'Festivity' },
    { text: 'wedding', category: 'Festivity' },
    { text: 'birthday', category: 'Festivity' },
    { text: 'bar mitzvah', category: 'Festivity' },
    { text: 'halloween', category: 'Festivity' },
    { text: 'octoberfest', category: 'Festivity' },
    { text: 'christmas', category: 'Festivity' },
    { text: 'Día de Muertos', category: 'Festivity' },
    { text: 'new year`s eve', category: 'Festivity' },
    { text: 'groundhog day', category: 'Festivity' },
    { text: 'Valentine`s Day', category: 'Festivity' },
    { text: 'St. Patrick`s Day', category: 'Festivity' },
    { text: 'passover', category: 'Festivity' },
    { text: 'easter', category: 'Festivity' },
    { text: 'Ramadan', category: 'Festivity' },
    { text: 'Mother`s Day', category: 'Festivity' },
    { text: 'Independence Day', category: 'Festivity' },
    { text: 'Columbus Day', category: 'Festivity' },
    { text: 'Divali', category: 'Festivity' },
    { text: 'Black Friday', category: 'Festivity' },
    { text: 'thanks giving', category: 'Festivity' },
    { text: 'election', category: 'Festivity' },
    { text: 'Graduation', category: 'Festivity' },

    { text: 'bracelet', category: 'Valuables' },
    { text: 'crystal', category: 'Valuables' },
    { text: 'diamond', category: 'Valuables' },
    { text: 'emerald', category: 'Valuables' },
    { text: 'jewelry', category: 'Valuables' },
    { text: 'gold bar', category: 'Valuables' },
    { text: 'pearls', category: 'Valuables' },

    { text: 'bromance', category: 'Social' },
    { text: 'follower', category: 'Social' },
    { text: 'highfive', category: 'Social' },
    { text: 'marriage', category: 'Social' },
    { text: 'divorce', category: 'Social' },
    { text: 'frenemy', category: 'Social' },

    { text: 'hulahoop', category: 'Games' },
    { text: 'pinwheel', category: 'Games' },
    { text: 'swingset', category: 'Games' },
    { text: 'balloon', category: 'Games' },
    { text: 'dreidel', category: 'Games' },
    { text: 'gameboy', category: 'Games' },

    { text: 'pinball', category: 'Games' },
    { text: 'checkers', category: 'Games' },
    { text: 'joystick', category: 'Games' },
    { text: 'monopoly', category: 'Games' },
    { text: 'scrabble', category: 'Games' },
    { text: 'yahtzee', category: 'Games' },

    { text: 'Chair', category: 'Furniture' },
    { text: 'barstool', category: 'Furniture' },
    { text: 'bookcase', category: 'Furniture' },
    { text: 'waterbed', category: 'Furniture' },
    { text: 'bathtub', category: 'Furniture' },
    { text: 'bunkbed', category: 'Furniture' },
    { text: 'cabinet', category: 'Furniture' },
    { text: 'dresser', category: 'Furniture' },
    { text: 'Bed', category: 'Furniture' },

    { text: 'chainsaw', category: 'Tool' },
    { text: 'scissors', category: 'Tool' },
    { text: 'tweezers', category: 'Tool' },
    { text: 'compass', category: 'Tool' },
    { text: 'crowbar', category: 'Tool' },
    { text: 'dustpan', category: 'Tool' },
    { text: 'stapler', category: 'Tool' },

    { text: 'lipstick', category: 'Toiletries' },
    { text: 'perfume', category: 'Toiletries' },
    { text: 'shampoo', category: 'Toiletries' },
    { text: 'nailfile', category: 'Toiletries' },
    { text: 'sunblock', category: 'Toiletries' },
    { text: 'hairdye', category: 'Toiletries' },
    { text: 'hairgel', category: 'Toiletries' },
    { text: 'mascara', category: 'Toiletries' },

    { text: 'computer', category: 'Computing' },
    { text: 'facebook', category: 'Computing' },
    { text: 'firewall', category: 'Computing' },
    { text: 'keyboard', category: 'Computing' },
    { text: 'password', category: 'Computing' },
    { text: 'hashtag', category: 'Computing' },
    { text: 'macbook', category: 'Computing' },
    { text: 'twitter', category: 'Computing' },

	{ category: 'Weapon', text: 'Battle Axe' },
	{ category: 'Weapon', text: 'bayonet' },
	{ category: 'Weapon', text: 'bazooka' },
	{ category: 'Weapon', text: 'cannon' },
	{ category: 'Weapon', text: 'catapult' },
	{ category: 'Weapon', text: 'crossbow' },
	{ category: 'Weapon', text: 'dynamite' },
	{ category: 'Weapon', text: 'handgun' },
	{ category: 'Weapon', text: 'missile' },
	{ category: 'Weapon', text: 'shotgun' },
	{ category: 'Weapon', text: 'Sword' },
	{ category: 'Weapon', text: 'torpedo' },
	{ category: 'Weapon', text: 'Warhammer'},

    { text: 'eyepatch', category: 'Accessory' },
    { text: 'headband', category: 'Accessory' },
    { text: 'kneepads', category: 'Accessory' },
    { text: 'necklace', category: 'Accessory' },
    { text: 'nosering', category: 'Accessory' },
    { text: 'partyhat', category: 'Accessory' },
    { text: 'shoelace', category: 'Accessory' },
    { text: 'umbrella', category: 'Accessory' },
    { text: 'bandana', category: 'Accessory' },
    { text: 'earring', category: 'Accessory' },
    { text: 'hairtie', category: 'Accessory' },
    { text: 'handbag', category: 'Accessory' },
	{ category: 'Accessory', text: 'Handkerchief' },

    { category: 'Clothing', text: 'Chasity Belt' },
    { category: 'Clothing ', text: 'Tophat' },
    { category: 'Clothing', text: 'pantsuit' },
    { category: 'Clothing', text: 'bandana' },
    { category: 'Clothing', text: 'belt' },
    { category: 'Clothing', text: 'bikini' },
    { category: 'Clothing', text: 'boots' },
    { category: 'Clothing', text: 'bowtie' },
	{ category: 'Clothing', text: 'Tophat' },
	{ category: 'Clothing', text: 'Cowboy Hat' },
    { category: 'Clothing', text: 'cap' },
    { category: 'Clothing', text: 'coat' },
    { category: 'Clothing', text: 'dress' },
    { category: 'Clothing', text: 'earmuffs' },
    { category: 'Clothing', text: 'eyepatch' },
    { category: 'Clothing', text: 'glasses' },
    { category: 'Clothing', text: 'gloves' },
    { category: 'Clothing', text: 'hairtie' },
	{ category: 'Clothing', text: 'Hoodie' },
    { category: 'Clothing', text: 'hat' },
    { category: 'Clothing', text: 'headband' },
    { category: 'Clothing', text: 'jacket' },
    { category: 'Clothing', text: 'jeans' },
    { category: 'Clothing', text: 'kneepads' },
    { category: 'Clothing', text: 'mittens' },
    { category: 'Clothing', text: 'necklace' },
    { category: 'Clothing', text: 'overalls' },
    { category: 'Clothing', text: 'pajamas' },
    { category: 'Clothing', text: 'partyhat' },
    { category: 'Clothing', text: 'raincoat' },
    { category: 'Clothing', text: 'sandals' },
    { category: 'Clothing', text: 'scarf' },
    { category: 'Clothing', text: 'shirt' },
    { category: 'Clothing', text: 'shoes' },
    { category: 'Clothing', text: 'skirt' },
    { category: 'Clothing', text: 'slippers' },
    { category: 'Clothing', text: 'sneakers' },
    { category: 'Clothing', text: 'socks' },
    { category: 'Clothing', text: 'sombrero' },
    { category: 'Clothing', text: 'stockings' },
    { category: 'Clothing', text: 'suit' },
    { category: 'Clothing', text: 'sweater' },
    { category: 'Clothing', text: 'sweatshirt' },
    { category: 'Clothing', text: 'swimsuit' },
    { category: 'Clothing', text: 't-shirt' },
    { category: 'Clothing', text: 'tie' },
    { category: 'Clothing', text: 'trousers' },
    { category: 'Clothing', text: 'underpants' },

    { text: 'crutches', category: 'Medical' },
    { text: 'dandruff', category: 'Medical' },
    { text: 'dentures', category: 'Medical' },
    { text: 'firstaid', category: 'Medical' },
    { text: 'headache', category: 'Medical' },
    { text: 'hospital', category: 'Medical' },
    { text: 'insomnia', category: 'Medical' },
    { text: 'medicine', category: 'Medical' },
    { text: 'papercut', category: 'Medical' },
    { text: 'seasick', category: 'Medical' },
    { text: 'sunburn', category: 'Medical' },
    { text: 'vaccine', category: 'Medical' },
    { text: 'vitamin', category: 'Medical' },

    { text: 'hongkong', category: 'Geography' },
    { text: 'scotland', category: 'Geography' },
    { text: 'america', category: 'Geography' },
    { text: 'atlanta', category: 'Geography' },
    { text: 'bahamas', category: 'Geography' },
    { text: 'england', category: 'Geography' },
    { text: 'finland', category: 'Geography' },
    { text: 'florida', category: 'Geography' },
    { text: 'germany', category: 'Geography' },
    { text: 'holland', category: 'Geography' },
    { text: 'ireland', category: 'Geography' },
    { text: 'jamaica', category: 'Geography' },
    { text: 'new-york', category: 'Geography' },
    { text: 'orlando', category: 'Geography' },

    { text: 'Cabbage', category: 'Plant' },
    { text: 'Persimmon', category: 'Plant' },
    { text: 'Cucumber', category: 'Plant' },
    { text: 'Zucchini', category: 'Plant' },
    { text: 'Watermelon', category: 'Plant' },
    { text: 'Mango', category: 'Plant' },
    { text: 'Lemon', category: 'Plant' },
    { text: 'Lime', category: 'Plant' },
    { text: 'Potato', category: 'Plant' },
    { text: 'Cactus', category: 'Plant' },
    { text: 'Tomato', category: 'Plant' },
    { text: 'Eggplant', category: 'Plant' },
    { text: 'Palmtree', category: 'Plant' },
    { text: 'Pinecone', category: 'Plant' },
    { text: 'Pinetree', category: 'Plant' },
    { text: 'Primrose', category: 'Plant' },
    { text: 'Oak', category: 'Plant' },
    { text: 'Seaweed', category: 'Plant' },
    { text: 'Bamboo', category: 'Plant' },
    { text: 'Carrot', category: 'Plant' },
    { text: 'Celery', category: 'Plant' },
    { text: 'Cherry', category: 'Plant' },
    { text: 'Garlic', category: 'Plant' },
    { text: 'Grapes', category: 'Plant' },
    { text: 'Cilantro', category: 'Plant' },
    { text: 'Banana', category: 'Plant' },
    { text: 'Broccoli', category: 'Plant' },
    { text: 'Avocado', category: 'Plant' },
    { text: 'Coconut', category: 'Plant' },
    { text: 'Peaches', category: 'Plant' },
    { text: 'Spinach', category: 'Plant' },
    { text: 'Pineapple', category: 'Plant' },
    { text: 'Wheat', category: 'Plant' },
    { text: 'Orange', category: 'Plant' },

    { text: 'backbone', category: 'Anatomy' },
    { text: 'forehead', category: 'Anatomy' },
    { text: 'mustache', category: 'Anatomy' },
    { text: 'nosehair', category: 'Anatomy' },
    { text: 'shoulder', category: 'Anatomy' },
    { text: 'skeleton', category: 'Anatomy' },
    { text: 'tentacle', category: 'Anatomy' },
    { text: 'whiskers', category: 'Anatomy' },
    { text: 'eyeball', category: 'Anatomy' },
    { text: 'eyebrow', category: 'Anatomy' },
    { text: 'eyelash', category: 'Anatomy' },
    { text: 'kneecap', category: 'Anatomy' },
    { text: 'knuckle', category: 'Anatomy' },
    { text: 'stomach', category: 'Anatomy' },
    { text: 'unibrow', category: 'Anatomy' },

    { category: 'Location', text: 'Airport' },
    { category: 'Location', text: 'Apartment Building' },
    { category: 'Location', text: 'Bank' },
    { category: 'Location', text: 'Barber Shop' },
	{ category: 'Location', text: 'Bar' },
    { category: 'Location', text: 'Barn' },
	{ category: 'Location', text: 'Beach' },
    { category: 'Location', text: 'Book Store' },
    { category: 'Location', text: 'Bowling Alley' },
    { category: 'Location', text: 'Bus Stop' },
	{ category: 'Location', text: 'Casino' },
    { category: 'Location', text: 'Cathedral' },
	{ category: 'Location', text: 'Castle' },
	{ category: 'Location', text: 'Cemetery' },
	{ category: 'Location', text: 'Church' },
	{ category: 'Location', text: 'Circus' },
    { category: 'Location', text: 'Convenience Store' },
    { category: 'Location', text: 'Courthouse' },
	{ category: 'Location', text: 'Desert' },
    { category: 'Location', text: 'Department Store' },
    { category: 'Location', text: 'Disco' },
	{ category: 'Location', text: 'Dungeon' },
    { category: 'Location', text: 'Fire Station' },
	{ category: 'Location', text: 'Garden' },
    { category: 'Location', text: 'Gas Station' },
	{ category: 'Location', text: 'Golf Course' },
    { category: 'Location', text: 'Hospital' },
    { category: 'Location', text: 'House' },
	{ category: 'Location', text: 'Library' },
    { category: 'Location', text: 'Lighthouse' },
	{ category: 'Location', text: 'Mansion' },
    { category: 'Location', text: 'Mall' },
    { category: 'Location', text: 'Movie Theater' },
    { category: 'Location', text: 'Museum' },
    { category: 'Location', text: 'Office Building' },
    { category: 'Location', text: 'Opera House' },
	{ category: 'Location', text: 'Orchard' },
    { category: 'Location', text: 'Palace' },
	{ category: 'Location', text: 'Petshop' },
    { category: 'Location', text: 'Police Station' },
    { category: 'Location', text: 'Post Office' },
	{ category: 'Location', text: 'Prison' },
	{ category: 'Location', text: 'Pub' },
    { category: 'Location', text: 'Restaurant' },
	{ category: 'Location', text: 'Safari' },
    { category: 'Location', text: 'Saw Mill' },
	{ category: 'Location', text: 'School' },
	{ category: 'Location', text: 'Skyscraper' },
    { category: 'Location', text: 'Supermarket' },
	{ category: 'Location', text: 'Swimming Pool' },
    { category: 'Location', text: 'Temple' },
    { category: 'Location', text: 'Train Station' },
	{ category: 'Location', text: 'Theater' },
	{ category: 'Location', text: 'Theme Park' },
	{ category: 'Location', text: 'Vet Clinic' },
	{ category: 'Location', text: 'Zoo' },

    { text: 'Airplane', category: 'Transportation' },
    { text: 'Bicycle', category: 'Transportation' },
	{ text: 'Bus', category: 'Transportation' },
	{ text: 'Boat', category: 'Transportation' },
    { text: 'Dog Sled', category: 'Transportation' },
	{ text: 'Double Decker bus', category: 'Transportation' },
    { text: 'F-16', category: 'Transportation' },
    { text: 'Forklift', category: 'Transportation' },
    { text: 'Formula One', category: 'Transportation' },
    { text: 'Golf Cart', category: 'Transportation' },
    { text: 'Helicopter', category: 'Transportation' },
    { text: 'Hoverboard', category: 'Transportation' },
	{ text: 'Ice Cream Truck', category: 'Transportation' },
    { text: 'Jeep', category: 'Transportation' },
    { text: 'Minivan', category: 'Transportation' },
    { text: 'Ocean Liner', category: 'Transportation' },
    { text: 'Rickshaw', category: 'Transportation' },
    { text: 'Rocketship', category: 'Transportation' },
	{ text: 'Rowboat', category: 'Transportation' },
    { text: 'Sail Soat', category: 'Transportation' },
    { text: 'Scooter', category: 'Transportation' },
    { text: 'Shuttle', category: 'Transportation' },
	{ text: 'Spaceship', category: 'Transportation' },
	{ text: 'Sports Car', category: 'Transportation' },
    { text: 'Stagecoach', category: 'Transportation' },
    { text: 'Steam Boat', category: 'Transportation' },
    { text: 'Submarine', category: 'Transportation' },
    { text: 'Tractor', category: 'Transportation' },
    { text: 'Train', category: 'Transportation' },
	{ text: 'Tram', category: 'Transportation' },
    { text: 'Tow Truck', category: 'Transportation' },
    { text: 'Tricycle', category: 'Transportation' },
    { text: 'Tugboat', category: 'Transportation' },
    { text: 'Unicycle', category: 'Transportation' },
    { text: 'Yacht', category: 'Transportation' },
    { text: 'Zeppelin', category: 'Transportation' },

	{ text: 'AC/DC', category: 'Music Band' },
    { text: 'Adele', category: 'Music Band' },
    { text: 'Beatles', category: 'Music Band' },
    { text: 'Beyonce', category: 'Music Band' },
    { text: 'Billie Eilish', category: 'Music Band' },
    { text: 'Bon Jovi', category: 'Music Band' },
    { text: 'Bruno Mars', category: 'Music Band' },
    { text: 'Childish Gambino', category: 'Music Band' },
    { text: 'Coldplay', category: 'Music Band' },
	{ text: 'David Bowie', category: 'Music Band' },
    { text: 'Daftpunk', category: 'Music Band' },
    { text: 'Dr. Dre', category: 'Music Band' },
    { text: 'Drake', category: 'Music Band' },
    { text: 'Ed Shiran', category: 'Music Band' },
	{ text: 'Elton John', category: 'Music Band' },
    { text: 'Eminem', category: 'Music Band' },
    { text: 'Guns And Roses', category: 'Music Band' },
    { text: 'Jay Z', category: 'Music Band' },
    { text: 'Justin Bieber', category: 'Music Band' },
    { text: 'Justin Timberlake', category: 'Music Band' },
    { text: 'Kanye West', category: 'Music Band' },
    { text: 'Katy Perry', category: 'Music Band' },
    { text: 'Lady Gaga', category: 'Music Band' },
    { text: 'Led Zeppelin', category: 'Music Band' },
    { text: 'Mariah Carey', category: 'Music Band' },
    { text: 'Michael Jackson', category: 'Music Band' },
    { text: 'Muse', category: 'Music Band' },
    { text: 'Nicki Minaj', category: 'Music Band' },
    { text: 'Nirvana', category: 'Music Band' },
    { text: 'Pink Floyd', category: 'Music Band' },
    { text: 'Pitbull', category: 'Music Band' },
    { text: 'Prince', category: 'Music Band' },
    { text: 'Queen', category: 'Music Band' },
    { text: 'Rihana', category: 'Music Band' },
    { text: 'Skrillex', category: 'Music Band' },
    { text: 'Snoop dogg', category: 'Music Band' },
    { text: 'Taylor Swift', category: 'Music Band' },
    { text: 'The Black Eyed Peas', category: 'Music Band' },
    { text: 'Tupac Shakur', category: 'Music Band' },
    { text: 'U2', category: 'Music Band' },

    { text: 'Dubstep', category: 'Music Genre' },
    { text: 'House', category: 'Music Genre' },
    { text: 'Rock', category: 'Music Genre' },
    { text: 'Hip Hop', category: 'Music Genre' },
    { text: 'Blues', category: 'Music Genre' },
    { text: 'Pop', category: 'Music Genre' },
    { text: 'Jazz', category: 'Music Genre' },
    { text: 'Classical', category: 'Music Genre' },
    { text: 'R&B', category: 'Music Genre' },
    { text: 'Heavy Metal', category: 'Music Genre' },
    { text: 'Punk', category: 'Music Genre' },
    { text: 'Country', category: 'Music Genre' },
    { text: 'Reggae', category: 'Music Genre' },
    { text: 'Elevator Music', category: 'Music Genre' },
    { text: 'Disco', category: 'Music Genre' },
    { text: 'Techno', category: 'Music Genre' },
    { text: 'J-Pop', category: 'Music Genre' },
    { text: 'Grunge', category: 'Music Genre' },
    { text: 'Rap', category: 'Music Genre' },
    { text: 'Swing', category: 'Music Genre' },

    { text: 'Bagpipes', category: 'Musical Instrument' },
    { text: 'Bass Guitar', category: 'Musical Instrument' },
    { text: 'Jukebox', category: 'Musical Instrument' },
    { text: 'Trombone', category: 'Musical Instrument' },
    { text: 'Drums', category: 'Musical Instrument' },
    { text: 'Ukulele', category: 'Musical Instrument' },
    { text: 'Electric Guitar', category: 'Musical Instrument' },
    { text: 'Piano', category: 'Musical Instrument' },
    { text: 'Violin', category: 'Musical Instrument' },
    { text: 'Saxophone', category: 'Musical Instrument' },
    { text: 'Cello', category: 'Musical Instrument' },
    { text: 'Flute', category: 'Musical Instrument' },
    { text: 'Clarinet', category: 'Musical Instrument' },
    { text: 'Trumpet', category: 'Musical Instrument' },
    { text: 'Harmonica', category: 'Musical Instrument' },
    { text: 'Harp', category: 'Musical Instrument' },
    { text: 'Banjo', category: 'Musical Instrument' },
    { text: 'Castanets', category: 'Musical Instrument' },
    { text: 'Kazoo', category: 'Musical Instrument' },
    { text: 'Cowbell', category: 'Musical Instrument' },
    { text: 'Cymbal', category: 'Musical Instrument' },
    { text: 'Gong', category: 'Musical Instrument' },
    { text: 'Maraca', category: 'Musical Instrument' },
    { text: 'Marimba', category: 'Musical Instrument' },
    { text: 'Tambourine', category: 'Musical Instrument' },
    { text: 'Triangle', category: 'Musical Instrument' },
    { text: 'Washboard', category: 'Musical Instrument' },
    { text: 'Xylophone', category: 'Musical Instrument' },
    { text: 'Accordion', category: 'Musical Instrument' },
    { text: 'Horn', category: 'Musical Instrument' },
    { text: 'Bugle', category: 'Musical Instrument' },
    { text: 'Didgeridoo', category: 'Musical Instrument' },
    { text: 'Oboe', category: 'Musical Instrument' },
    { text: 'Ocarina', category: 'Musical Instrument' },
    { text: 'Piccolo', category: 'Musical Instrument' },
    { text: 'Whistle', category: 'Musical Instrument' },
    { text: 'Tuba', category: 'Musical Instrument' },
    { text: 'Sitar', category: 'Musical Instrument' },
    { text: 'Fiddle', category: 'Musical Instrument' },
    { text: 'Lute', category: 'Musical Instrument' },
    
    { text: 'Genie', category: 'Mythology' },
    { text: 'Minotaur', category: 'Mythology' },
    { text: 'Magic Carpet', category: 'Mythology' },
    { text: 'Griffin', category: 'Mythology' },
    { text: 'Minotaur', category: 'Mythology' },
    { text: 'Bigfoot', category: 'Mythology' },
    { text: 'Chimera', category: 'Mythology' },
    { text: 'Cyclop', category: 'Mythology' },
    { text: 'Centaur', category: 'Mythology' },
    { text: 'Mermaid', category: 'Mythology' },
    { text: 'Pegasus', category: 'Mythology' },
    { text: 'Phoenix', category: 'Mythology' },
    { text: 'Unicorn', category: 'Mythology' },
    { text: 'Vampire', category: 'Mythology' },
    { text: 'Dragon', category: 'Mythology' },
    { text: 'Dryad', category: 'Mythology' },
    { text: 'Ghost', category: 'Mythology' },
    { text: 'Medusa', category: 'Mythology' },
    { text: 'Manticore', category: 'Mythology' },
    { text: 'Satyr', category: 'Mythology' },
    { text: 'Sphinx', category: 'Mythology' },
    { text: 'Werewolf', category: 'Mythology' },
    { text: 'Zombie', category: 'Mythology' },
    { text: 'Mummy', category: 'Mythology' },
    { text: 'Golem', category: 'Mythology' },
    { text: 'Amazon Warrior', category: 'Mythology' },
    { text: 'Lizard People', category: 'Mythology' },
    { text: 'Basilisk', category: 'Mythology' },
    { text: 'Goblin', category: 'Mythology' },
    { text: 'Fairy', category: 'Mythology' },
    { text: 'Ghoul', category: 'Mythology' },
    { text: 'Imp', category: 'Mythology' },
    { text: 'Troll', category: 'Mythology' },
    { text: 'Ogre', category: 'Mythology' },
    { text: 'Nymph', category: 'Mythology' },
    { text: 'Giant', category: 'Mythology' },
    { text: 'Elf', category: 'Mythology' },

    { text: 'angelina jolie', category: 'Famous person' },
    { text: 'bob dylan', category: 'Famous person' },
    { text: 'brad pitt', category: 'Famous person' },
    { text: 'bruce lee', category: 'Famous person' },
    { text: 'geronimo', category: 'Famous person' },
    { text: 'greenday', category: 'Famous person' },
    { text: 'kate moss', category: 'Famous person' },
    { text: 'lady gaga', category: 'Famous person' },
    { text: 'lil wayne', category: 'Famous person' },
    { text: 'ludacris', category: 'Famous person' },
    { text: 'mc hammer', category: 'Famous person' },
    { text: 'tom hanks', category: 'Famous person' },
    { text: 'beckham', category: 'Famous person' },
    { text: 'colbert', category: 'Famous person' },
    { text: 'jay leno', category: 'Famous person' },
    { text: 'lincoln', category: 'Famous person' },
    { text: 'picasso', category: 'Famous person' },
    { text: 'rihanna', category: 'Famous person' },
    { text: 'van gogh', category: 'Famous person' },
    { text: 'justin bieber', category: 'Famous person' },
    { text: 'eminem', category: 'Famous person' },
    { text: 'gandhi', category: 'Famous person' },
    { text: 'madonna', category: 'Famous person' },
    { text: 'pitbull', category: 'Famous person' },
	{ text: 'vincent van gogh', category: 'Famous person' },
	{ text: 'Donald Trump', category: 'Famous person' },

    { text: 'archery', category: 'Sports' },
    { text: 'baseball', category: 'Sports' },
    { text: 'Basketball', category: 'Sports' },
    { text: 'bowling', category: 'Sports' },
    { text: 'Boxing', category: 'Sports' },
    { text: 'Curling', category: 'Sports' },
	{ text: 'Cricket', category: 'Sports' },
    { text: 'dumbbell', category: 'Sports' },
    { text: 'fencing', category: 'Sports' },
    { text: 'fishing', category: 'Sports' },
    { text: 'football', category: 'Sports' },
    { text: 'frisbee', category: 'Sports' },
    { text: 'goal post', category: 'Sports' },
    { text: 'Golf', category: 'Sports' },
    { text: 'half pipe', category: 'Sports' },
    { text: 'handball', category: 'Sports' },
    { text: 'homerun', category: 'Sports' },
    { text: 'iceskate', category: 'Sports' },
    { text: 'javelin', category: 'Sports' },
    { text: 'jumprope', category: 'Sports' },
    { text: 'Lacrosse', category: 'Sports' },
    { text: 'longjump', category: 'Sports' },
    { text: 'minigolf', category: 'Sports' },
    { text: 'Netball', category: 'Sports' },
    { text: 'olympics', category: 'Sports' },
    { text: 'pingpong', category: 'Sports' },
    { text: 'rebound', category: 'Sports' },
    { text: 'referee', category: 'Sports' },
	{ text: 'Rock climbing', category: 'Sports' },
    { text: 'slamdunk', category: 'Sports' },
    { text: 'sledding', category: 'Sports' },
	{ text: 'soccer', category: 'Sports' },
    { text: 'Surfing', category: 'Sports' },
	{ text: 'swimming', category: 'Sports' },
	{ text: 'Tennis', category: 'Sports' },
    { text: 'Volleyball', category: 'Sports' },


    { text: 'Autobots', category: 'Pop Culture' },
    { text: 'Catwoman', category: 'Pop Culture' },
    { text: 'Garfield', category: 'Pop Culture' },
    { text: 'iron chef', category: 'Pop Culture' },
    { text: 'splinter', category: 'Pop Culture' },
    { text: 'superman', category: 'Pop Culture' },
    { text: 'aladdin', category: 'Pop Culture' },
    { text: 'aquaman', category: 'Pop Culture' },
    { text: 'asterix', category: 'Pop Culture' },
    { text: 'hawkeye', category: 'Pop Culture' },
    { text: 'metroid', category: 'Pop Culture' },
    { text: 'Pikachu', category: 'Pop Culture' },
    { text: 'riddler', category: 'Pop Culture' },
    { text: 'rugrats', category: 'Pop Culture' },
    { text: 'Twoface', category: 'Pop Culture' },
    { text: 'avatar', category: 'Pop Culture' },
    { text: 'barbie', category: 'Pop Culture' },
    { text: 'batman', category: 'Pop Culture' },
    { text: 'beavis', category: 'Pop Culture' },
    { text: 'bowser', category: 'Pop Culture' },
    { text: 'Legend of Zelda', category: 'Pop Culture' },
    { text: 'Mickey Mouse', category: 'Pop Culture' },
    { text: 'Voldemort', category: 'Pop Culture' },
    { text: 'Conan the Barbarian', category: 'Pop Culture' },
    { text: 'The Simpsons', category: 'Pop Culture' },
    { text: 'Rick & Morty', category: 'Pop Culture' },
    { text: 'Kermit', category: 'Pop Culture' },
    { text: 'Spongebob', category: 'Pop Culture' },
    { text: 'Simba', category: 'Pop Culture' },
	{ text: 'Scooby Doo', category: 'Pop Culture' },
	
    { text: 'Artist', category: 'Profession' },
    { text: 'Assassin', category: 'Profession' },
    { text: 'Barber', category: 'Profession' },
    { text: 'Butcher', category: 'Profession' },
    { text: 'Captain', category: 'Profession' },
    { text: 'Cashier', category: 'Profession' },
	{ text: 'Chef', category: 'Profession' },
	{ text: 'Clown', category: 'Profession' },
	{ text: 'Cook', category: 'Profession' },
    { text: 'Cowboy', category: 'Profession' },
    { text: 'Cowgirl', category: 'Profession' },
    { text: 'Dentist', category: 'Profession' },
    { text: 'DJ', category: 'Profession' },
    { text: 'Doctor', category: 'Profession' },
    { text: 'Drummer', category: 'Profession' },
    { text: 'Farmer', category: 'Profession' },
    { text: 'Firefighter', category: 'Profession' },
	{ text: 'Hacker', category: 'Profession' },
    { text: 'Gangster', category: 'Profession' },
    { text: 'Gardener', category: 'Profession' },
    { text: 'Gymnast', category: 'Profession' },
    { text: 'Janitor', category: 'Profession' },
	{ text: 'Lawyer', category: 'Profession' },
    { text: 'Magician', category: 'Profession' },
    { text: 'Mailman', category: 'Profession' },
    { text: 'Milkman', category: 'Profession' },
    { text: 'Movie Director', category: 'Profession' },
    { text: 'Opera Singer', category: 'Profession' },
    { text: 'Painter', category: 'Profession' },
	{ text: 'Pilot', category: 'Profession' },
    { text: 'Plumber', category: 'Profession' },
    { text: 'Policeman', category: 'Profession' },
    { text: 'Poolboy', category: 'Profession' },
    { text: 'Priest', category: 'Profession' },
    { text: 'Princess', category: 'Profession' },
    { text: 'Sheriff', category: 'Profession' },
    { text: 'Soldier', category: 'Profession' },
    { text: 'Surgeon', category: 'Profession' },
    { text: 'Teacher', category: 'Profession' },
    { text: 'Teacher', category: 'Profession' },
    { text: 'Waiter', category: 'Profession' },
    { text: 'Warrior', category: 'Profession' },
    { text: 'Window cleaner ', category: 'Profession' },
    { text: 'Wrestler', category: 'Profession' },

    { category: 'Animal', text: 'aardvark' },
    { category: 'Animal', text: 'Alpaca' },
    { category: 'Animal', text: 'ant' },
    { category: 'Animal', text: 'anteater' },
    { category: 'Animal', text: 'armadillo' },
    { category: 'Animal', text: 'baboon' },
    { category: 'Animal', text: 'badger' },
	{ category: 'Animal', text: 'bat' },
    { category: 'Animal', text: 'bear' },
    { category: 'Animal', text: 'beaver' },
    { category: 'Animal', text: 'bee' },
    { category: 'Animal', text: 'bird' },
    { category: 'Animal', text: 'buffalo' },
    { category: 'Animal', text: 'bull' },
    { category: 'Animal', text: 'calf' },
    { category: 'Animal', text: 'camel' },
    { category: 'Animal', text: 'cat' },
    { category: 'Animal', text: 'Caterpillar' },
	{ category: 'Animal', text: 'catfish' },
	{ category: 'Animal', text: 'Chameleon' },
    { category: 'Animal', text: 'cheetah' },
    { category: 'Animal', text: 'chicken' },
    { category: 'Animal', text: 'chimpanzee' },
    { category: 'Animal', text: 'Chihuahua ' },
    { category: 'Animal', text: 'Cicada ' },
	{ category: 'Animal', text: 'cockroach' },
    { category: 'Animal', text: 'cow' },
    { category: 'Animal', text: 'crane' },
	{ category: 'Animal', text: 'crab' },
    { category: 'Animal', text: 'Cricket' },
    { category: 'Animal', text: 'crocodile' },
    { category: 'Animal', text: 'deer' },
    { category: 'Animal', text: 'dinosaur' },
    { category: 'Animal', text: 'dog' },
    { category: 'Animal', text: 'dolphin' },
    { category: 'Animal', text: 'donkey' },
    { category: 'Animal', text: 'duck' },
	{ category: 'Animal', text: 'dragonfly' },
    { category: 'Animal', text: 'eagle' },
    { category: 'Animal', text: 'elephant' },
	{ category: 'Animal', text: 'firefly' },
    { category: 'Animal', text: 'fish' },
    { category: 'Animal', text: 'flamingo' },
    { category: 'Animal', text: 'fly' },
    { category: 'Animal', text: 'fox' },
    { category: 'Animal', text: 'Frog' },
    { category: 'Animal', text: 'Giraffe' },
    { category: 'Animal', text: 'goat' },
    { category: 'Animal', text: 'goldfish' },
	{ category: 'Animal', text: 'Goose' },
    { category: 'Animal', text: 'gorilla' },
    { category: 'Animal', text: 'Grasshopper' },
    { category: 'Animal', text: 'hamster' },
    { category: 'Animal', text: 'hippopotamus' },
    { category: 'Animal', text: 'horse' },
    { category: 'Animal', text: 'hyena' },
    { category: 'Animal', text: 'jaguar' },
    { category: 'Animal', text: 'kangaroo' },
    { category: 'Animal', text: 'kitten' },
    { category: 'Animal', text: 'ladybug' },
    { category: 'Animal', text: 'leopard' },
    { category: 'Animal', text: 'lion' },
    { category: 'Animal', text: 'lizard' },
    { category: 'Animal', text: 'llama' },
    { category: 'Animal', text: 'lobster' },
    { category: 'Animal', text: 'mammoth' },
    { category: 'Animal', text: 'monkey' },
    { category: 'Animal', text: 'mosquito' },
	{ category: 'Animal', text: 'moose' },
    { category: 'Animal', text: 'Mouse' },
    { category: 'Animal', text: 'narwhal' },
    { category: 'Animal', text: 'octopus' },
    { category: 'Animal', text: 'ostrich' },
    { category: 'Animal', text: 'otter' },
    { category: 'Animal', text: 'owl' },
    { category: 'Animal', text: 'oyster' },
    { category: 'Animal', text: 'panda' },
    { category: 'Animal', text: 'Pangolin' },
	{ category: 'Animal', text: 'parrot' },
    { category: 'Animal', text: 'panther' },
    { category: 'Animal', text: 'peacock' },
    { category: 'Animal', text: 'pelican' },
    { category: 'Animal', text: 'penguin' },
    { category: 'Animal', text: 'pig' },
    { category: 'Animal', text: 'pigeon' },
	{ category: 'Animal', text: 'pitbull' },
	{ category: 'Animal', text: 'Platypus' },
    { category: 'Animal', text: 'porcupine' },
	{ category: 'Animal', text: 'Poodle' },
    { category: 'Animal', text: 'puppy' },
    { category: 'Animal', text: 'rabbit' },
    { category: 'Animal', text: 'raccoon' },
    { category: 'Animal', text: 'rat' },
    { category: 'Animal', text: 'reindeer' },
	{ category: 'Animal', text: 'reptile' },
    { category: 'Animal', text: 'rhinoceros' },
    { category: 'Animal', text: 'rooster' },
    { category: 'Animal', text: 'scorpion' },
    { category: 'Animal', text: 'seagull' },
    { category: 'Animal', text: 'seahorse' },
    { category: 'Animal', text: 'Seal' },
    { category: 'Animal', text: 'shark' },
    { category: 'Animal', text: 'sheep' },
    { category: 'Animal', text: 'shrimp' },
	{ category: 'Animal', text: 'Skunk' },
    { category: 'Animal', text: 'snail' },
    { category: 'Animal', text: 'snake' },
    { category: 'Animal', text: 'spider' },
    { category: 'Animal', text: 'squid' },
    { category: 'Animal', text: 'squirrel' },
    { category: 'Animal', text: 'starfish' },
    { category: 'Animal', text: 'stork' },
    { category: 'Animal', text: 'swan' },
    { category: 'Animal', text: 'tadpole' },
    { category: 'Animal', text: 'tiger' },
    { category: 'Animal', text: 'toad' },
    { category: 'Animal', text: 'tropical fish' },
    { category: 'Animal', text: 'tuna' },
    { category: 'Animal', text: 'turkey' },
    { category: 'Animal', text: 'turtle' },
    { category: 'Animal', text: 'tortoise' },
	{ category: 'Animal', text: 'vulture' },
	{ category: 'Animal', text: 'walrus' },
    { category: 'Animal', text: 'whale' },
    { category: 'Animal', text: 'wolf' },
    { category: 'Animal', text: 'Wombat' },
    { category: 'Animal', text: 'Worm' },
	{ category: 'Animal', text: 'zebra' },

    { text: 'Bacon', category: 'Food' },
    { text: 'Baguette', category: 'Food' },
    { text: 'Barbeque', category: 'Food' },
    { text: 'Beans', category: 'Food' },
    { text: 'Beer', category: 'Food' },
    { text: 'Burrito', category: 'Food' },
	{ text: 'Cake', category: 'Food' },
    { text: 'Cereal', category: 'Food' },
    { text: 'Champagne', category: 'Food' },
    { text: 'Cheese', category: 'Food' },
    { text: 'Chicken Wings', category: 'Food' },
    { text: 'Coffee', category: 'Food' },
    { text: 'Corndog', category: 'Food' },
	{ text: 'Croissant', category: 'Food' },
    { text: 'Cupcake', category: 'Food' },
    { text: 'Eggroll', category: 'Food' },
    { text: 'Espresso', category: 'Food' },
    { text: 'Fast Food', category: 'Food' },
    { text: 'Fish and Chips', category: 'Food' },
    { text: 'Frosting', category: 'Food' },
	{ text: 'Hamburger', category: 'Food' },
    { text: 'Hambone', category: 'Food' },
    { text: 'Hamwich', category: 'Food' },
    { text: 'Hot sauce', category: 'Food' },
    { text: 'Junk Food', category: 'Food' },
    { text: 'Kebab', category: 'Food' },
	{ text: 'Ketchup', category: 'Food' },
	{ text: 'Lasagna', category: 'Food' },
    { text: 'Lemonade', category: 'Food' },
    { text: 'Macaroni', category: 'Food' },
    { text: 'Martini', category: 'Food' },
    { text: 'Mashed Potatoes', category: 'Food' },
    { text: 'Meatballs', category: 'Food' },
	{ text: 'Milk', category: 'Food' },
    { text: 'Mushroom', category: 'Food' },
    { text: 'Mustard', category: 'Food' },
    { text: 'Noodles', category: 'Food' },
    { text: 'Oatmeal', category: 'Food' },
    { text: 'Pancake', category: 'Food' },
    { text: 'Pasta', category: 'Food' },
    { text: 'Pie', category: 'Food' },
    { text: 'Pizza', category: 'Food' },
    { text: 'Popcorn', category: 'Food' },
    { text: 'Pretzel', category: 'Food' },
    { text: 'Pumpkin', category: 'Food' },
    { text: 'Salad', category: 'Food' },
    { text: 'Sandwich', category: 'Food' },
    { text: 'Sausage', category: 'Food' },
    { text: 'SeaFood', category: 'Food' },
    { text: 'Smoothie', category: 'Food' },
    { text: 'Snowcone', category: 'Food' },
    { text: 'Soy Sauce', category: 'Food' },
    { text: 'Sushi', category: 'Food' },
    { text: 'Tea', category: 'Food' },
    { text: 'Tequila', category: 'Food' },
	{ text: 'Waffles', category: 'Food' },
    { text: 'Whiskey', category: 'Food' },


    { text: 'Horror', category: 'Film Genres' },
    { text: 'Action', category: 'Film Genres' },
    { text: 'Thriller', category: 'Film Genres' },
    { text: 'Sci-Fi', category: 'Film Genres' },
    { text: 'Rom-Com', category: 'Film Genres' },
    { text: 'Western', category: 'Film Genres' },
    { text: 'Comedy', category: 'Film Genres' },
    { text: 'Gangster', category: 'Film Genres' },
    { text: 'Slapstick', category: 'Film Genres' },
    { text: 'War', category: 'Film Genres' },
    { text: 'Documentry', category: 'Film Genres' },
    { text: 'Mockumentry', category: 'Film Genres' },
    { text: 'Musical', category: 'Film Genres' },
    { text: 'Animation', category: 'Film Genres' },
    { text: 'Disasters', category: 'Film Genres' },
    { text: 'Zombies', category: 'Film Genres' },
    { text: 'Sport', category: 'Film Genres' },

    { text: 'A Clockwork Orange', category: 'Movies' },
	{ text: 'Armagedon', category: 'Movies' },
    { text: 'Alien', category: 'Movies' },
    { text: 'Austin Powers', category: 'Movies' },
    { text: 'Avengers', category: 'Movies' },
    { text: 'Back to the Future', category: 'Movies' },
    { text: 'Braveheart', category: 'Movies' },
	{ text: 'Beetlejuice', category: 'Movies' },
    { text: 'Die Hard', category: 'Movies' },
    { text: 'E.T.', category: 'Movies' },
    { text: 'Fargo', category: 'Movies' },
    { text: 'Finding Nemo', category: 'Movies' },
    { text: 'Forrest Gump', category: 'Movies' },
	{ text: 'Frozen', category: 'Movies' },
    { text: 'Gladiator', category: 'Movies' },
    { text: 'Golden Eye', category: 'Movies' },
    { text: 'Gone with The Wind', category: 'Movies' },
    { text: 'Groundhog Day', category: 'Movies' },
    { text: 'Home Alone', category: 'Movies' },
    { text: 'Inception', category: 'Movies' },
    { text: 'Indiana Jones', category: 'Movies' },
    { text: 'Inglourious Basterds', category: 'Movies' },
    { text: 'Jaws', category: 'Movies' },
    { text: 'Jurassic Park', category: 'Movies' },
    { text: 'King Kong', category: 'Movies' },
    { text: 'Lion King', category: 'Movies' },
    { text: 'Mary Poppins', category: 'Movies' },
    { text: 'Minority Report', category: 'Movies' },
    { text: 'Mission Impossible', category: 'Movies' },
    { text: 'Monty Python and the Holy Grail', category: 'Movies' },
    { text: 'Princess Bride', category: 'Movies' },
    { text: 'Pulp Fiction', category: 'Movies' },
    { text: 'Rocky Horror Picture Show', category: 'Movies' },
    { text: 'Rocky', category: 'Movies' },
    { text: 'Saving Private Ryan', category: 'Movies' },
    { text: 'Scarface', category: 'Movies' },
    { text: 'Shrek', category: 'Movies' },
    { text: 'Star Wars', category: 'Movies' },
    { text: 'Terminator', category: 'Movies' },
    { text: 'The Good, the Bad and the Ugly', category: 'Movies' },
    { text: 'The Green Mile', category: 'Movies' },
    { text: 'The Lord Of the Rings', category: 'Movies' },
    { text: 'The Matrix', category: 'Movies' },
    { text: 'The Shawshank Redemption', category: 'Movies' },
    { text: 'The Social Network', category: 'Movies' },
    { text: 'The Wizard of Oz', category: 'Movies' },
    { text: 'Titanic', category: 'Movies' },
    { text: 'Toy Story', category: 'Movies' },
    { text: 'West Side Story', category: 'Movies' },
    { text: 'Wonder Woman', category: 'Movies' },
    { text: 'X-Men', category: 'Movies' },
	{ text: 'Robocop', category: 'Movies' },


    { text: 'Sour Candy', category: 'Snacks' },
    { text: 'Twinkie', category: 'Snacks' },
    { text: 'Lollipop', category: 'Snacks' },
    { text: 'Popsicle', category: 'Snacks' },
    { text: 'Skittles', category: 'Snacks' },
    { text: 'Brownie', category: 'Snacks' },
    { text: 'Cookie', category: 'Snacks' },
    { text: 'Doritos', category: 'Snacks' },
    { text: 'Sour Candy', category: 'Snacks' },
    { text: 'Icecream', category: 'Snacks' },

    { text: 'The Pyramids', category: 'Famous Landmark' },
    { text: 'Christ the Redeemer statue', category: 'Famous Landmark' },
    { text: 'The Great Chinese Wall', category: 'Famous Landmark' },
    { text: 'Leaning Tower of Pisa', category: 'Famous Landmark' },
    { text: 'Empire State Building', category: 'Famous Landmark' },
    { text: 'Colosseum', category: 'Famous Landmark' },
    { text: 'The Eiffel Tower', category: 'Famous Landmark' },
    { text: 'Statue of Liberty', category: 'Famous Landmark' },
    { text: 'The Sphinx', category: 'Famous Landmark' },
    { text: 'The Little Mermaid', category: 'Famous Landmark' },
    { text: 'The Taj Mahal', category: 'Famous Landmark' },
    { text: 'Big Ben', category: 'Famous Landmark' },
    { text: 'Loch Ness', category: 'Famous Landmark' },
    { text: 'Brandenburg Gate', category: 'Famous Landmark' },
    { text: 'Acropolis', category: 'Famous Landmark' },
    { text: 'Stonehenge', category: 'Famous Landmark' },
    { text: 'Easter Island', category: 'Famous Landmark' },
    { text: 'Capitol Hill', category: 'Famous Landmark' },
    { text: 'Niagra Falls', category: 'Famous Landmark' },
    { text: 'Mount Rushmore', category: 'Famous Landmark' },
    { text: 'Grand Canyon', category: 'Famous Landmark' },
    { text: 'Fontana de Trevi', category: 'Famous Landmark' },
    { text: 'Sydney Opera House', category: 'Famous Landmark' },
    { text: 'Golden Gate Bridge ', category: 'Famous Landmark' },
    { text: 'The Forbidden City', category: 'Famous Landmark' },
    { text: 'The Kremlin', category: 'Famous Landmark' },
    { text: 'The Louvre ', category: 'Famous Landmark' },
    { text: 'The Hollywood Sign ', category: 'Famous Landmark' },

    { text: 'Cinderella', category: 'Fairytale' },
    { text: 'The Three Little Pigs', category: 'Fairytale' },
    { text: 'The Ugly Duckling', category: 'Fairytale' },
    { text: 'The Tin Soldier', category: 'Fairytale' },
    { text: 'The Tinderbox', category: 'Fairytale' },
    { text: 'The Princess and the Pea', category: 'Fairytale' },
    { text: 'Thumbelina', category: 'Fairytale' },
    { text: 'The Little Mermaid', category: 'Fairytale' },
    { text: 'Thumbelina', category: 'Fairytale' },
    { text: 'The Steadfast Tin Soldier', category: 'Fairytale' },
    { text: "The Emperor's New Clothes", category: 'Fairytale' },
    { text: 'Goldilocks and the Three Bears', category: 'Fairytale' },
    { text: 'Thumbelina', category: 'Fairytale' },
    { text: 'Sleeping Beauty', category: 'Fairytale' },
    { text: 'Snow White', category: 'Fairytale' },
    { text: 'Rapunzel', category: 'Fairytale' },
    { text: 'The Frog Prince', category: 'Fairytale' },
    { text: 'Hansel and Gretel', category: 'Fairytale' },
    { text: 'The Golden Fish', category: 'Fairytale' },
    { text: 'Rumpelstiltskin', category: 'Fairytale' },
    { text: 'The Golden Goose', category: 'Fairytale' },
    { text: 'Puss in Boots', category: 'Fairytale' },
    { text: 'Aladdin', category: 'Fairytale' },
    { text: 'Beauty and the Beast', category: 'Fairytale' },
    { text: 'Ali Baba and the Forty Thieves', category: 'Fairytale' },
    { text: 'Sinbad', category: 'Fairytale' },
    { text: 'The Fisherman and the Jinni', category: 'Fairytale' },
    
]